---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/08/2019 00:08
---
RMenu.Add(
    "personnal",
    "wallet",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "inventory"), "Portefeuille", "Billets disponibles")
)
RMenu.Add(
    "personnal",
    "wallet_give",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "wallet"), "Portefeuille", "Billets disponibles")
)
RMenu.Add(
    "personnal",
    "wallet_list",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "wallet"), "Portefeuille", "Billets disponibles")
)
RMenu.Add(
    "personnal",
    "wallet_act",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "wallet"), "Portefeuille", "Billets disponibles")
)

local filter = {"dollar1", "dollar5", "dollar10", "dollar50", "dollar100", "dollar500"}
local am = {1, 5, 10, 50, 100, 500}
function GetTotalMoney()
    local amount = 0
    for k, v in pairs(Atlantiss.Inventory:GetInventory()) do
        for i = 1, #filter, 1 do
            if k == filter[i] then
                amount = amount + (am[i] * #v)
            end
        end
    end
    return amount
end
function GiveMoneyy(tablee, player)
    for k, v in pairs(tablee) do
        local sendItems = {}
        local itemSent = 0

        for i = 1, v.index - 1, 1 do
            itemSent = itemSent + 1
            table.insert(sendItems, {name = Atlantiss.Inventory:GetInventory()[k][1].name})

            if (itemSent >= 150) then
                math.randomseed(GetGameTimer())
                TriggerPlayerEvent("atlantiss:inventory:addItems", player, sendItems)
                RemoveItemsFromInv(Atlantiss.Inventory:GetInventory()[k][1].name, itemSent)
                sendItems = {}
                itemSent = 0
                Wait(100)
            end
        end

        if (itemSent > 0) then
            math.randomseed(GetGameTimer())
            TriggerPlayerEvent("atlantiss:inventory:addItems", player, sendItems)
            RemoveItemsFromInv(Atlantiss.Inventory:GetInventory()[k][1].name, itemSent)
            sendItems = {}
            itemSent = 0
            Wait(100)
        end
    end
end
function PayMoney(tablee)
    for k, v in pairs(tablee) do
        print(k, v.index)
        for i = 1, v.index - 1, 1 do
            -- print(Atlantiss.Inventory:GetInventory()[k])
            local t = 0
            while Atlantiss.Inventory:GetInventory()[k][t] == nil do
                t = t + 1
                Wait(0)
            end
            if Atlantiss.Inventory:GetInventory()[k] ~= nil then
                Atlantiss.Inventory:RemoveItem(Atlantiss.Inventory:GetInventory()[k][t], true)
            end
        end
    end
end
function AddMoney(_am)
    ShowNotification("~r~Veuillez reessayer. Merci")
    TriggerServerEvent(
        "atlantiss:sendToDiscord",
        26,
        "[ERREUR] Appel d'une fonction désactivée.", 
        "error"
    )
end

local filter = {"dollar1", "dollar5", "dollar10", "dollar50", "dollar100", "dollar500"}
local am = {1, 5, 10, 50, 100, 500}
local m = {
    dollar1 = {
        index = 1,
        label = {0}
    },
    dollar5 = {
        index = 1,
        label = {0}
    },
    dollar10 = {
        index = 1,
        label = {0}
    },
    dollar50 = {
        index = 1,
        label = {0}
    },
    dollar100 = {
        index = 1,
        label = {0}
    },
    dollar500 = {
        index = 1,
        label = {0}
    }
}

local function GetCurrentMoneySelected()
    local mo = 0
    for k, v in pairs(m) do
        if v.visible then
            p = string.gsub(tostring(k), "dollar", "")
            p = tonumber(p)
            mo = mo + (p * (v.index - 1))
        end
    end

    return mo
end

local function Refresh()
    for k, v in pairs(m) do
        if Atlantiss.Inventory:GetInventory()[k] ~= nil then
            v.visible = true
            v.total = #Atlantiss.Inventory:GetInventory()[k]
            for i = 0, #Atlantiss.Inventory:GetInventory()[k], 1 do
                v.label[i + 1] = i
            end
        else
            v.total = 0
            v.visible = false
        end
    end
end
local currentIndex = nil
local currentDollar = {}
Citizen.CreateThread(
    function()
        while true do
            Wait(1)

            if RageUI.Visible(RMenu:Get("personnal", "wallet")) then
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        RageUI.Button(
                            "Argent total",
                            nil,
                            {RightLabel = GetTotalMoney() .. "$"},
                            true,
                            function(_, _, _)
                            end
                        )

                        for k, v in pairs(Atlantiss.Inventory:GetInventory()) do
                            for i = 1, #filter, 1 do
                                if k == filter[i] then
                                    local m = nil
                                    if #v == 1 then
                                        m = RMenu:Get("personnal", "wallet_act")
                                    else
                                        m = RMenu:Get("personnal", "wallet_list")
                                    end
                                    RageUI.Button(
                                        Items[k].label,
                                        nil,
                                        {RightLabel = #v},
                                        true,
                                        function(_, _, S)
                                            if S and #v > 1 then
                                                currentIndex = v
                                            elseif S then
                                                currentDollar = v[1]
                                            end
                                        end,
                                        m
                                    )
                                end
                            end
                        end
                    end,
                    function()
                    end
                )
            end
            if RageUI.Visible(RMenu:Get("personnal", "wallet_act")) then
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        RageUI.Button(
                            "Donner",
                            nil,
                            {},
                            true,
                            function(_, A, S)
                                if S then
                                    Inventory.SelectedItem = currentDollar
                                    Inventory:GiveItem(currentDollar)
                                end
                                if A then
                                    HoverPlayer()
                                end
                            end
                        )
                        RageUI.Button(
                            "Jeter",
                            nil,
                            {},
                            true,
                            function(_, _, S)
                                if S then
                                    local ped = PlayerPedId()
                                    local coords = GetEntityCoords(ped)
                                    local forward = GetEntityForwardVector(ped)
                                    local x, y, z = table.unpack(coords + forward)
                                    local coords = {
                                        x = x,
                                        y = y,
                                        z = z - 1.0
                                    }
                                    local item = {currentDollar}
                                    TriggerPlayerEvent("newProps", -1, item, coords)
                                    Atlantiss.Inventory:RemoveItem(currentDollar, true)
                                    RageUI.CloseAll()
                                end
                            end
                        )
                    end,
                    function()
                    end
                )
            end

            if RageUI.Visible(RMenu:Get("personnal", "wallet_list")) then
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        if currentIndex ~= nil then
                            for i = 1, #currentIndex, 1 do
                                local v = currentIndex[i]

                                if (v ~= nil) then
                                    if (v.data ~= nil and v.data.serial ~= nil) then
                                        v.data.serial = v.data.serial
                                    elseif (v.data ~= nil and v.data.serial == nil) then
                                        v.data.serial = "LS-" .. Random(999999999)
                                    else
                                        v.data = {}
                                        v.data.serial = "LS-" .. Random(999999999)
                                    end
                                end

                                RageUI.Button(
                                    Items[v.name].label .. " #" .. v.data.serial,
                                    nil,
                                    {},
                                    true,
                                    function(_, _, S)
                                        if S then
                                            currentDollar = v
                                        end
                                    end,
                                    RMenu:Get("personnal", "wallet_act")
                                )
                            end
                        else
                            CloseAllMenus()
                        end
                    end,
                    function()
                    end
                )
            end

            if RageUI.Visible(RMenu:Get("personnal", "wallet_give")) then
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        for k, v in pairs(m) do
                            if v.total > 0 then
                                RageUI.List(
                                    Items[k].label .. " (" .. v.total .. "x)",
                                    v.label,
                                    v.index,
                                    nil,
                                    {},
                                    v.visible,
                                    function(_, Active, Selected, Index)
                                        v.index = Index
                                        if Selected then
                                            local ask = KeyboardInput("Combien ? ~r~(MAX " .. v.total .. ")", nil)

                                            ask = tonumber(ask)
                                            if ask ~= nil then
                                                if ask <= v.total then
                                                    v.index = ask + 1
                                                end
                                            end
                                        end
                                    end
                                )
                            else
                                v.index = 1
                            end
                        end

                        if dataonWait.price ~= nil then
                            RageUI.Button(
                                "Donner ",
                                nil,
                                {
                                    RightLabel = "~g~(" ..
                                        dataonWait.price ..
                                            "$)~s~-" ..
                                                GetCurrentMoneySelected() ..
                                                    "$ = " ..
                                                        math.floor(dataonWait.price - GetCurrentMoneySelected()) .. "$"
                                },
                                true,
                                function(_, H, S)
                                    if S and GetPlayerServerIdInDirection(5.0) then
                                        local mT = math.floor(dataonWait.price - GetCurrentMoneySelected())
                                        if mT <= 0 then
                                            ShowNotification("~b~Paiement effectué")
                                            local t = {}
                                            for k, v in pairs(m) do
                                                if #v.label > 1 then
                                                    t[k] = v
                                                end
                                                --v.index = 1
                                            end
                                            GiveMoneyy(t, GetPlayerServerIdInDirection(5.0))

                                            RageUI.GoBack()
                                        else
                                            ShowNotification("~r~Vous n'avez pas donner assez d'argent")
                                        end
                                    elseif not GetPlayerServerIdInDirection(5.0) then
                                        ShowNotification("~r~Aucun joueur")
                                    end
                                end
                            )
                        end
                    end,
                    function()
                    end
                )
            end
        end
    end
)

function Random(max)
    local c = 0
    TriggerEvent(
        "getRandom",
        function(m)
            c = m
        end,
        max
    )
    return c
end
