Ora.NpcJobs.Wholesaler = {}
Ora.NpcJobs.Wholesaler.ItemsPerJob = {


  grossiste = {
    ["medica4"] = {"Anti-Dépresseurs", 2},
    ["medica1"] = {"Anti-Douleur", 2},
    ["medica2"] = {"Anti-Inflammatoires", 2},
    ["camera"] = {"Appareil photo", 100},
    ["aperitif"] = {"Apéritif", 1},
    ["bandage"] = {"Bandage", 2},
    ["blocnote"] = {"Blocnote", 2},
    ["boeufkobe"] = {"Boeuf de Kobe", 2},
    ["boissonpearl"] = {"Boisson Pearl's", 2},
    ["boissontaco"] = {"Boisson taco loco", 2},
    ["cafe"] = {"Cafe", 1},
    ["bigcam "] = {"Caméra sur épaule", 100},
    ["fishingrod"] = {"Cannes à pêche", 5},
    ["caviar"] = {"Caviar Beluga", 40},
    ["chips"] = {"Chips", 2},
    ["churros"] = {"Churros", 2},
    ["cheddar"] = {"Cheddar", 2},
    ["chocolat"] = {"chocolat", 2},
    ["fraise"] = {"Fraise", 2},
    ["ciseaux"] = {"Ciseaux", 2},
    ["wrench"] = {"Clé anglaise", 100},
    ["cone"] = {"Cone", 1},
    ["coupedefruit"] = {"Coupe de fruits", 2},
    ["medica3"] = {"Crème analgésique", 2},
    ["medica5"] = {"Crème pour brûlures", 2},
    ["fish15"] = {"Crevettes", 2},
    ["fish6"] = {"Daurade", 5},
    ["donut"] = {"Donut", 2},
    ["water"] = {"Eau", 1},
    ["tattoo_ink"] = {"Encre tatouage", 1},
    ["fire_extinguisher"] = {"Extincteur", 10},
    ["feuillenori"] = {"Feuille de Nori", 2},
    ["gascan"] = {"Jerrican", 2},
    ["binoculars"] = {"Jumelles", 3},
    ["jus"] = {"Jus de leechi", 1},
    ["lavage"] = {"Kit de nettoyage", 5},
    ["repairbox2"] = {"Kit de réparation", 20},
    ["litchi"] = {"Litchi", 2},
    ["mentos"] = {"Mentos", 1},
    ["micro "] = {"Micro", 80},
    ["moules"] = {"Moules", 2},
    ["coco"] = {"Noix de coco", 2},
    ["noddle"] = {"Nouilles", 2},
    ["oeuf"] = {"oeuf", 2},
    ["parapluie"] = {"Parapluie", 2},
    ["perche"] = {"Perche de micro", 100},
    ["crowbar"] = {"Pied de biche", 100},
    ["piecedeboeuf"] = {"Pièce de boeuf", 2},
    ["pinces"] = {"Pinces", 2},
    --["chicken"] = {"Poulet", 2},
    ["plateaufruitsmer"] = {"Plateau de fruits de mer", 2},
    ["radio"] = {"Radio", 3},
    ["rice"] = {"Riz", 2},
    ["sake"] = {"Sake", 5},
    ["salade"] = {"Salade", 2},
    ["fish12"] = {"Saumon", 5},
    ["cola"] = {"Soda", 2},
    ["sushi"] = {"Sushi", 5},
    ["tapas"] = {"Tapas", 1},
    ["tartefraise"] = {"Tarte aux fraises", 2},
    ["fish4"] = {"Thon rouge", 5},
    ["fabric"] = {"Tissu", 1},
    ["makeup"] = {"Trousse de maquillage", 5},
    ["medikit"] = {"Trousse de soin", 10},
    ["veloute"] = {"Velouté", 2},
    ["courgette"] = {"Courgette", 2},
    ["caramel"] = {"Caramel", 2},
    ["latecoco"] = {"Lait de coco", 2},
    ["meat"] = {"Viande Crue", 2},
    ["sirup"] = {"Sirop", 1},
    ["mint"] = {"Menthe", 1},
    ["orangejuice"] = {"Jus d'orange", 1},
    ["pineapplejuice"] = {"Jus d'ananas", 1}
  },
  



 --[[ night = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },
  henhouse = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },
  unicorn = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },
  tequilala = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },]]
  --[[restaurant = {
    --["bread"] = {"Pain", 25},
    ["aperitif"] = {"Apéritif", 5},
    ["entreepearl"] = {"Tartare de thon-rouge", 5},
    ["entreepearl2"] = {"Carpaccio de bar", 5},
    ["platpearl"] = {"Plat Pearl's", 5},
    ["poissontahitienne"] = {"Poisson à la Tahitienne", 20},
    ["boissonpearl"] = {"Boisson Pearl's", 5},
    --["burgerpoisson"] = {"Burger de poisson", 20},
    ["caviar"] = {"Caviar Beluga", 100},
    ["tatakithon"] = {"Tataki de thon", 20},
    --["milk"] = {"Lait", 20},
    ["fish12"] = {"Saumon", 100},
    ["fish6"] = {"Daurade", 20},
    --["whisky"] = {"Bouteille de whisky", 100},
    --["vodka"] = {"Bouteille de vodka", 80},
    --["cognac"] = {"Bouteille de cognac", 100},
    --["rhum"] = {"Bouteille de rhum", 85},
    --["tequila"] = {"Bouteille de tequila", 80},
    --["red_wine"] = {"Bouteille de vin rouge", 70},
    --["high_quality_wine"] = {"Bouteille de grand cru", 100},
    --["white_wine"] = {"Bouteille de vin blanc", 70},
    --["beer"] = {"Bière", 50},
    --["jus_raisin"] = {"Jus de raisin", 40},
    --["champagne"] = {"Bouteille de champage", 200},

  },]]
--[[  ltdsud = {
    ["pinces"] = {"Pinces", 5},
    ["radio"] = {"Radio", 10},
    ["tel"] = {"Téléphone", 10},
    ["parapluie"] = {"Parapluie", 5},
    ["ciseaux"] = {"Ciseaux", 5},
    ["binoculars"] = {"Jumelles", 10},
    ["gascan"] = {"Jerrican", 5},
    ["blocnote"] = {"Blocnote", 5},
    ["makeup"] = {"Trousse de maquillage", 25},
    ["tapas"] = {"Tapas", 3},
    ["cafe"] = {"Cafe", 2},
    ["jus"] = {"Jus de leechi", 3},
    ["mentos"] = {"Mentos", 2},
    ["water"] = {"Eau", 1},
    ["cola"] = {"Soda", 5},
    ["ricemilk"] = {"Lait de riz", 2},
    ["chips"] = {"Chips", 5},
    ["fishingrod"] = {"Cannes à pêche", 25},
    -- ["speaker"] = {"Radio portative", 350},
  },
  ltdnord = {
    ["pinces"] = {"Pinces", 5},
    ["radio"] = {"Radio", 10},
    ["parapluie"] = {"Parapluie", 5},
    ["ciseaux"] = {"Ciseaux", 5},
    ["binoculars"] = {"Jumelles", 10},
    ["gascan"] = {"Jerrican", 5},
    ["blocnote"] = {"Blocnote", 5},
    ["makeup"] = {"Trousse de maquillage", 25},
    ["tapas"] = {"Tapas", 3},
    ["cafe"] = {"Cafe", 2},
    ["jus"] = {"Jus de leechi", 3},
    ["mentos"] = {"Mentos", 2},
    ["water"] = {"Eau", 1},
    ["cola"] = {"Soda", 5},
    --["ricemilk"] = {"Lait de riz", 2},
    ["chips"] = {"Chips", 5},
    ["fishingrod"] = {"Cannes à pêche", 25},
    -- ["speaker"] = {"Radio portative", 350},
  },]]
--[[  yellowjack = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },
  bahamas = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },]]
--[[  burgershot = {
    --["milk"] = {"Lait", 30},
    ["chicken"] = {"Poulet", 50},
    --["bread"] = {"Pain", 25},
   -- ["pommeterre"] = {"Pomme de terre", 45},
    ["meat"] = {"Viande Crue", 5},
    --["jus_raisin"] = {"Jus de raisin", 40},
   -- ["cola"] = {"Soda", 5},
    ["donut"] = {"Donut", 5}
  },]]
  --[[osakatsubaki = {
    ["rice"] = {"Riz", 5},
    ["feuillenori"] = {"Feuille de Nori", 5},
    ["bouillon"] = {"Bouillon", 5},
    ["noddle"] = {"Nouilles", 5},
    ["sushi"] = {"Sushi", 50},
    ["tonkatsu"] = {"Tonkatsu", 50},
    ["onigiri"] = {"Onigiri", 50},
    ["ramen"] = {"Ramen", 50},
    ["sake"] = {"Sake", 20},
    ["aperitif"] = {"Apéritif", 5},
    ["filet"] = {"Filet", 5},
    ["fish12"] = {"Saumon", 50},
    ["milk"] = {"Lait", 30},
  },]]
--[[  distillerie = {
    ["pommeterre"] = {"Pomme de terre", 45},
    ["cereale"] = {"Céréale", 45},
  },]]
  -- [""] = {},
  -- [""] = {},
  -- [""] = {},
  -- [""] = {},
}

function Ora.NpcJobs.Wholesaler:GetJobName()
  return "Wholesaler"
end

function Ora.NpcJobs.Wholesaler:Debug(message)
  if (Ora:IsDebug()) then
    Citizen.Trace(string.format("^2[Job %s / %s] ^3%s^7.\n",  Ora.NpcJobs:GetModuleName(), Ora.NpcJobs.Wholesaler:GetJobName(), message))
  end
end

Ora.NpcJobs:Register(Ora.NpcJobs.Wholesaler:GetJobName())
