Ora.NpcJobs.Wholesaler = {}
Ora.NpcJobs.Wholesaler.ItemsPerJob = {
  ammunation = {
    ["metalpiece11"] = {"Chassis de Tazer", 250},
    ["metalpiece1"] = {"Chassis de pistolet", 1250},
    ["metalpiece2"] = {"Chassis de fusil de chasse", 750},
    ["metalpiece3"] = {"Chassis de fusil à pompe", 750},
    ["metalpiece4"] = {"Chassis de mitraillette", 2450},
    ["metalpiece5"] = {"Chassis de fusil d'assaut", 3950},
    ["metalpiece6"] = {"Chassis de fusil a lunette", 17500},
    ["metalpiece7"] = {"Queue de détente Acier", 300},
    ["metalpiece8"] = {"Renfort protection en acier", 300},
    ["metalpiece9"] = {"Canon léger", 850},
    ["metalpiece10"] = {"Canon renforcé", 1050},
    ["metalpiece12"] = {"Renfort protection acier renforcé", 400},
    ["metalpiece13"] = {"Plaquette en acier", 400},
    ["metalpiece14"] = {"Plaquette en acier renforcé", 800},
    ["woodpiece1"] = {"Poignée en bois", 300},
    ["woodpiece2"] = {"Plaquette en bois", 200},
    ["woodpiece3"] = {"Crosse en bois", 500},
    ["woodpiece4"] = {"Renfort protection en bois", 12000},
    ["plasticpiece1"] = {"Poignée ABS", 50},
    ["plasticpiece2"] = {"Plaquette ABS", 100},
    ["plasticpiece3"] = {"Crosse ABS", 200},
    ["plasticpiece4"] = {"Queue de détente ABS", 150},
    ["plasticpiece5"] = {"Renfort protection en ABS", 150},
    ["poolcue"] = {"Queue de billard", 100},
    ["knuckle"] = {"Poing américain", 100},
    ["hammer"] = {"Poing américain", 100},
    ["batte"] = {"Batte de baseball", 100},
    ["knife"] = {"Couteau", 100},
    ["dagger"] = {"Dague", 100},
    ["wrench"] = {"Clé anglaise", 100},

  },
  bennys = {
    ["repairbox"] = {"Boite à outils", 350},
    ["repairbox2"] = {"Kit de réparation", 450},
    ["chariot"] = {"Chariot", 50},
    ["cone"] = {"Cone", 10},
    ["wrench"] = {"Clé anglaise", 250},
    ["hammer"] = {"Marteau", 250},
    ["crowbar"] = {"Pied de biche", 250},
    ["masse"] = {"Masse", 250},
    ["lavage"] = {"Kit de nettoyage", 25},
    ["driftwheels"] = {"4 Roues de drift", 1250},
    ["roadwheels"] = {"4 Roues de route", 1250},
  },
  mecano = {
    ["repairbox"] = {"Boite à outils", 350},
    ["repairbox2"] = {"Kit de réparation", 450},
    ["chariot"] = {"Chariot", 50},
    ["cone"] = {"Cone", 10},
    ["wrench"] = {"Clé anglaise", 250},
    ["hammer"] = {"Marteau", 250},
    ["crowbar"] = {"Pied de biche", 250},
    ["masse"] = {"Masse", 250},
    ["lavage"] = {"Kit de nettoyage", 25},
    ["driftwheels"] = {"4 Roues de drift", 1250},
    ["roadwheels"] = {"4 Roues de route", 1250},
  },
  mecano2 = {
    ["repairbox"] = {"Boite à outils", 350},
    ["repairbox2"] = {"Kit de réparation", 450},
    ["chariot"] = {"Chariot", 50},
    ["cone"] = {"Cone", 10},
    ["wrench"] = {"Clé anglaise", 250},
    ["hammer"] = {"Marteau", 250},
    ["crowbar"] = {"Pied de biche", 250},
    ["masse"] = {"Masse", 250},
    ["lavage"] = {"Kit de nettoyage", 25},
    ["driftwheels"] = {"4 Roues de drift", 1250},
    ["roadwheels"] = {"4 Roues de route", 1250},
  },
  caroccasions = {
    ["repairbox"] = {"Boite à outils", 350},
    ["repairbox2"] = {"Kit de réparation", 450},
    ["chariot"] = {"Chariot", 50},
    ["cone"] = {"Cone", 10},
    ["wrench"] = {"Clé anglaise", 250},
    ["hammer"] = {"Marteau", 250},
    ["crowbar"] = {"Pied de biche", 250},
    ["masse"] = {"Masse", 250},
    ["lavage"] = {"Kit de nettoyage", 25},
  },
  lsms = {
    ["medbox"] = {"Boite medical", 150},
    ["medikit"] = {"Trousse de soin", 200},
    ["mec"] = {"Médicament", 75},
    ["cone"] = {"Cone", 10},
    ["wrench"] = {"Clé anglaise", 250},
    ["hammer"] = {"Marteau", 250},
    ["crowbar"] = {"Pied de biche", 250},
    ["masse"] = {"Masse", 250},
    ["lavage"] = {"Kit de nettoyage", 25},
  },
  carwash = {
    ["lavage"] = {"Kit de nettoyage", 25},
  },
  night = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
  },
  henhouse = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
  },
  unicorn = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
  },
  tequilala = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
  },
  restaurant = {
    ["bread"] = {"Pain", 25},
    ["aperitif"] = {"Apéritif", 5},
    ["entreepearl"] = {"Tartare de thon-rouge", 5},
    ["entreepearl2"] = {"Carpaccio de bar", 5},
    ["platpearl"] = {"Plat Pearl's", 5},
    ["poissontahitienne"] = {"Poisson à la Tahitienne", 20},
    ["boissonpearl"] = {"Boisson Pearl's", 5},
    ["burgerpoisson"] = {"Burger de poisson", 20},
    ["caviar"] = {"Caviar Beluga", 100},
    ["tatakithon"] = {"Tataki de thon", 20},
    ["milk"] = {"Lait", 20},
    ["fish12"] = {"Saumon", 100},
    ["fish6"] = {"Daurade", 20},
  },
  ltdsud = {
    ["pinces"] = {"Pinces", 5},
    ["radio"] = {"Radio", 10},
    ["parapluie"] = {"Parapluie", 5},
    ["ciseaux"] = {"Ciseaux", 5},
    ["binoculars"] = {"Jumelles", 10},
    ["gascan"] = {"Jerrican", 5},
    ["blocnote"] = {"Blocnote", 5},
    ["makeup"] = {"Trousse de maquillage", 25},
    ["tapas"] = {"Tapas", 3},
    ["cafe"] = {"Cafe", 2},
    ["jus"] = {"Jus de leechi", 3},
    ["mentos"] = {"Mentos", 2},
    ["water"] = {"Eau", 1},
    ["cola"] = {"Soda", 5},
    ["ricemilk"] = {"Lait de riz", 2},
    ["chips"] = {"Chips", 5},
    ["fishingrod"] = {"Cannes à pêche", 25},
    -- ["speaker"] = {"Radio portative", 350},
  },
  ltdnord = {
    ["pinces"] = {"Pinces", 5},
    ["radio"] = {"Radio", 10},
    ["parapluie"] = {"Parapluie", 5},
    ["ciseaux"] = {"Ciseaux", 5},
    ["binoculars"] = {"Jumelles", 10},
    ["gascan"] = {"Jerrican", 5},
    ["blocnote"] = {"Blocnote", 5},
    ["makeup"] = {"Trousse de maquillage", 25},
    ["tapas"] = {"Tapas", 3},
    ["cafe"] = {"Cafe", 2},
    ["jus"] = {"Jus de leechi", 3},
    ["mentos"] = {"Mentos", 2},
    ["water"] = {"Eau", 1},
    ["cola"] = {"Soda", 5},
    ["ricemilk"] = {"Lait de riz", 2},
    ["chips"] = {"Chips", 5},
    ["fishingrod"] = {"Cannes à pêche", 25},
    -- ["speaker"] = {"Radio portative", 350},
  },
  yellowjack = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
  },
  bahamas = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
  },
  burgershot = {
    ["milk"] = {"Lait", 30},
    ["chicken"] = {"Poulet", 50},
    ["bread"] = {"Pain", 25},
    ["pommeterre"] = {"Pomme de terre", 45},
    ["meat"] = {"Viande Crue", 5},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["cola"] = {"Soda", 5},
    ["donut"] = {"Donut", 5}
  },
  osakatsubaki = {
    ["rice"] = {"Riz", 5},
    ["feuillenori"] = {"Feuille de Nori", 5},
    ["bouillon"] = {"Bouillon", 5},
    ["noddle"] = {"Nouilles", 5},
    ["sushi"] = {"Sushi", 50},
    ["tonkatsu"] = {"Tonkatsu", 50},
    ["onigiri"] = {"Onigiri", 50},
    ["ramen"] = {"Ramen", 50},
    ["sake"] = {"Sake", 20},
    ["aperitif"] = {"Apéritif", 5},
    ["filet"] = {"Filet", 5},
    ["fish12"] = {"Saumon", 50},
    ["milk"] = {"Lait", 30},
  },
  distillerie = {
    ["pommeterre"] = {"Pomme de terre", 45},
    ["cereale"] = {"Céréale", 45},
  },
  lfsd = {
    ["fire_extinguisher"] = {"Extincteur", 25},
  },
  -- [""] = {},
  -- [""] = {},
  -- [""] = {},
  -- [""] = {},
}

function Ora.NpcJobs.Wholesaler:GetJobName()
  return "Wholesaler"
end

function Ora.NpcJobs.Wholesaler:Debug(message)
  if (Ora:IsDebug()) then
    Citizen.Trace(string.format("^2[Job %s / %s] ^3%s^7.\n",  Ora.NpcJobs:GetModuleName(), Ora.NpcJobs.Wholesaler:GetJobName(), message))
  end
end

Ora.NpcJobs:Register(Ora.NpcJobs.Wholesaler:GetJobName())
