Ora.NpcJobs.Wholesaler = {}
Ora.NpcJobs.Wholesaler.ItemsPerJob = {


  grossiste = {
    ["batte"] = {"Batte de baseball", 80},
    ["metalpiece9"] = {"Canon léger", 400},
    ["metalpiece10"] = {"Canon renforcé", 500},
    ["metalpiece6"] = {"Chassis de fusil à lunette", 8000},
    ["metalpiece3"] = {"Chassis de fusil à pompe", 300},
    ["metalpiece5"] = {"Chassis de fusil d'assaut", 1800},
    ["metalpiece2"] = {"Chassis de fusil de chasse", 300},
    ["metalpiece4"] = {"Chassis de mitraillette", 1200},
    ["metalpiece1"] = {"Chassis de pistolet", 600},
    ["metalpiece11"] = {"Chassis de Tazer", 150},
    ["golf"] = {"Club de golf", 80},
    ["knife"] = {"Couteau", 80},
    ["knife1"] = {"Cran d'arrêt", 200},
    ["plasticpiece3"] = {"Crosse ABS", 90},
    ["woodpiece3"] = {"Crosse en bois", 200},
    ["teargas"] = {"Gaz lacrymo", 20},
    ["hatchet"] = {"Hachette", 180},
    ["flashlight"] = {"Lampe torche", 20},
    ["nightstick"] = {"Matraque", 20},
    ["hammer"] = {"Marteau", 80},    
    ["snip"] = {"Munition .300 magnum", 1},
    ["cab"] = {"Munition 223. Remington", 1}, --mun mousquet
    ["acp45"] = {"Munition 45ACP", 1},
    ["cab2"] = {"Munition 5.56 NATO", 1},
    ["mm9"] = {"Munition 9mm", 1},
    ["calibre12"] = {"Munition Calibre 12", 1},
    ["crowbar"] = {"Pied de biche", 80},
    ["plasticpiece2"] = {"Plaquette ABS", 40},
    ["metalpiece13"] = {"Plaquette en acier", 200},
    ["metalpiece14"] = {"Plaquette en acier renforcé", 350},
    ["woodpiece2"] = {"Plaquette en bois", 75},
    ["plasticpiece1"] = {"Poignée ABS", 20},
    ["woodpiece1"] = {"Poignée en bois", 100},
    ["knuckle"] = {"Poing américain", 80},
    ["poolcue"] = {"Queue de billard", 80},
    ["plasticpiece4"] = {"Queue de détente ABS", 70},
    ["metalpiece7"] = {"Queue de détente Acier", 100},
    ["plasticpiece5"] = {"Renfort protection en ABS", 70},
    ["metalpiece8"] = {"Renfort protection en acier", 100},    
    ["metalpiece12"] = {"Renfort protection acier renforcé", 200},
    ["woodpiece4"] = {"Renfort protection en bois", 5000},
    
    ["repairbox"] = {"Boite à outils", 150},
    ["chariot"] = {"Chariot", 20},
    ["wrench"] = {"Clé anglaise", 100},
    ["cone"] = {"Cone", 1},
    ["repairbox2"] = {"Kit de réparation", 20},   
    ["crowbar"] = {"Pied de biche", 100},

    ["lavage"] = {"Kit de nettoyage", 5},

    ["medbox"] = {"Boite medical", 8},
    ["fire_extinguisher"] = {"Extincteur", 10},
    ["medbag"] = {"Sac medical", 10},
    ["medikit"] = {"Trousse de soin", 20},

    ["bigcam "] = {"Caméra sur épaule", 120}, 
    ["micro "] = {"Micro", 20},
    ["perche"] = {"Perche de micro", 30},

    ["aperitif"] = {"Apéritif", 2},
    ["boissonpearl"] = {"Boisson Pearl's", 2},
    ["entreepearl2"] = {"Carpaccio de bar", 2},
    ["caviar"] = {"Caviar Beluga", 40},
    ["fish6"] = {"Daurade", 8},
    ["platpearl"] = {"Plat Pearl's", 2},
    ["poissontahitienne"] = {"Poisson à la Tahitienne", 8},
    ["fish12"] = {"Saumon", 40},
    ["tatakithon"] = {"Tataki de thon", 8},
    ["entreepearl"] = {"Tartare de thon-rouge", 2},

    ["aperitif"] = {"Apéritif", 2},
    ["blocnote"] = {"Blocnote", 2},
    ["bouillon"] = {"Bouillon", 2},
    ["cafe"] = {"Cafe", 1},
    ["fishingrod"] = {"Cannes à pêche", 5},
    ["chips"] = {"Chips", 2},
    ["ciseaux"] = {"Ciseaux", 2},
    ["donut"] = {"Donut", 2},
    ["water"] = {"Eau", 1},
    ["feuillenori"] = {"Feuille de Nori", 2},
    ["filet"] = {"Filet", 2},
    ["gascan"] = {"Jerrican", 2},
    ["binoculars"] = {"Jumelles", 3},
    ["jus"] = {"Jus de leechi", 1},
    ["mentos"] = {"Mentos", 1},
    ["noddle"] = {"Nouilles", 2},
    ["onigiri"] = {"Onigiri", 20},
    ["parapluie"] = {"Parapluie", 2},
    ["pinces"] = {"Pinces", 2},
    ["chicken"] = {"Poulet", 8},
    ["radio"] = {"Radio", 3},
    ["ramen"] = {"Ramen", 20},
    ["rice"] = {"Riz", 2},
    ["sake"] = {"Sake", 8},
    ["fish12"] = {"Saumon", 20},
    ["cola"] = {"Soda", 2},
    ["sushi"] = {"Sushi", 20},
    ["tapas"] = {"Tapas", 1},
    ["tonkatsu"] = {"Tonkatsu", 20},
    ["makeup"] = {"Trousse de maquillage", 5},
    ["meat"] = {"Viande Crue", 2}, 
    ["menottes"] = {"Menotte", 1},
    ["camera"] = {"Appareil photo", 100},
    ["fabric"] = {"Tissu", 1},
    ["tattoo_ink"] = {"Encre tatouage", 1},
    ["desertmiror"] = {"Désert Pearl's", 2},
    ["desertmiror"] = {"Désert Miror", 2}
  },




 --[[ night = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },
  henhouse = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },
  unicorn = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },
  tequilala = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },]]
  --[[restaurant = {
    --["bread"] = {"Pain", 25},
    ["aperitif"] = {"Apéritif", 5},
    ["entreepearl"] = {"Tartare de thon-rouge", 5},
    ["entreepearl2"] = {"Carpaccio de bar", 5},
    ["platpearl"] = {"Plat Pearl's", 5},
    ["poissontahitienne"] = {"Poisson à la Tahitienne", 20},
    ["boissonpearl"] = {"Boisson Pearl's", 5},
    --["burgerpoisson"] = {"Burger de poisson", 20},
    ["caviar"] = {"Caviar Beluga", 100},
    ["tatakithon"] = {"Tataki de thon", 20},
    --["milk"] = {"Lait", 20},
    ["fish12"] = {"Saumon", 100},
    ["fish6"] = {"Daurade", 20},
    --["whisky"] = {"Bouteille de whisky", 100},
    --["vodka"] = {"Bouteille de vodka", 80},
    --["cognac"] = {"Bouteille de cognac", 100},
    --["rhum"] = {"Bouteille de rhum", 85},
    --["tequila"] = {"Bouteille de tequila", 80},
    --["red_wine"] = {"Bouteille de vin rouge", 70},
    --["high_quality_wine"] = {"Bouteille de grand cru", 100},
    --["white_wine"] = {"Bouteille de vin blanc", 70},
    --["beer"] = {"Bière", 50},
    --["jus_raisin"] = {"Jus de raisin", 40},
    --["champagne"] = {"Bouteille de champage", 200},

  },]]
--[[  ltdsud = {
    ["pinces"] = {"Pinces", 5},
    ["radio"] = {"Radio", 10},
    ["tel"] = {"Téléphone", 10},
    ["parapluie"] = {"Parapluie", 5},
    ["ciseaux"] = {"Ciseaux", 5},
    ["binoculars"] = {"Jumelles", 10},
    ["gascan"] = {"Jerrican", 5},
    ["blocnote"] = {"Blocnote", 5},
    ["makeup"] = {"Trousse de maquillage", 25},
    ["tapas"] = {"Tapas", 3},
    ["cafe"] = {"Cafe", 2},
    ["jus"] = {"Jus de leechi", 3},
    ["mentos"] = {"Mentos", 2},
    ["water"] = {"Eau", 1},
    ["cola"] = {"Soda", 5},
    ["ricemilk"] = {"Lait de riz", 2},
    ["chips"] = {"Chips", 5},
    ["fishingrod"] = {"Cannes à pêche", 25},
    -- ["speaker"] = {"Radio portative", 350},
  },
  ltdnord = {
    ["pinces"] = {"Pinces", 5},
    ["radio"] = {"Radio", 10},
    ["parapluie"] = {"Parapluie", 5},
    ["ciseaux"] = {"Ciseaux", 5},
    ["binoculars"] = {"Jumelles", 10},
    ["gascan"] = {"Jerrican", 5},
    ["blocnote"] = {"Blocnote", 5},
    ["makeup"] = {"Trousse de maquillage", 25},
    ["tapas"] = {"Tapas", 3},
    ["cafe"] = {"Cafe", 2},
    ["jus"] = {"Jus de leechi", 3},
    ["mentos"] = {"Mentos", 2},
    ["water"] = {"Eau", 1},
    ["cola"] = {"Soda", 5},
    --["ricemilk"] = {"Lait de riz", 2},
    ["chips"] = {"Chips", 5},
    ["fishingrod"] = {"Cannes à pêche", 25},
    -- ["speaker"] = {"Radio portative", 350},
  },]]
--[[  yellowjack = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },
  bahamas = {
    ["whisky"] = {"Bouteille de whisky", 100},
    ["vodka"] = {"Bouteille de vodka", 80},
    ["cognac"] = {"Bouteille de cognac", 100},
    ["rhum"] = {"Bouteille de rhum", 85},
    ["tequila"] = {"Bouteille de tequila", 80},
    ["red_wine"] = {"Bouteille de vin rouge", 70},
    ["high_quality_wine"] = {"Bouteille de grand cru", 100},
    ["white_wine"] = {"Bouteille de vin blanc", 70},
    ["beer"] = {"Bière", 50},
    ["jus_raisin"] = {"Jus de raisin", 40},
    ["champagne"] = {"Bouteille de champage", 200},
  },]]
--[[  burgershot = {
    --["milk"] = {"Lait", 30},
    ["chicken"] = {"Poulet", 50},
    --["bread"] = {"Pain", 25},
   -- ["pommeterre"] = {"Pomme de terre", 45},
    ["meat"] = {"Viande Crue", 5},
    --["jus_raisin"] = {"Jus de raisin", 40},
   -- ["cola"] = {"Soda", 5},
    ["donut"] = {"Donut", 5}
  },]]
  --[[osakatsubaki = {
    ["rice"] = {"Riz", 5},
    ["feuillenori"] = {"Feuille de Nori", 5},
    ["bouillon"] = {"Bouillon", 5},
    ["noddle"] = {"Nouilles", 5},
    ["sushi"] = {"Sushi", 50},
    ["tonkatsu"] = {"Tonkatsu", 50},
    ["onigiri"] = {"Onigiri", 50},
    ["ramen"] = {"Ramen", 50},
    ["sake"] = {"Sake", 20},
    ["aperitif"] = {"Apéritif", 5},
    ["filet"] = {"Filet", 5},
    ["fish12"] = {"Saumon", 50},
    ["milk"] = {"Lait", 30},
  },]]
--[[  distillerie = {
    ["pommeterre"] = {"Pomme de terre", 45},
    ["cereale"] = {"Céréale", 45},
  },]]
  -- [""] = {},
  -- [""] = {},
  -- [""] = {},
  -- [""] = {},
}

function Ora.NpcJobs.Wholesaler:GetJobName()
  return "Wholesaler"
end

function Ora.NpcJobs.Wholesaler:Debug(message)
  if (Ora:IsDebug()) then
    Citizen.Trace(string.format("^2[Job %s / %s] ^3%s^7.\n",  Ora.NpcJobs:GetModuleName(), Ora.NpcJobs.Wholesaler:GetJobName(), message))
  end
end

Ora.NpcJobs:Register(Ora.NpcJobs.Wholesaler:GetJobName())
