Citizen.CreateThread(function()
    AddTextEntry("PSCOUT", "Scout 2014 LSPD")
    AddTextEntry("PSCOUTNEW", "Scout 2016 LSPD")
    AddTextEntry("POLICE", "Stanier LSPD")
    AddTextEntry("POLICESLICK", "Stanier Slicktop LSPD")
    AddTextEntry("POLICE2", "Buffalo LSPD")
    AddTextEntry("POLICE3", "Torrence LSPD")
    AddTextEntry("RIOT", "Riot LSPD")
    AddTextEntry("POLICE2N", "Buffalo S LSPD")
    AddTextEntry("POLRAIDEN", "Raiden LSPD")
    AddTextEntry("police3slick", "Torrence Slicktop LSPD")
    AddTextEntry("POLICE3UMK", "Torrence UMK LSPD")
    AddTextEntry("pdumkbuffalo", "Buffalo S UMK LSPD")
end)