Citizen.CreateThread(function()
    --POLICE
    AddTextEntry("lspd1", "CVPI 2011 LSPD")
    AddTextEntry("lspd4", "FPIU 2016 LSPD")
    AddTextEntry("lspd5", "FPIS 2014 LSPD")
    AddTextEntry("lspd6", "FPIS 2014 Slicktop LSPD ")
    AddTextEntry("lspd8", "CVPI 2011 slicktop LSPD")
    AddTextEntry("lspd11", "Dodger Charger 2016 LSPD")
    AddTextEntry("Riot", "Lenco Bearcat")
    AddTextEntry("lspda", "CVPI 2011 Unmarked")
    AddTextEntry("lspdc", "Ford Explorer 2016 SWAT")
    AddTextEntry("lspde", "Ford Explorer 2016 DB")
    AddTextEntry("lspdf", "Ford Taurus 2014 Unmarked")
    AddTextEntry("lspdh", "Dodge Charger 2016 Unmarked")
    AddTextEntry("lspdg", "Dodge Charger 2018 Unmarked")
    AddTextEntry("lspdi", "CVPI 1999 Unmarked")
    AddTextEntry("lspdj", "Chevrolet Tahoe 2018 Unmarked")
    AddTextEntry("lspdk", "Chevrolet Tahoe 2010 Unmarked")
    AddTextEntry("lspdL", "Box ville LSPD ")
    AddTextEntry("policeb", "Harley Davidson LSPD")
    AddTextEntry("policem1", "Vélo LSPD")
    --SAMS
    AddTextEntry("EMSNSPEEDO", "Speedo SAMS")
    AddTextEntry("EMSROAMER", "Roamer SAMS")
    --LSFD
    AddTextEntry("LSFDTRUCK3", "MTL 3 LSFD")
    AddTextEntry("LSFDTRUCK2", "MTL Bateau LSFD")
    AddTextEntry("LSFDTRUCK", "Camion Feu LSFD")
    AddTextEntry("LSFD", "Stanier LSFD")
    AddTextEntry("LSFD2", "Sadler LSFD")
    AddTextEntry("LSFD3", "Ambulance 2 LSFD")
    AddTextEntry("LSFD4", "Ambulance LSFD")
    AddTextEntry("LSFD5", "Bison LSFD")

    --Biker
    AddTextEntry("foxharley2", "Fox Harley")
    AddTextEntry("hvrod", "HV Rod")
    AddTextEntry("na252", "Na 252")
    AddTextEntry("dyna", "Dyna")
    AddTextEntry("dyne", "Dyne")
    AddTextEntry("Softail1", "Softail One")
    AddTextEntry("na25", "Na 25")
    AddTextEntry("lv", "LV Motorcycle")
    AddTextEntry("rk2019", "RK 2019")
    AddTextEntry("softail2", "Softail Two")
    AddTextEntry("indian", "Indian")
    AddTextEntry("acknodlow", "ACK Nodlow")
    AddTextEntry("Scout", "Scout")


    --WEAZEL
    -- AddTextEntry("NEWSVAN", "Rumpo News")
    -- AddTextEntry("NEWSMAV", "Maverick News")
end)