Citizen.CreateThread(function()
    --POLICE
    AddTextEntry("PSCOUT", "Scout 2014 LSPD")
    AddTextEntry("PSCOUTNEW", "Scout 2016 LSPD")
    AddTextEntry("POLICE", "Stanier LSPD")
    AddTextEntry("POLICESLICK", "Stanier Slicktop LSPD")
    AddTextEntry("POLICE2", "Buffalo LSPD")
    AddTextEntry("POLICE3", "Torrence LSPD")
    AddTextEntry("POLICE4", "Stanier UMK LSPD")
    AddTextEntry("POLICE42old", "Buffalo 2009 UMK LSPD")
    AddTextEntry("RIOT", "Riot LSPD")
    AddTextEntry("POLICE2NEW", "Buffalo S LSPD")
    AddTextEntry("POLRAIDEN", "Raiden LSPD")
    AddTextEntry("POLICE3SLICK", "Torrence Slicktop LSPD")
    AddTextEntry("POLICE3UMK", "Torrence UMK LSPD")
    AddTextEntry("PDUMKBUFFALO", "Buffalo S UMK LSPD")
    AddTextEntry("POLEVERON", "Everon LSPD")
    AddTextEntry("POLALAMO", "Alamo LSPD")
    AddTextEntry("UMKSCOUT", "Scout UMK LSPD")
    AddTextEntry("SUPPRESSOR", "Lenco SWAT")
    --SAMS
    AddTextEntry("EMSNSPEEDO", "Speedo SAMS")
    AddTextEntry("EMSROAMER", "Roamer SAMS")
    --LSFD
    AddTextEntry("LSFDTRUCK3", "MTL 3 LSFD")
    AddTextEntry("LSFDTRUCK2", "MTL Bateau LSFD")
    AddTextEntry("LSFDTRUCK", "Camion Feu LSFD")
    AddTextEntry("LSFD", "Stanier LSFD")
    AddTextEntry("LSFD2", "Sadler LSFD")
    AddTextEntry("LSFD3", "Ambulance 2 LSFD")
    AddTextEntry("LSFD4", "Ambulance LSFD")
    AddTextEntry("LSFD5", "Bison LSFD")
    --WEAZEL
    -- AddTextEntry("NEWSVAN", "Rumpo News")
    -- AddTextEntry("NEWSMAV", "Maverick News")
end)