---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 02/09/2019 15:02
---

function CreatorMenuRoleplay(indexCharacter, createPlayer)
    RageUI.DrawContent({ header = true, instructionalButton = true }, function()
        if createPlayer[createPlayer.Model] ~= nil then
            RageUI.Button("Prénom", "Inscrivez votre ~o~prénom.", { RightLabel = createPlayer[createPlayer.Model].Identity.first_name }, true, function(Hovered, Active, Selected)
                if Selected then
                    createPlayer[createPlayer.Model].Identity.first_name = KeyboardInput("~b~Prénom", "", 25)
                end
            end)

            RageUI.Button("Nom", "Inscrivez votre ~o~nom.", { RightLabel = createPlayer[createPlayer.Model].Identity.last_name }, true, function(Hovered, Active, Selected)
                if Selected then
                    createPlayer[createPlayer.Model].Identity.last_name = KeyboardInput("~b~Nom", "", 25)
                end
            end)

            RageUI.Button("Date de naissance", "Inscrivez votre ~o~date de naissance.", { RightLabel = createPlayer[createPlayer.Model].Identity.birth_date }, true, function(Hovered, Active, Selected)
                if Selected then
                    createPlayer[createPlayer.Model].Identity.birth_date = KeyboardInput("~b~Date de naissance", "02/12/1999", 25)
                end
            end)

            RageUI.Button("Origine", "Inscrivez votre ~o~origine.", { RightLabel = createPlayer[createPlayer.Model].Identity.origine }, true, function(Hovered, Active, Selected)
                if Selected then
                    createPlayer[createPlayer.Model].Identity.origine = KeyboardInput("~b~Origine", "", 25)
                end
            end)
        else
            RageUI.Button("Prénom", "Inscrivez votre ~o~prénom.", { RightLabel = createPed.Identity.first_name }, true, function(Hovered, Active, Selected)
                if Selected then
                    createPed.Identity.first_name = KeyboardInput("~b~Prénom", "", 25)
                end
            end)

            RageUI.Button("Nom", "Inscrivez votre ~o~nom.", { RightLabel = createPed.Identity.last_name }, true, function(Hovered, Active, Selected)
                if Selected then
                    createPed.Identity.last_name = KeyboardInput("~b~Nom", "", 25)
                end
            end)

            RageUI.Button("Date de naissance", "Inscrivez votre ~o~date de naissance.", { RightLabel = createPed.Identity.birth_date }, true, function(Hovered, Active, Selected)
                if Selected then
                    createPed.Identity.birth_date = KeyboardInput("~b~Date de naissance", "02/12/1999", 25)
                end
            end)

            RageUI.Button("Origine", "Inscrivez votre ~o~origine.", { RightLabel = createPed.Identity.origine }, true, function(Hovered, Active, Selected)
                if Selected then
                    createPed.Identity.origine = KeyboardInput("~b~Origine", "", 25)
                end
            end)
        end
    end, function()
        ---Panels
    end)
end