---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 02/09/2019 [15] =02
---

local razorCuts = {
    ["mp_m_freemode_01"] = {
        [0] = { collection = 'mpbeach_overlays', overlay = 'FM_Hair_Fuzz' },
        [1] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_001' },
        [2] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_002' },
        [3] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_003' },
        [4] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_004' },
        [5] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_005' },
        [6] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_006' },
        [7] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_007' },
        [8] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_008' },
        [9] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_009' },
        [10] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_013' },
        [11] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_002' },
        [12] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_011' },
        [13] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_012' },
        [14] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_014' },
        [15] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_015' },
        [16] = { collection = 'multiplayer_overlays', overlay = 'NGBea_M_Hair_000' },
        [17] = { collection = 'multiplayer_overlays', overlay = 'NGBea_M_Hair_001' },
        [18] = { collection = 'multiplayer_overlays', overlay = 'NGBus_M_Hair_000' },
        [19] = { collection = 'multiplayer_overlays', overlay = 'NGBus_M_Hair_001' },
        [20] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_000' },
        [21] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
        [22] = { collection = 'multiplayer_overlays', overlay = 'NGInd_M_Hair_000' },
        [24] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_000' },
        [25] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_001' },
        [26] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_002' },
        [27] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_003' },
        [28] = { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_004' },
        [29] = { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_005' },
        [30] = { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_006' },
        [31] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_000_M' },
        [32] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_001_M' },
        [33] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_002_M' },
        [34] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_003_M' },
        [35] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_004_M' },
        [36] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_005_M' },
        [37] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_001' },
        [38] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_002' },
        [39] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_003' },
        [40] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_004' },
        [41] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_005' },
        [42] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_006' },
        [43] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_007' },
        [44] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_008' },
        [45] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_009' },
        [46] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_013' },
        [47] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_002' },
        [48] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_011' },
        [49] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_012' },
        [50] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_014' },
        [51] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_015' },
        [52] = { collection = 'multiplayer_overlays', overlay = 'NGBea_M_Hair_000' },
        [53] = { collection = 'multiplayer_overlays', overlay = 'NGBea_M_Hair_001' },
        [54] = { collection = 'multiplayer_overlays', overlay = 'NGBus_M_Hair_000' },
        [55] = { collection = 'multiplayer_overlays', overlay = 'NGBus_M_Hair_001' },
        [56] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_000' },
        [57] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
        [58] = { collection = 'multiplayer_overlays', overlay = 'NGInd_M_Hair_000' },
        [59] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_000' },
        [60] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_001' },
        [61] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_002' },
        [62] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_003' },
        [63] = { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_004' },
        [64] = { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_005' },
        [65] = { collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_006' },
        [66] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_000_M' },
        [67] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_001_M' },
        [68] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_002_M' },
        [69] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_003_M' },
        [70] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_004_M' },
        [71] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_005_M' },
        [72] = { collection = 'mpgunrunning_overlays', overlay = 'MP_Gunrunning_Hair_M_000_M'},
        [73] = { collection = 'mpgunrunning_overlays', overlay = 'MP_Gunrunning_Hair_M_001_M'}
    },
    ["mp_f_freemode_01"] = {
        [0] = { collection = 'mpbeach_overlays', overlay = 'FM_Hair_Fuzz' },
        [1] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_001' },
        [2] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_002' },
        [3] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_003' },
        [4] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_004' },
        [5] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_005' },
        [6] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_006' },
        [7] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_007' },
        [8] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_008' },
        [9] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_009' },
        [10] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_010' },
        [11] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_011' },
        [12] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_012' },
        [13] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_013' },
        [14] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_014' },
        [15] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_015' },
        [16] = { collection = 'multiplayer_overlays', overlay = 'NGBea_F_Hair_000' },
        [17] = { collection = 'multiplayer_overlays', overlay = 'NGBea_F_Hair_001' },
        [18] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_007' },
        [19] = { collection = 'multiplayer_overlays', overlay = 'NGBus_F_Hair_000' },
        [20] = { collection = 'multiplayer_overlays', overlay = 'NGBus_F_Hair_001' },
        [21] = { collection = 'multiplayer_overlays', overlay = 'NGBea_F_Hair_001' },
        [22] = { collection = 'multiplayer_overlays', overlay = 'NGHip_F_Hair_000' },
        [23] = { collection = 'multiplayer_overlays', overlay = 'NGInd_F_Hair_000' },
        [25] = { collection = 'mplowrider_overlays', overlay = 'LR_F_Hair_000' },
        [26] = { collection = 'mplowrider_overlays', overlay = 'LR_F_Hair_001' },
        [27] = { collection = 'mplowrider_overlays', overlay = 'LR_F_Hair_002' },
        [28] = { collection = 'mplowrider2_overlays', overlay = 'LR_F_Hair_003' },
        [29] = { collection = 'mplowrider2_overlays', overlay = 'LR_F_Hair_003' },
        [30] = { collection = 'mplowrider2_overlays', overlay = 'LR_F_Hair_004' },
        [31] = { collection = 'mplowrider2_overlays', overlay = 'LR_F_Hair_006' },
        [32] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_000_F' },
        [33] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_001_F' },
        [34] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_002_F' },
        [35] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_003_F' },
        [36] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_003' },
        [37] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_006_F' },
        [38] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_004_F' },
        [39] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_001' },
        [40] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_002' },
        [41] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_003' },
        [42] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_004' },
        [43] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_005' },
        [44] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_006' },
        [45] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_007' },
        [46] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_008' },
        [47] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_009' },
        [48] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_010' },
        [49] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_011' },
        [50] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_012' },
        [51] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_013' },
        [52] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_014' },
        [53] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_015' },
        [54] = { collection = 'multiplayer_overlays', overlay = 'NGBea_F_Hair_000' },
        [55] = { collection = 'multiplayer_overlays', overlay = 'NGBea_F_Hair_001' },
        [56] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_007' },
        [57] = { collection = 'multiplayer_overlays', overlay = 'NGBus_F_Hair_000' },
        [58] = { collection = 'multiplayer_overlays', overlay = 'NGBus_F_Hair_001' },
        [59] = { collection = 'multiplayer_overlays', overlay = 'NGBea_F_Hair_001' },
        [60] = { collection = 'multiplayer_overlays', overlay = 'NGHip_F_Hair_000' },
        [61] = { collection = 'multiplayer_overlays', overlay = 'NGInd_F_Hair_000' },
        [62] = { collection = 'mplowrider_overlays', overlay = 'LR_F_Hair_000' },
        [63] = { collection = 'mplowrider_overlays', overlay = 'LR_F_Hair_001' },
        [64] = { collection = 'mplowrider_overlays', overlay = 'LR_F_Hair_002' },
        [65] = { collection = 'mplowrider2_overlays', overlay = 'LR_F_Hair_003' },
        [66] = { collection = 'mplowrider2_overlays', overlay = 'LR_F_Hair_003' },
        [67] = { collection = 'mplowrider2_overlays', overlay = 'LR_F_Hair_004' },
        [68] = { collection = 'mplowrider2_overlays', overlay = 'LR_F_Hair_006' },
        [69] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_000_F' },
        [70] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_001_F' },
        [71] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_002_F' },
        [72] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_003_F' },
        [73] = { collection = 'multiplayer_overlays', overlay = 'NG_F_Hair_003' },
        [74] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_006_F' },
        [75] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_004_F' },
        [76] = { collection = 'mpgunrunning_overlays', overlay = 'MP_Gunrunning_Hair_F_000_F'},
        [77] = { collection = 'mpgunrunning_overlays', overlay = 'MP_Gunrunning_Hair_F_001_F'}
    },
}

local razorCutBoolean = false

local SA = {
    GetLabelText("CC_EYEBRW_0"),
    GetLabelText("CC_EYEBRW_1"),
    GetLabelText("CC_EYEBRW_2"),
    GetLabelText("CC_EYEBRW_3"),
    GetLabelText("CC_EYEBRW_4"),
    GetLabelText("CC_EYEBRW_5"),
    GetLabelText("CC_EYEBRW_6"),
    GetLabelText("CC_EYEBRW_7"),
    GetLabelText("CC_EYEBRW_8"),
    GetLabelText("CC_EYEBRW_9"),
    GetLabelText("CC_EYEBRW_10"),
    GetLabelText("CC_EYEBRW_11"),
    GetLabelText("CC_EYEBRW_12"),
    GetLabelText("CC_EYEBRW_13"),
    GetLabelText("CC_EYEBRW_14"),
    GetLabelText("CC_EYEBRW_15"),
    GetLabelText("CC_EYEBRW_16"),
    GetLabelText("CC_EYEBRW_17"),
    GetLabelText("CC_EYEBRW_18"),
    GetLabelText("CC_EYEBRW_19"),
    GetLabelText("CC_EYEBRW_20"),
    GetLabelText("CC_EYEBRW_21"),
    GetLabelText("CC_EYEBRW_22"),
    GetLabelText("CC_EYEBRW_23"),
    GetLabelText("CC_EYEBRW_24"),
    GetLabelText("CC_EYEBRW_25"),
    GetLabelText("CC_EYEBRW_26"),
    GetLabelText("CC_EYEBRW_27"),
    GetLabelText("CC_EYEBRW_28"),
    GetLabelText("CC_EYEBRW_29"),
    GetLabelText("CC_EYEBRW_30"),
    GetLabelText("CC_EYEBRW_31"),
    GetLabelText("CC_EYEBRW_32"),
    GetLabelText("CC_EYEBRW_33")
}

local rideList = {
    "-",
    "Rides yeux",
    "Rides 1",
    "Rides 2",
    "Rides 3",
    "Rides 4",
    "Rides 5",
    "Rides 6",
    "Rides 7",
    "Rides 8",
    "Rides 9",
    "Rides 10",
    "Rides EX 1",
    "Rides EX 2",
    "Cernes"
}
local tachList = {
    "-",
    "Peu de tâches",
    "Tâches peu visibles",
    "Tâches baladées",
    "Tâches éparpillées",
    "Tâches sauvages",
    "Tâches centrées",
    "Tâches joues",
    "Tâches visage",
    "Infection visage",
    "Infection joues",
    "Rougeur",
    "Rougeur infectée",
    "Rougeurs front",
    "Acnée",
    "Acnée sévère",
    "Acnée baladée",
    "Acnée épaisse",
    "Acnée front",
    "Acnée totale"
}
local eyesList = {
    "Vert",
    "Emmeraude",
    "Bleu",
    "Bleu ciel",
    "Marron clair",
    "Marron",
    "Noisette",
    "Gris sombre",
    "Gris propre",
    "Rose",
    "Jaune",
    "Violet",
    "Blackout",
    "Ombre grise",
    "Soleil tequila",
    "Atomic",
    "Faux",
    "Cola",
    "Ranger",
    "Ying-yang",
    "Bull",
    "Lezard",
    "Dragon",
    "Extra-terrestre",
    "Chèvre",
    "Smiley",
    "Possédé",
    "Démon",
    "Infecté",
    "Alien",
    "Mort",
    "Zombie"
}


local BarbeName = {}
for i = 1, 29, 1 do
    BarbeName[i] = GetLabelText("CC_BEARD_" .. i - 1)
end

local SKClist = {"-"}
for i = 0, 11, 1 do
    table.insert(SKClist, GetLabelText("CC_SKINCOM_" .. i))
end

local MoleList = {"-"}

for i = 0, 18, 1 do
    table.insert(MoleList, GetLabelText("CC_MOLEFRECK_" .. i))
end

local ComplexList = {"-"}
for i = 1, 11, 1 do
    table.insert(ComplexList, GetLabelText("CC_MOLEFRECK_" .. i))
end

local MaquillageList = {"-"}
for i = 1, 71, 1 do
    table.insert(MaquillageList, GetLabelText("CC_MKUP_" .. i))
end

local LipsList = {"-"}
for i = 1, 10, 1 do
    table.insert(LipsList, GetLabelText("CC_LIPSTICK_" .. i))
end

TorsoHairList = {"-"}
for i = 1, GetPedHeadOverlayNum(10), 1 do
    TorsoHairList[i] = i - 1
end

local colorsPanel = {
    haircut = {
        [1] = 1,
        [2] = 1
    },
    barber = {
        [1] = 1,
        [2] = 1
    },
    lipstick = {
        [1] = 1,
        [2] = 1
    },
    makeup = {
        [1] = 1,
        [2] = 1
    }
}

parameters = {
    FACE_HAIR = false,
    FACE_BEARD = false,
    FACE_SKINISSUES = false,
    FACE_OLDNESS = false,
    FACE_TINT = false
}

-- TODO Implemented poile au dos ect..
function CreatorMenuAppearance(indexCharacter, createPlayer)
    --hairstyles = {[1] = -1}
    if Ora.World.Ped:IsPedMale(PlayerPedId()) then
        for i = 1, 25, 1 do
            hairstyles[i] = GetLabelText("CC_M_HS_" .. i - 1) == "NULL" and "Coupe #" .. i or GetLabelText("CC_M_HS_" .. i - 1)
        end
    else
        for i = 1, 25, 1 do
            hairstyles[i] = GetLabelText("CC_F_HS_" .. i - 1) == "NULL" and "Coupe #" .. i or GetLabelText("CC_F_HS_" .. i - 1)
        end
    end
    RageUI.DrawContent(
        {header = true, instructionalButton = true},
        function()
            RageUI.List(
                GetLabelText("FACE_HAIR"),
                hairstyles,
                indexCharacter[createPlayer.Model].Face.hair.style + 1,
                GetLabelText("FACE_APP_H"),
                {},
                true,
                function(Hovered, Active, Selected, Index)
                    if Active then
                        if createPlayer[createPlayer.Model].Face.hair.style ~= Index - 1 then
                            razorDict = razorCuts[createPlayer.Model]
                            if razorDict and razorDict[Index-1] ~= nil and razorCutBoolean then
                                createPlayer[createPlayer.Model].Face.razorCut = {}
                                createPlayer[createPlayer.Model].Face.razorCut.index = 1
                                createPlayer[createPlayer.Model].Face.razorCut.dict = razorDict[Index-1].collection
                                createPlayer[createPlayer.Model].Face.razorCut.hash = razorDict[Index-1].overlay
                            else
                                createPlayer[createPlayer.Model].Face.razorCut = {}
                            end

                            createPlayer[createPlayer.Model].Face.hair.style = Index - 1
                            UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                            indexCharacter[createPlayer.Model].Face.hair.style = Index - 1
                        end
                        if parameters.chestHair then
                            UpdateEntityOutfit(PlayerPedId(), createPlayer[createPlayer.Model].Outfit)
                        end
                        parameters = {}
                        parameters.FACE_HAIR = true
                    else
                        --print("FACE_HAIR")
                        parameters.FACE_HAIR = false
                    end
                end
            )

            RageUI.Checkbox("Dégradé", "Choisissez d'avoir le dégradé associé à cette coupe", razorCutBoolean, {}, function(Hovered, Active, Selected, Checked)
                    if Selected then
                        local Index = createPlayer[createPlayer.Model].Face.hair.style
                        if razorCuts[createPlayer.Model][Index] ~= nil then
                            razorCutBoolean = Checked
                            if Checked then
                                --print(Index)
                                createPlayer[createPlayer.Model].Face.razorCut = {}
                                createPlayer[createPlayer.Model].Face.razorCut.index = 1
                                createPlayer[createPlayer.Model].Face.razorCut.dict = razorCuts[createPlayer.Model][Index].collection
                                createPlayer[createPlayer.Model].Face.razorCut.hash = razorCuts[createPlayer.Model][Index].overlay
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                            else
                                createPlayer[createPlayer.Model].Face.razorCut = nil
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                            end
                        else
                            ShowNotification("Cette coupe n'a pas de dégradé")
                        end
                    end
                end
            )

            RageUI.List("Sourcils",SA,indexCharacter[createPlayer.Model].Face.facial.hair.eyebrow.style + 1, GetLabelText("FACE_APP_H"),{},true,function(Hovered, Active, Selected, Index)
                    if Active then
                        if createPlayer[createPlayer.Model].Face.facial.hair.eyebrow.style ~= Index - 1 then
                            createPlayer[createPlayer.Model].Face.facial.hair.eyebrow.style = Index - 1
                            UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                            indexCharacter[createPlayer.Model].Face.facial.hair.eyebrow.style = Index - 1
                        end
                        parameters = {}
                        parameters.FACE_EYEBROW = true
                    else
                        parameters.FACE_EYEBROW = false
                    end
                end
            )
            if (GetEntityModel(PlayerPedId()) == GetHashKey("mp_m_freemode_01")) then
                RageUI.List("Barbe",BarbeName,indexCharacter[createPlayer.Model].Face.facial.hair.beard.style + 1, GetLabelText("FACE_APP_H"), {},true,function(Hovered, Active, Selected, Index)
                        if Active then
                            if createPlayer[createPlayer.Model].Face.facial.hair.beard.style ~= Index - 1 then
                                createPlayer[createPlayer.Model].Face.facial.hair.beard.style = Index - 1
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                indexCharacter[createPlayer.Model].Face.facial.hair.beard.style = Index - 1
                            end
                            parameters = {}
                            parameters.FACE_BEARD = true
                        else
                            parameters.FACE_BEARD = false
                        end
                    end
                )
            else
                parameters.FACE_BEARD = false
            end
            RageUI.List(GetLabelText("FACE_F_SKINB"),tachList,indexCharacter[createPlayer.Model].Face.blemishes.style + 1, GetLabelText("FACE_APP_H"),{},true,function(Hovered, Active, Selected, Index)
                if Active then
                    if createPlayer[createPlayer.Model].Face.blemishes.style ~= Index - 1 then
                        createPlayer[createPlayer.Model].Face.blemishes.style = Index - 1
                        UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                        indexCharacter[createPlayer.Model].Face.blemishes.style = Index - 1
                    end
                    parameters = {}
                    parameters.FACE_TACH = true
                else
                    parameters.FACE_TACH = false
                end
            end)
            RageUI.List(GetLabelText("FACE_F_SKINA"),rideList,indexCharacter[createPlayer.Model].Face.ageing.style + 1,GetLabelText("FACE_APP_H"),{},true,function(Hovered, Active, Selected, Index)
                if Active then
                    if createPlayer[createPlayer.Model].Face.ageing.style ~= Index - 1 then
                        createPlayer[createPlayer.Model].Face.ageing.style = Index - 1
                        UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                        indexCharacter[createPlayer.Model].Face.ageing.style = Index - 1
                    end
                    parameters = {}

                    parameters.FACE_AGE = true
                else
                    parameters.FACE_AGE = false
                end
            end)
            RageUI.List(GetLabelText("FACE_F_SKC"), SKClist, indexCharacter[createPlayer.Model].Face.skinAspect.style + 1, GetLabelText("FACE_APP_H"), {}, true, function(Hovered, Active, Selected, Index)
                if Active then
                    if createPlayer[createPlayer.Model].Face.skinAspect.style ~= Index - 1 then
                        createPlayer[createPlayer.Model].Face.skinAspect.style = Index - 1
                        UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                        indexCharacter[createPlayer.Model].Face.skinAspect.style = Index - 1
                    end
                    parameters = {}
                    parameters.skin_Aspect = true
                else
                    parameters.skin_Aspect = false
                end
            end)
            RageUI.List(GetLabelText("FACE_F_MOLE"), MoleList,indexCharacter[createPlayer.Model].Face.freckles.style + 1, GetLabelText("FACE_APP_H"), {}, true, function(Hovered, Active, Selected, Index)
                if Active then
                    if createPlayer[createPlayer.Model].Face.freckles.style ~= Index - 1 then
                        createPlayer[createPlayer.Model].Face.freckles.style = Index - 1
                        UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                        indexCharacter[createPlayer.Model].Face.freckles.style = Index - 1
                    end
                    parameters = {}
                    parameters.freckles = true
                else
                    parameters.freckles = false
                end
            end)
            RageUI.List(GetLabelText("FACE_F_SUND"), ComplexList, indexCharacter[createPlayer.Model].Face.complexion.style + 1, GetLabelText("FACE_APP_H"),{},true,function(Hovered, Active, Selected, Index)
                if Active then
                    if createPlayer[createPlayer.Model].Face.complexion.style ~= Index - 1 then
                        createPlayer[createPlayer.Model].Face.complexion.style = Index - 1
                        UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                        indexCharacter[createPlayer.Model].Face.complexion.style = Index - 1
                    end
                    parameters = {}
                    parameters.complexion = true
                else
                    parameters.complexion = false
                end
            end)
            RageUI.List(GetLabelText("FACE_APP_EYE"), eyesList, indexCharacter[createPlayer.Model].Face.eye.style + 1,GetLabelText("FACE_APP_H"), {},true, function(Hovered, Active, Selected, Index)
                if Active then
                    if createPlayer[createPlayer.Model].Face.eye.style ~= Index - 1 then
                        createPlayer[createPlayer.Model].Face.eye.style = Index - 1
                        UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                        indexCharacter[createPlayer.Model].Face.eye.style = Index - 1
                    end
                end
            end)

            RageUI.List(GetLabelText("FACE_F_EYEM"),MaquillageList,indexCharacter[createPlayer.Model].Face.makeup.style + 1, GetLabelText("FACE_APP_H"),{}, true,function(Hovered, Active, Selected, Index)
                if Active then
                    if createPlayer[createPlayer.Model].Face.makeup.style ~= Index - 1 then
                        createPlayer[createPlayer.Model].Face.makeup.style = Index - 1
                        UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                        indexCharacter[createPlayer.Model].Face.makeup.style = Index - 1
                    end
                    parameters = {}
                    parameters.makeup = true
                else
                    parameters.makeup = false
                end
            end)
            if (GetEntityModel(PlayerPedId()) ~= GetHashKey("mp_m_freemode_01")) then
                RageUI.List( GetLabelText("FACE_F_LIPST"),LipsList,indexCharacter[createPlayer.Model].Face.lipstick.style + 1, GetLabelText("FACE_APP_H"), {}, true, function(Hovered, Active, Selected, Index)
                    if Active then
                        if createPlayer[createPlayer.Model].Face.lipstick.style ~= Index - 1 then
                            createPlayer[createPlayer.Model].Face.lipstick.style = Index - 1
                            UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                            indexCharacter[createPlayer.Model].Face.lipstick.style = Index - 1
                        end
                        parameters = {}
                        parameters.lipstick = true
                    else
                        parameters.lipstick = false
                    end
                end)
            end
            RageUI.List("Pilosité du torse", TorsoHairList, indexCharacter[createPlayer.Model].Face.chestHair.style + 1, GetLabelText("FACE_APP_H"), {}, true, function(Hovered, Active, Selected, Index)
                if Active then
                    -- Set ped witout any chest component
                    -- local saveComponents = {

                    -- }

                    if createPlayer.Model == "mp_m_freemode_01" then
                        SetPedComponentVariation(PlayerPedId(), 3, 15, 0, 2)
                        SetPedComponentVariation(PlayerPedId(), 8, 15, 0, 2)
                        SetPedComponentVariation(PlayerPedId(), 10, 0, 0)
                        SetPedComponentVariation(PlayerPedId(), 11, 15, 0, 2)
                    else
                        SetPedComponentVariation(ped, 3, 15, 0)
                        SetPedComponentVariation(ped, 8, 15, 0, 2)
                        SetPedComponentVariation(ped, 10, 0, 0)
                        SetPedComponentVariation(ped, 11, 15, 0, 2)
                    end

                    if createPlayer[createPlayer.Model].Face.chestHair.style ~= Index - 1 then
                        print("chestHair.style changing")
                        createPlayer[createPlayer.Model].Face.chestHair.style = Index - 1
                        UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                        indexCharacter[createPlayer.Model].Face.chestHair.style = Index - 1
                    end
                    parameters = {}
                    parameters.chestHair = true
                else
                    UpdateEntityOutfit(PlayerPedId(), createPlayer[createPlayer.Model].Outfit)
                    parameters.chestHair = false
                end
            end)
        end,
        function()
            --- Panel
            --print(dump(parameters))
            if parameters.FACE_HAIR then
                RageUI.ColourPanel(
                    "Couleur principale",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.haircut[1],
                    indexCharacter[createPlayer.Model].Face.hair.color[1],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.hair.color[1] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.hair.color[1] = CurrentIndex
                                colorsPanel.haircut[1] = MinimumIndex
                                createPlayer[createPlayer.Model].Face.hair.color[1] = CurrentIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                            end
                        end
                    end
                )
                RageUI.ColourPanel(
                    "Couleur secondaire",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.haircut[2],
                    indexCharacter[createPlayer.Model].Face.hair.color[2],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.hair.color[2] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.hair.color[2] = CurrentIndex
                                colorsPanel.haircut[2] = MinimumIndex
                                createPlayer[createPlayer.Model].Face.hair.color[2] = CurrentIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                            end
                        end
                    end
                )
            end
            if parameters.FACE_EYEBROW then
                RageUI.PercentagePanel(
                    indexCharacter[createPlayer.Model].Face.facial.hair.eyebrow.opacity,
                    "Opacité",
                    nil,
                    nil,
                    function(Hovered, Active, Percent)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.facial.hair.eyebrow.opacity ~= Percent then
                                createPlayer[createPlayer.Model].Face.facial.hair.eyebrow.opacity = Percent
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                indexCharacter[createPlayer.Model].Face.facial.hair.eyebrow.opacity = Percent
                            end
                        end
                    end
                )
                RageUI.ColourPanel(
                    "Couleur principale",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.barber[1],
                    indexCharacter[createPlayer.Model].Face.facial.hair.eyebrow.color[1],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.facial.hair.eyebrow.color[1] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.facial.hair.eyebrow.color[1] = CurrentIndex
                                colorsPanel.barber[1] = MinimumIndex
                                createPlayer[createPlayer.Model].Face.facial.hair.eyebrow.color[1] = CurrentIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                            end
                        end
                    end
                )
                RageUI.ColourPanel(
                    "Couleur secondaire",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.barber[2],
                    indexCharacter[createPlayer.Model].Face.facial.hair.eyebrow.color[2],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.facial.hair.eyebrow.color[2] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.facial.hair.eyebrow.color[2] = CurrentIndex
                                colorsPanel.barber[2] = MinimumIndex
                                createPlayer[createPlayer.Model].Face.facial.hair.eyebrow.color[2] = CurrentIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                            end
                        end
                    end
                )
            end
            if parameters.lipstick then
                RageUI.PercentagePanel(
                    indexCharacter[createPlayer.Model].Face.lipstick.opacity,
                    "Opacité",
                    nil,
                    nil,
                    function(Hovered, Active, Percent)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.lipstick.opacity ~= Percent then
                                createPlayer[createPlayer.Model].Face.lipstick.opacity = Percent
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                indexCharacter[createPlayer.Model].Face.lipstick.opacity = Percent
                            end
                        end
                    end
                )
                RageUI.ColourPanel(
                    "Couleur principale",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.lipstick[1],
                    indexCharacter[createPlayer.Model].Face.lipstick.color[1],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.lipstick.color[1] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.lipstick.color[1] = CurrentIndex
                                colorsPanel.lipstick[1] = MinimumIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                createPlayer[createPlayer.Model].Face.lipstick.color[1] = CurrentIndex
                            end
                        end
                    end
                )
                RageUI.ColourPanel(
                    "Couleur secondaire",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.lipstick[2],
                    indexCharacter[createPlayer.Model].Face.lipstick.color[2],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.lipstick.color[2] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.lipstick.color[2] = CurrentIndex
                                colorsPanel.lipstick[2] = MinimumIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                createPlayer[createPlayer.Model].Face.lipstick.color[2] = CurrentIndex
                            end
                        end
                    end
                )
            end
            if parameters.makeup then
                RageUI.PercentagePanel(
                    indexCharacter[createPlayer.Model].Face.makeup.opacity,
                    "Opacité",
                    nil,
                    nil,
                    function(Hovered, Active, Percent)
                        if createPlayer[createPlayer.Model].Face.makeup.opacity ~= Percent then
                            createPlayer[createPlayer.Model].Face.makeup.opacity = Percent
                            UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                            indexCharacter[createPlayer.Model].Face.makeup.opacity = Percent
                        end
                    end
                )
                RageUI.ColourPanel(
                    "Couleur principale",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.makeup[1],
                    indexCharacter[createPlayer.Model].Face.makeup.color[1],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.makeup.color[1] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.makeup.color[1] = CurrentIndex
                                colorsPanel.makeup[1] = MinimumIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                createPlayer[createPlayer.Model].Face.makeup.color[1] = CurrentIndex
                            end
                        end
                    end
                )
                RageUI.ColourPanel(
                    "Couleur secondaire",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.makeup[2],
                    indexCharacter[createPlayer.Model].Face.makeup.color[2],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.makeup.color[2] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.makeup.color[2] = CurrentIndex
                                colorsPanel.makeup[2] = MinimumIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                createPlayer[createPlayer.Model].Face.makeup.color[2] = CurrentIndex
                            end
                        end
                    end
                )
            end
            if parameters.FACE_BEARD then
                RageUI.PercentagePanel(
                    indexCharacter[createPlayer.Model].Face.facial.hair.beard.opacity,
                    "Opacité",
                    nil,
                    nil,
                    function(Hovered, Active, Percent)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.facial.hair.beard.opacity ~= Percent then
                                createPlayer[createPlayer.Model].Face.facial.hair.beard.opacity = Percent
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                indexCharacter[createPlayer.Model].Face.facial.hair.beard.opacity = Percent
                            end
                        end
                    end
                )
                RageUI.ColourPanel(
                    "Couleur principale",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.barber[1],
                    indexCharacter[createPlayer.Model].Face.facial.hair.beard.color[1],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.facial.hair.beard.color[1] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.facial.hair.beard.color[1] = CurrentIndex
                                colorsPanel.barber[1] = MinimumIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                createPlayer[createPlayer.Model].Face.facial.hair.beard.color[1] = CurrentIndex
                            end
                        end
                    end
                )
                RageUI.ColourPanel(
                    "Couleur secondaire",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.barber[2],
                    indexCharacter[createPlayer.Model].Face.facial.hair.beard.color[2],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.facial.hair.beard.color[2] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.facial.hair.beard.color[2] = CurrentIndex
                                colorsPanel.barber[2] = MinimumIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                createPlayer[createPlayer.Model].Face.facial.hair.beard.color[2] = CurrentIndex
                            end
                        end
                    end
                )
            end
            if parameters.FACE_TACH then
                RageUI.PercentagePanel(
                    indexCharacter[createPlayer.Model].Face.blemishes.opacity,
                    "Opacité",
                    nil,
                    nil,
                    function(Hovered, Active, Percent)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.blemishes.opacity ~= Percent then
                                createPlayer[createPlayer.Model].Face.blemishes.opacity = Percent
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                indexCharacter[createPlayer.Model].Face.blemishes.opacity = Percent
                            end
                        end
                    end
                )
            end
            if parameters.FACE_AGE then
                RageUI.PercentagePanel(
                    indexCharacter[createPlayer.Model].Face.ageing.opacity,
                    "Opacité",
                    nil,
                    nil,
                    function(Hovered, Active, Percent)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.ageing.opacity ~= Percent then
                                createPlayer[createPlayer.Model].Face.ageing.opacity = Percent
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                indexCharacter[createPlayer.Model].Face.ageing.opacity = Percent
                            end
                        end
                    end
                )
            end
            if parameters.skin_Aspect then
                RageUI.PercentagePanel(
                    indexCharacter[createPlayer.Model].Face.skinAspect.opacity,
                    "Opacité",
                    nil,
                    nil,
                    function(Hovered, Active, Percent)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.skinAspect.opacity ~= Percent then
                                createPlayer[createPlayer.Model].Face.skinAspect.opacity = Percent
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                indexCharacter[createPlayer.Model].Face.skinAspect.opacity = Percent
                            end
                        end
                    end
                )
            end
            if parameters.freckles then
                RageUI.PercentagePanel(
                    indexCharacter[createPlayer.Model].Face.freckles.opacity,
                    "Opacité",
                    nil,
                    nil,
                    function(Hovered, Active, Percent)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.freckles.opacity ~= Percent then
                                createPlayer[createPlayer.Model].Face.freckles.opacity = Percent
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                indexCharacter[createPlayer.Model].Face.freckles.opacity = Percent
                            end
                        end
                    end
                )
            end
            if parameters.complexion then
                RageUI.PercentagePanel(
                    indexCharacter[createPlayer.Model].Face.complexion.opacity,
                    "Opacité",
                    nil,
                    nil,
                    function(Hovered, Active, Percent)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.complexion.opacity ~= Percent then
                                createPlayer[createPlayer.Model].Face.complexion.opacity = Percent
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                indexCharacter[createPlayer.Model].Face.complexion.opacity = Percent
                            end
                        end
                    end
                )
            end

            if parameters.chestHair then
                RageUI.PercentagePanel(
                    indexCharacter[createPlayer.Model].Face.chestHair.opacity,
                    "Opacité",
                    nil,
                    nil,
                    function(Hovered, Active, Percent)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.chestHair.opacity ~= Percent then
                                createPlayer[createPlayer.Model].Face.chestHair.opacity = Percent
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                indexCharacter[createPlayer.Model].Face.chestHair.opacity = Percent
                            end
                        end
                    end
                )

                RageUI.ColourPanel(
                    "Couleur principale",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.barber[1],
                    indexCharacter[createPlayer.Model].Face.chestHair.color[1],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.chestHair.color[1] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.chestHair.color[1] = CurrentIndex
                                colorsPanel.barber[1] = MinimumIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                createPlayer[createPlayer.Model].Face.chestHair.color[1] = CurrentIndex
                            end
                        end
                    end
                )
                RageUI.ColourPanel(
                    "Couleur secondaire",
                    RageUI.PanelColour.HairCut,
                    colorsPanel.barber[2],
                    indexCharacter[createPlayer.Model].Face.chestHair.color[2],
                    function(Hovered, Active, MinimumIndex, CurrentIndex)
                        if (Active) then
                            if createPlayer[createPlayer.Model].Face.chestHair.color[2] ~= CurrentIndex then
                                indexCharacter[createPlayer.Model].Face.chestHair.color[2] = CurrentIndex
                                colorsPanel.barber[2] = MinimumIndex
                                UpdateEntityFace(PlayerPedId(), createPlayer[createPlayer.Model].Face)
                                createPlayer[createPlayer.Model].Face.chestHair.color[2] = CurrentIndex
                            end
                        end
                    end
                )
            end
        end
    )
end
