---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 02/09/2019 15:02
---
local MenClothes = {
    {
        Name = "Cuir noir",
        Description = " ",
        Selected = false,
        Value = {
            torso = {id = 1, txt = 0},
            undershirt = {id = 2, txt = 2},
            tops = {id = 6, txt = 0},
            legs = {id = 1, txt = 1},
            body_armor = {id = 0, txt = 0},
            backpacks = {id = 0, txt = 0},
            texture = {id = 0, txt = 0},
            feet = {id = 1, txt = 0},
            accessories = {id = 0, txt = 0},
            mask = {toggle = false, id = 0, txt = 0},
            hat = {toggle = false, id = -1, txt = 0},
            glasses = {toggle = false, id = -1, txt = 0},
            ears = {toggle = false, id = -1, txt = 0},
            watches = {toggle = false, id = -1, txt = 0},
            bracelets = {toggle = false, id = -1, txt = 0}
        }
    },
    {
        Name = "Sport blanc",
        Description = " ",
        Selected = false,
        Value = {
            torso = {id = 1, txt = 0},
            undershirt = {id = 0, txt = 2},
            tops = {id = 7, txt = 0},
            legs = {id = 5, txt = 0},
            body_armor = {id = 0, txt = 0},
            backpacks = {id = 0, txt = 0},
            texture = {id = 0, txt = 0},
            feet = {id = 26, txt = 0},
            accessories = {id = 0, txt = 0},
            mask = {toggle = false, id = 0, txt = 0},
            hat = {toggle = false, id = -1, txt = 0},
            glasses = {toggle = false, id = -1, txt = 0},
            ears = {toggle = false, id = -1, txt = 0},
            watches = {toggle = false, id = -1, txt = 0},
            bracelets = {toggle = false, id = -1, txt = 0}
        }
    },
    -- {
    --     Name = "Business man",
    --     Description = " ",
    --     Selected = false,
    --     Value = {
    --         torso = { id = 1, txt = 0 },
    --         undershirt = { id = 31, txt = 0 },
    --         tops = { id = 29, txt = 0 },
    --         legs = { id = 10, txt = 0 },
    --         body_armor = { id = 0, txt = 0 },
    --         backpacks = { id = 0, txt = 0 },
    --         texture = { id = 0, txt = 0 },
    --         feet = { id = 15, txt = 0 },
    --         accessories = { id = 10, txt = 2 },
    --         mask = { toggle = false, id = 0, txt = 0 },
    --         hat = { toggle = false, id = -1, txt = 0 },
    --         glasses = { toggle = false, id = -1, txt = 0 },
    --         ears = { toggle = false, id = -1, txt = 0 },
    --         watches = { toggle = false, id = -1, txt = 0 },
    --         bracelets = { toggle = false, id = -1, txt = 0 },
    --     }
    -- },
    {
        Name = "Cool",
        Description = " ",
        Selected = false,
        Value = {
            torso = {id = 0, txt = 0},
            undershirt = {id = 15, txt = 0},
            tops = {id = 0, txt = 0},
            legs = {id = 6, txt = 1},
            body_armor = {id = 0, txt = 0},
            backpacks = {id = 0, txt = 0},
            texture = {id = 0, txt = 0},
            feet = {id = 12, txt = 4},
            accessories = {id = 0, txt = 0},
            mask = {toggle = false, id = 0, txt = 0},
            hat = {toggle = false, id = -1, txt = 0},
            glasses = {toggle = false, id = -1, txt = 0},
            ears = {toggle = false, id = -1, txt = 0},
            watches = {toggle = false, id = -1, txt = 0},
            bracelets = {toggle = false, id = -1, txt = 0}
        }
    },
    {
        Name = "Junki",
        Description = " ",
        Selected = false,
        Value = {
            torso = {id = 1, txt = 0}, -- Top (lambda)
            undershirt = {id = 1, txt = 1}, -- Shirt (lambda)
            tops = {id = 121, txt = 3}, -- Shirt / Jacket (lambda)
            legs = {id = 5, txt = 2},
            body_armor = {id = 0, txt = 0},
            backpacks = {id = 0, txt = 0},
            texture = {id = 0, txt = 0},
            feet = {id = 5, txt = 0},
            accessories = {id = 0, txt = 2},
            mask = {toggle = false, id = 0, txt = 0},
            hat = {toggle = false, id = -1, txt = 0},
            glasses = {toggle = false, id = -1, txt = 0},
            ears = {toggle = false, id = -1, txt = 0},
            watches = {toggle = false, id = -1, txt = 0},
            bracelets = {toggle = false, id = -1, txt = 0}
        }
    }
}

local FemaleClothes = {
    -- {
    --     Name = "Hiver rude",
    --     Description = " ",
    --     Selected = false,
    --     Value = {
    --         torso = { id = 49, txt = 1 },
    --         undershirt = { id = 2, txt = 0 },
    --         tops = { id = 3, txt = 0 },
    --         legs = { id = 4, txt = 9 },
    --         body_armor = { id = 0, txt = 0 },
    --         backpacks = { id = 0, txt = 0 },
    --         texture = { id = 0, txt = 0 },
    --         feet = { id = 2, txt = 1 },
    --         accessories = { id = 2, txt = 5 },
    --         mask = { toggle = false, id = 0, txt = 0 },
    --         hat = { toggle = true, id = 12, txt = 0 },
    --         glasses = { toggle = true, id = 17, txt = 0 },
    --         ears = { toggle = false, id = -1, txt = 0 },
    --         watches = { toggle = false, id = -1, txt = 0 },
    --         bracelets = { toggle = false, id = -1, txt = 0 },
    --     }
    -- },
    {
        Name = "Junkie",
        Description = " ",
        Selected = false,
        Value = {
            torso = {id = 12, txt = 0},
            undershirt = {id = 15, txt = 0},
            tops = {id = 169, txt = 0},
            legs = {id = 66, txt = 0},
            body_armor = {id = 0, txt = 0},
            backpacks = {id = 0, txt = 0},
            texture = {id = 0, txt = 0},
            feet = {id = 3, txt = 0},
            accessories = {id = 0, txt = 0},
            mask = {toggle = false, id = 0, txt = 0},
            hat = {toggle = true, id = 82, txt = 1},
            glasses = {toggle = false, id = -1, txt = 0},
            ears = {toggle = false, id = -1, txt = 0},
            watches = {toggle = true, id = 17, txt = 0},
            bracelets = {toggle = true, id = 14, txt = 0}
        }
    },
    {
        Name = "BCBG",
        Description = " ",
        Selected = false,
        Value = {
            torso = {id = 12, txt = 0}, -- Mains
            undershirt = {id = 15, txt = 0}, -- Shirt / Accessory
            tops = {id = 37, txt = 1}, -- Shirt Overlay / Jackets
            legs = {id = 24, txt = 0},
            body_armor = {id = 0, txt = 0},
            backpacks = {id = 0, txt = 0},
            texture = {id = 0, txt = 0},
            feet = {id = 42, txt = 1},
            accessories = {id = 0, txt = 0},
            mask = {toggle = false, id = 0, txt = 0},
            hat = {toggle = false, id = -1, txt = 0},
            glasses = {toggle = false, id = 1, txt = 2},
            ears = {toggle = true, id = 7, txt = 0},
            watches = {toggle = true, id = 9, txt = 0},
            bracelets = {toggle = false, id = -1, txt = 0}
        }
    },
    {
        Name = "Robe",
        Description = " ",
        Selected = false,
        Value = {
            torso = {id = 11, txt = 0}, -- Mains
            undershirt = {id = 14, txt = 0}, -- Shirt / Accessory
            tops = {id = 322, txt = 3}, -- Shirt Overlay / Jackets
            legs = {id = 15, txt = 0},
            body_armor = {id = 0, txt = 0},
            backpacks = {id = 0, txt = 0},
            texture = {id = 0, txt = 0},
            feet = {id = 42, txt = 1},
            accessories = {id = 0, txt = 0},
            mask = {toggle = false, id = 0, txt = 0},
            hat = {toggle = false, id = 3, txt = 9},
            glasses = {toggle = false, id = -1, txt = 0},
            ears = {toggle = true, id = 7, txt = 0},
            watches = {toggle = true, id = 4, txt = 0},
            bracelets = {toggle = true, id = 2, txt = 0}
        }
    }
}

local SelectedClothes = {
    mp_m_freemode_01 = {
        Index = 0
    },
    mp_f_freemode_01 = {
        Index = 0
    }
}

local function SelectedClothesWithModel()
    if (GetEntityModel(PlayerPedId()) == GetHashKey("mp_m_freemode_01")) then
        return MenClothes
    else
        return FemaleClothes
    end
end

local function EquipedClothesBadge(Index, Key)
    if (Key == Index) then
        return {RightBadge = RageUI.BadgeStyle.Clothes}
    else
        return {}
    end
end

function CreatorMenuClothes(indexCharacter, createPlayer)
    RageUI.DrawContent(
        {header = true, instructionalButton = true},
        function()
            for k, v in pairs(SelectedClothesWithModel()) do
                RageUI.Button(
                    v.Name,
                    v.Description,
                    EquipedClothesBadge(SelectedClothes[createPlayer.Model].Index, k),
                    true,
                    function(Hovered, Active, Selected)
                        if Selected then
                            SelectedClothes[createPlayer.Model].Index = k
                            local Entity = PlayerPedId()
                            UpdateEntityOutfit(Entity, v.Value)
                            if not (isPlayingAnimSelectedClothes(Entity)) then
                                OnSelectedClothes(v.Value)
                            end
                        end
                    end
                )
            end
        end,
        function()
        end
    )
end

if GetConvar("env_dev", "false") == "true" then
    RegisterCommand("saveOutfit", function()
        -- Get the full outfit of the current player
        local ped = PlayerPedId() 
        local outfit = {
            torso = {id = GetPedDrawableVariation(ped, 3), txt = GetPedTextureVariation(ped, 3)}, -- Mains
            undershirt = {id = GetPedDrawableVariation(ped, 8), txt = GetPedTextureVariation(ped, 8)}, -- Shirt / Accessory
            tops = {id = GetPedDrawableVariation(ped, 11), txt = GetPedTextureVariation(ped, 11)}, -- Shirt Overlay / Jackets
            legs = {id = GetPedDrawableVariation(ped, 4), txt = GetPedTextureVariation(ped, 4)},
            body_armor = {id = GetPedDrawableVariation(ped, 9), txt = GetPedTextureVariation(ped, 9)},
            backpacks = {id = GetPedDrawableVariation(ped, 5), txt = GetPedTextureVariation(ped, 5)},
            texture = {id = GetPedDrawableVariation(ped, 10), txt = GetPedTextureVariation(ped, 10)},
            feet = {id = GetPedDrawableVariation(ped, 6), txt = GetPedTextureVariation(ped, 6)},
            accessories = {id = GetPedDrawableVariation(ped, 7), txt = GetPedTextureVariation(ped, 7)},
            mask = {toggle = false, id = 0, txt = 0},
            hat = {toggle = true, id = GetPedPropIndex(ped, 0), txt = GetPedPropTextureIndex(ped, 0)},
            glasses = {toggle = true, id = GetPedPropIndex(ped, 1), txt = GetPedPropTextureIndex(ped, 1)},
            ears = {toggle = true, id = GetPedPropIndex(ped, 2), txt = GetPedPropTextureIndex(ped, 2)},
            watches = {toggle = true, id = GetPedPropIndex(ped, 6), txt = GetPedPropTextureIndex(ped, 6)},
            bracelets = {toggle = true, id = GetPedPropIndex(ped, 7), txt = GetPedPropTextureIndex(ped, 7)}
        }

        for k, v in pairs(outfit) do
            if (v.toggle ~= nil) then
                v.toggle = v.id ~= -1 and true or false
            end
        end

        print("Outfit : ["..tostring(args).."]", json.encode(outfit))
    end)
end