RegisterServerEvent('fireworks')
AddEventHandler('fireworks', function()
    TriggerClientEvent('frobski-fireworks:start', source)
    TriggerClientEvent('frobski-fireworks:start2', source)
    TriggerClientEvent('frobski-fireworks:start3', source)
    TriggerClientEvent('frobski-fireworks:start4', source)
    TriggerClientEvent('frobski-fireworks:start9', source)
    TriggerClientEvent('frobski-fireworks:start10', source)
    TriggerClientEvent('frobski-fireworks:start11', source)
end)

RegisterServerEvent('fireworks2')
AddEventHandler('fireworks2', function()
    TriggerClientEvent('frobski-fireworks:start5', source)
    TriggerClientEvent('frobski-fireworks:start6', source)
    TriggerClientEvent('frobski-fireworks:start7', source)
    TriggerClientEvent('frobski-fireworks:start8', source)
end)

RegisterServerEvent('fireworks3')
AddEventHandler('fireworks3', function()
    TriggerClientEvent('frobski-fireworks:start', source)
    TriggerClientEvent('frobski-fireworks:start2', source)
    TriggerClientEvent('frobski-fireworks:start3', source)
    TriggerClientEvent('frobski-fireworks:start4', source)
    TriggerClientEvent('frobski-fireworks:start5', source)
    TriggerClientEvent('frobski-fireworks:start6', source)
    TriggerClientEvent('frobski-fireworks:start7', source)
    TriggerClientEvent('frobski-fireworks:start8', source)
    TriggerClientEvent('frobski-fireworks:start9', source)
    TriggerClientEvent('frobski-fireworks:start10', source)
    TriggerClientEvent('frobski-fireworks:start11', source)
end)
