---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 28/08/2019 22:31
---
local Player = {
    Handcuff = false
}

Player.Vehicle = 0
Player.Ped = 0
Player.ActivePlayer = GetActivePlayers()
Player.Health = 0
Player.Identity = {}
Player.Pos = vector3(0.0,0.0,0.0)
Player.Heading = 0.0
Player.Health = 200
Player.Armor = 0
Player.Shooting = false
Player.InteriorID = false
Player.InVehicle = false

Player.Model = 0
Player.Face = {}
Player.Outfit = {}
Player.Tattoo = {}
Player.Weapon = {}
Player.FarmLimit = 0
Player.Strength = 0
Player.Uuid = nil
Player.Inventory = {["Vide"] = {}}

Player.InCombat = false
Player.Ragdoll = false
Player.isDead = false
Player.isLoaded = false
Player.isBusy = true
Player.isCinematic = false

Player.Position = {}
Player.ZoneName = nil
Player.Hud = true -- read-only property, to change HUD use exports["Atlantiss_utils"]:SetPlayerHUD(true or false)
Player.InteriorID = 0
Player.Armed = false
Player.Shooting = false
Player.MeleeCombat = false
Player.Cuffed = false
Player.isInWater = false
Player.isDiving = false
Player.Running = false

---GetMatrix
---@param Callback function
---@return table
---@public
function Player:GetMatrix(Callback)
    Callback(GetEntityMatrix(self.Ped))
    return GetEntityMatrix(self.Ped)
end

---GetVehicle
---@return number
---@public
function Player:GetVehicle()
    local vehicle = self.InVehicle and GetVehiclePedIsUsing(self.Ped)
    return vehicle and vehicle > 0 and vehicle
end

---Set
---@param Value string
---@param Arg string
---@return void
---@public
function Player:Set(Value, Arg)
    self[Value] = Arg
end

---GetPlayer
---@return table
function LocalPlayer()
    return Player
end

Player.UpdateHud = function()
    if Player.isCinematic or not Player.Hud then
        TriggerEvent("es:setMoneyDisplay", 0.0)
    else
        TriggerEvent("es:setMoneyDisplay", 0.8)
    end
end

Citizen.CreateThread(function()
	Player.ID = PlayerId()
	Player.ServerID = GetPlayerServerId(Player.ID)

	while true do
		Player.Pos = GetEntityCoords(Player.Ped)
		Player.Heading = GetEntityHeading(Player.Ped)
		Player.InVehicle = IsPedInAnyVehicle(Player.Ped)
		Citizen.Wait(0)
	end
end)

Citizen.CreateThread(
    function()
        while true do
            Player.Ped = PlayerPedId()
            Player.Pos = GetEntityCoords(Player.Ped)
            Player.Hud = exports["Atlantiss_utils"]:GetPlayerHUD()
            SetPedSuffersCriticalHits(Player.Ped, false)

            if (IsPedFalling(Player.Ped) or IsPedInParachuteFreeFall(Player.Ped)) then
                if (Atlantiss.Inventory:GetItemCount("parachute") > 0) then
                    GiveWeaponToPed(Player.Ped, GetHashKey("GADGET_PARACHUTE"), true)
                    SetCurrentPedWeapon(Player.Ped, GetHashKey("GADGET_PARACHUTE"), true)
                    SetPlayerHasReserveParachute(PlayerId())
                    SetPlayerParachutePackTintIndex(PlayerId(), math.random(1, 4))
                    SetPlayerParachuteTintIndex(PlayerId(), math.random(0, 13))
                    SetPlayerReserveParachuteTintIndex(PlayerId(), math.random(0, 13))
                    SetAutoGiveParachuteWhenEnterPlane(PlayerId(), true)
                    SetPedGadget(Player.Ped, "GADGET_PARACHUTE", true)
                end
            end

            Citizen.Wait(1000)
        end
    end
)

Citizen.CreateThread(
    function()
        for i = 1, 500, 1 do
            Wait(10)
            FreezePlayer(PlayerId(), false)
        end
        --print("end")
        while true do
            Citizen.Wait(1)
            --FreezePlayer(PlayerId(),false)
            if Player.Ragdoll then
                SetPedToRagdoll(Player.Ped, 1000, 1000, 0, 0, 0, 0)
                if not Player.KO and not Player.isDead then
                    SetTextComponentFormat("STRING")
                    AddTextComponentString("Appuyez sur ~INPUT_CONTEXT~ pour vous relever")
                    DisplayHelpTextFromStringLabel(0, 0, 1, -1)
                    if IsControlJustPressed(0, Keys["E"]) then
                        Player.Ragdoll = not Player.Ragdoll
                    end
                end
            end
        end
    end
)

function SetFarmLimit(f)
    if f == nil then
        f = 0
    end
    if Player.FarmLimit == nil then
        Player.FarmLimit = 0
    end
    Player.FarmLimit = Player.FarmLimit + f
end

function GetFarmLimit()
    if Player.FarmLimit == nil then
        Player.FarmLimit = 0
    end
    return Player.FarmLimit
end

function SetPlayerInventoryPrefix(inventoryPrefix)
    Player.InventoryPrefix = inventoryPrefix
end
