---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 01/09/2019 02:07
---

RegisterNetEvent("mugroom:Finish")

Creator = {}

local _Cam

function RegenCreatorCam()
    _Cam = CamCreatorInit()
end

function GetCreatorCam()
    return _Cam
end

function Creator.LoadContent()
    SetOverrideWeather("EXTRASUNNY")
    SetWeatherTypePersist("EXTRASUNNY")

    RegenCreatorCam()
    CreatorRequestAssets()
    Citizen.Wait(1000)
    DoScreenFadeIn(500)
    if isPed == false and sexIndex == 1 and GetEntityModel(PlayerPedId()) ~= GetHashKey("mp_f_freemode_01") then
        UpdatePlayerPedFreemodeCharacter(
            PlayerPedId(),
            "mp_f_freemode_01",
            createPlayer[createPlayer.Model].Face,
            createPlayer[createPlayer.Model].Outfit,
            createPlayer[createPlayer.Model].Tattoo
        )
    elseif isPed == false and sexIndex == 2 and GetEntityModel(PlayerPedId()) ~= GetHashKey("mp_m_freemode_01") then
        UpdatePlayerPedFreemodeCharacter(
            PlayerPedId(),
            "mp_m_freemode_01",
            createPlayer[createPlayer.Model].Face,
            createPlayer[createPlayer.Model].Outfit,
            createPlayer[createPlayer.Model].Tattoo
        )
    else
        Cped = true
    end
    while not IsScreenFadedIn() do
        Citizen.Wait(10)
    end
    RemoveLoadingPrompt()
    Ora.Health:Revive(false)
    Ora.Health:SetMyHealthPercent(100)
    Stage_01(_Cam)
    Stage_01_A(_Cam)
    RenderScriptCams(true, false, 3000, 1, 0, 0)
    WalkToRoom()
    Citizen.Wait(5000)
    OpenCreatorMenu()
    onCreatorTick.Tick = true
end

AddEventHandler(
    "mugroom:Finish",
    function(SpawnLocation)
        Citizen.Wait(500)

        CreatorDeleteAssets()
        if (SpawnLocation.index == 1) then
            LOSSANTOS()
        elseif (SpawnLocation.index == 2) then
            DESERT()
        elseif (SpawnLocation.index == 3) then
            CENTREVILLE()
        end

        TriggerServerCallback(
            "spawned:requestData",
            function(ActiveCharacter, ActionID, Table, Identity, Jobs, Users)
                TriggerEvent("es:activateMoney", Users[1].money)
                --TriggerEvent("es:activateBlackMoney", Users[1].black_money)
                player_group = Users[1].group
                SetMyIdentity(Identity)
                setOldF(Users[1].limit_farm)
                PlyUuid = Users[1].uuid
                Ora.Player.HasLoaded = true
                SetFarmLimit(Users[1].limit_farm)
                SetPlayerInventoryPrefix(Users[1].id)
                LocalPlayer().InventoryPrefix = Users[1].id
                Ora.Identity.Job:Set(Jobs[1].name, Jobs[1].rank)
                Ora.Identity.Orga:Set(Jobs[1].orga, Jobs[1].orga_rank)
                XNL_SetInitialXPLevels(tonumber(Users[1].xp))
                StartEverything()
                if (ifModuleLoaded("Player")) then
                    Ora.Player:SetEntityInvicible(PlayerId(), PlayerPedId(), false)
                end
            end
        )
    end
)

function UpdateCreatorTick(type, value)
    onCreatorTick[type] = value
end

local isTurnedLeft = false
local isTurnedRight = false

AddEventHandler(
    "onResourceStop",
    function(resourceName)
        if (GetCurrentResourceName() ~= resourceName) then
            return
        end
        CreatorDeleteAssets()
    end
)

local lightTurnedOff = true
Citizen.CreateThread(
    function()
        while true do
            Citizen.Wait(1)
            if (onCreatorTick.FaceTurnEnabled) then
                --print("AA")
                if IsControlJustReleased(2, 205) or IsDisabledControlJustReleased(1, 205) then
                    -- run code here
                    if not (isTurnedLeft) then
                        func_1513(PlayerPedId(), false)
                        isTurnedLeft = true
                    else
                        func_1514(PlayerPedId(), true)
                        isTurnedLeft = false
                    end
                end
                if IsControlJustReleased(1, 206) or IsDisabledControlJustReleased(1, 206) then
                    if not (isTurnedRight) then
                        func_1514(PlayerPedId(), false)
                        isTurnedRight = true
                    else
                        func_1513(PlayerPedId(), true)
                        isTurnedRight = false
                    end
                end
            end
            if (onCreatorTick.LightRemote) then
            end
            if (onCreatorTick.Scaleform) then
                OnRenderCreatorScaleform()
            end
        end
    end
)
