Ora.Anticheat = {}
Ora.Anticheat.GroupsWhitelist = {
  ["superadmin"] = true,
  ["animator"] = true,
  ["user"] = false,
}

Ora.Anticheat.Alert = {
  HEALTH_ALERT = false,
  BLIPS = true
}

Ora.Anticheat.ObjectWhitelist = {
  [GetHashKey("prop_juicestand")] = true,
  [GetHashKey("p_parachute1_sp_dec")] = true,
  [GetHashKey("prop_v_parachute")] = true,
  [GetHashKey("p_parachute1_s")] = true,
  [GetHashKey("p_parachute1_mp_dec")] = true,
  [GetHashKey("p_parachute_s")] = true,
  [GetHashKey("p_parachute1_sp_s")] = true,
  [GetHashKey("p_parachute1_mp_s")] = true,
  [GetHashKey("xm_prop_x17_tool_draw_01a")] = true,
  [GetHashKey("prop_tennis_rack_01b")] = true,
  [GetHashKey("prop_golf_ball")] = true,
  [GetHashKey("prop_golf_ball_p2")] = true,
  [GetHashKey("prop_golf_ball_p3")] = true,
  [GetHashKey("prop_golf_ball_p4")] = true,
  [GetHashKey("prop_golf_putter_01")] = true,
  [GetHashKey("prop_golf_iron_01")] = true,
  [GetHashKey("prop_golf_wood_01")] = true,
  [-1124612472] = true,
  [974883178] = true,
  [1511282135] = true,
  [-303457828] = true,
  [-901038522] = true,
  [1463746489] = true,
  [977923025] = true,
  [1760825203] = true,
  [746336278] = true,
  [1808635348] = true,
  [-1539862408] = true,
  [-2098426548] = true,
  [-1964402432] = true,
  [155046858] = true,
  [-472443277] = true,
  [1053267296] = true,
  [-1910604593] = true,
  [-1036807324] = true,
  [-1533900808] = true,
  [-154609122] = true,
  [1184113278] = true, -- poolcue
  [1729911864] = true, -- speaker
  [1262298127] = true, -- wheelchair
  [GetHashKey("bv_shield1")] = true,
  [GetHashKey("bv_shield2")] = true,
  [GetHashKey("bv_shield3")] = true,
  [GetHashKey("bv_shield4")] = true,
  [GetHashKey("prop_shield_one")] = true,
  [GetHashKey("prop_shield_two")] = true,
  [GetHashKey("prop_shield_three")] = true,
  [GetHashKey("prop_shield_four")] = true,
}

Ora.Anticheat.WeaponBlacklist = {
  [GetHashKey("WEAPON_PISTOL_MK2")] = "WEAPON_PISTOL_MK2",
  [GetHashKey("WEAPON_APPISTOL")] = "WEAPON_APPISTOL",
  [GetHashKey("WEAPON_FLAREGUN")] = "WEAPON_FLAREGUN",
  [GetHashKey("WEAPON_MARKSMANPISTOL")] = "WEAPON_MARKSMANPISTOL",
  [GetHashKey("WEAPON_SMG_MK2")] = "WEAPON_SMG_MK2",
  [GetHashKey("WEAPON_ASSAULTSMG")] = "WEAPON_ASSAULTSMG",
  [GetHashKey("WEAPON_MG")] = "WEAPON_MG",
  [GetHashKey("WEAPON_COMBATMG")] = "WEAPON_COMBATMG",
  [GetHashKey("WEAPON_COMBATMG_MK2")] = "WEAPON_COMBATMG_MK2",
  [GetHashKey("WEAPON_COMBATPDW")] = "WEAPON_COMBATPDW",
  [GetHashKey("WEAPON_GUSENBERG")] = "WEAPON_GUSENBERG",
  [GetHashKey("WEAPON_ASSAULTRIFLE_MK2")] = "WEAPON_ASSAULTRIFLE_MK2",
  [GetHashKey("WEAPON_CARBINERIFLE_MK2")] = "WEAPON_CARBINERIFLE_MK2",
  [GetHashKey("WEAPON_ADVANCEDRIFLE")] = "WEAPON_ADVANCEDRIFLE",
  [GetHashKey("WEAPON_SPECIALCARBINE")] = "WEAPON_SPECIALCARBINE",
  [GetHashKey("WEAPON_BULLPUPRIFLE")] = "WEAPON_BULLPUPRIFLE",
  [GetHashKey("WEAPON_COMPACTRIFLE")] = "WEAPON_COMPACTRIFLE",
  [GetHashKey("WEAPON_SWEEPERSHOTGUN")] = "WEAPON_SWEEPERSHOTGUN",
  [GetHashKey("WEAPON_ASSAULTSHOTGUN")] = "WEAPON_ASSAULTSHOTGUN",
  [GetHashKey("WEAPON_HEAVYSHOTGUN")] = "WEAPON_HEAVYSHOTGUN",
  [GetHashKey("WEAPON_HEAVYSNIPER_MK2")] = "WEAPON_HEAVYSNIPER_MK2",
  [GetHashKey("WEAPON_MARKSMANRIFLE")] = "WEAPON_MARKSMANRIFLE",
  [GetHashKey("WEAPON_RPG")] = "WEAPON_RPG",
  [GetHashKey("WEAPON_MINIGUN")] = "WEAPON_MINIGUN",
  [GetHashKey("WEAPON_FIREWORK")] = "WEAPON_FIREWORK",
  [GetHashKey("WEAPON_RAILGUN")] = "WEAPON_RAILGUN",
  [GetHashKey("WEAPON_HOMINGLAUNCHER")] = "WEAPON_HOMINGLAUNCHER",
  [GetHashKey("WEAPON_GRENADE")] = "WEAPON_GRENADE",
  [GetHashKey("WEAPON_STICKYBOMB")] = "WEAPON_STICKYBOMB",
  [GetHashKey("WEAPON_COMPACTLAUNCHER")] = "WEAPON_COMPACTLAUNCHER",
  [GetHashKey("WEAPON_SNSPISTOL_MK2")] = "WEAPON_SNSPISTOL_MK2",
  [GetHashKey("WEAPON_REVOLVER_MK2")] = "WEAPON_REVOLVER_MK2",
  [GetHashKey("WEAPON_DOUBLEACTION")] = "WEAPON_DOUBLEACTION",
  [GetHashKey("WEAPON_SPECIALCARBINE_MK2")] = "WEAPON_SPECIALCARBINE_MK2",
  [GetHashKey("WEAPON_BULLPUPRIFLE_MK2")] = "WEAPON_BULLPUPRIFLE_MK2",
  [GetHashKey("WEAPON_PUMPSHOTGUN_MK2")] = "WEAPON_PUMPSHOTGUN_MK2",
  [GetHashKey("WEAPON_MARKSMANRIFLE_MK2")] = "WEAPON_MARKSMANRIFLE_MK2",
  [GetHashKey("WEAPON_RAYPISTOL")] = "WEAPON_RAYPISTOL",
  [GetHashKey("WEAPON_RAYCARBINE")] = "WEAPON_RAYCARBINE",
  [GetHashKey("WEAPON_RAYMINIGUN")] = "WEAPON_RAYMINIGUN",
  [GetHashKey("WEAPON_NAVYREVOLVER")] = "WEAPON_NAVYREVOLVER",
  [GetHashKey("WEAPON_CERAMICPISTOL")] = "WEAPON_CERAMICPISTOL"
}

function Ora.Anticheat:IsAnticheatWhitelist()
  local myGroup = Ora.Identity:GetMyGroup()
  if (self.GroupsWhitelist[myGroup] ~= nil) then
    return self.GroupsWhitelist[myGroup]
  end

  return false
end

function Ora.Anticheat:GetModuleName()
  return "Anticheat"
end

function Ora.Anticheat:Debug(message)
  if (Ora:IsDebug()) then
    Citizen.Trace(string.format("^2[%s / %s] ^3%s^7.\n",  Ora:GetServerName(), Ora.Anticheat:GetModuleName(), message))
  end
end

Ora.Modules:Register(Ora.Anticheat:GetModuleName())


Ora.Anticheat.DisabledExplosion = {7, 9, 31}

Ora.Anticheat.ServerSideDisabledVehicles = {
  LIST = {},
  HAS_BEEN_POPULATED = false
}

Ora.Anticheat.NoRandomSpawnVehicle = {
    GetHashKey("SHAMAL"), -- They spawn on LSIA and try to take off
    GetHashKey("LUXOR"), -- They spawn on LSIA and try to take off
    GetHashKey("LUXOR2"), -- They spawn on LSIA and try to take off
    GetHashKey("JET"), -- They spawn on LSIA and try to take off and land, remove this if you still want em in the skies
    GetHashKey("LAZER"), -- They spawn on Zancudo and try to take off
    GetHashKey("TITAN"), -- They spawn on Zancudo and try to take off
    GetHashKey("BARRACKS"), -- Regularily driving around the Zancudo airport surface
    GetHashKey("BARRACKS2"), -- Regularily driving around the Zancudo airport surface
    GetHashKey("CRUSADER"), -- Regularily driving around the Zancudo airport surface
    GetHashKey("RHINO"), -- Regularily driving around the Zancudo airport surface
    GetHashKey("AIRTUG"), -- Regularily spawns on the LSsIA airport surface
    GetHashKey("RIPLEY"), -- Regularily spawns on the LSIA airport surface
    GetHashKey("PHANTOM"),
    GetHashKey("HAULER"),
    GetHashKey("RUBBLE"),
    GetHashKey("POLMAV"),
    GetHashKey("BIFF"),
    GetHashKey("TACO"),
    GetHashKey("PACKER"),
    GetHashKey("TRAILERS"),
    GetHashKey("TRAILERS2"),
    GetHashKey("TRAILERS3"),
    GetHashKey("TRAILERS4"),
    GetHashKey("CERBERUS3"),
    GetHashKey("CERBERUS2"),
    GetHashKey("CERBERUS"),
    GetHashKey("BLIMP"),
    GetHashKey("BLIMP2"),
    GetHashKey("BLIMP3"),
    GetHashKey("MOGUL"),
    GetHashKey("CUBAN800"),
    GetHashKey("MICROLIGHT"),
    GetHashKey("DUSTER"),
    GetHashKey("AKULA"),
    GetHashKey("ANNIHILATOR"),
    GetHashKey("BUZZARD"),
    GetHashKey("BUZZARD2"),
    GetHashKey("CARGOBOB"),
    GetHashKey("CARGOBOB2"),
    GetHashKey("CARGOBOB3"),
    GetHashKey("CARGOBOB4"),
    GetHashKey("FROGGER"),
    GetHashKey("FROGGER2"),
    GetHashKey("HAVOK"),
    GetHashKey("HUNTER"),
    GetHashKey("MAVERICK"),
    GetHashKey("SAVAGE"),
    GetHashKey("SEASPARROW"),
    GetHashKey("SKYLIFT"),
    GetHashKey("SUPERVOLITO"),
    GetHashKey("SUPERVOLITO2"),
    GetHashKey("SWIFT"),
    GetHashKey("SWIFT2"),
    GetHashKey("VALKYRIE"),
    GetHashKey("VOLATUS"),
    GetHashKey("VALKYRIE2"),
    GetHashKey("ALPHAZ1"),
    GetHashKey("AVENGER"),
    GetHashKey("AVENGER2"),
    GetHashKey("BESRA"),
    GetHashKey("BOMBUSHKA"),
    GetHashKey("CARGOPLANE"),
    GetHashKey("CUBAN800"),
    GetHashKey("DODO"),
    GetHashKey("DUSTER"),
    GetHashKey("HYDRA"),
    GetHashKey("JET"),
    GetHashKey("MAMMATUS"),
    GetHashKey("MICROLIGHT"),
    GetHashKey("MILJET"),
    GetHashKey("MOGUL"),
    GetHashKey("MOLOTOK"),
    GetHashKey("NIMBUS"),
    GetHashKey("NOKOTA"),
    GetHashKey("PYRO"),
    GetHashKey("ROGUE"),
    GetHashKey("SEABREEZE"),
    GetHashKey("SHAMAL"),
    GetHashKey("STARLING"),
    GetHashKey("STRIKEFORCE"),
    GetHashKey("STUNT"),
    GetHashKey("TITAN"),
    GetHashKey("TULA"),
    GetHashKey("VELUM"),
    GetHashKey("VELUM2"),
    GetHashKey("VESTRA"),
    GetHashKey("DUMP")
}


Ora.Anticheat.HashToName = {
  [GetHashKey("dinghy")] = "dinghy",
  [GetHashKey("dinghy2")] = "dinghy2",
  [GetHashKey("dinghy3")] = "dinghy3",
  [GetHashKey("dinghy4")] = "dinghy4",
  [GetHashKey("jetmax")] = "jetmax",
  [GetHashKey("marquis")] = "marquis",
  [GetHashKey("seashark")] = "seashark",
  [GetHashKey("seashark2")] = "seashark2",
  [GetHashKey("seashark3")] = "seashark3",
  [GetHashKey("speeder")] = "speeder",
  [GetHashKey("speeder2")] = "speeder2",
  [GetHashKey("squalo")] = "squalo",
  [GetHashKey("submersible")] = "submersible",
  [GetHashKey("submersible2")] = "submersible2",
  [GetHashKey("suntrap")] = "suntrap",
  [GetHashKey("toro")] = "toro",
  [GetHashKey("toro2")] = "toro2",
  [GetHashKey("tropic")] = "tropic",
  [GetHashKey("tropic2")] = "tropic2",
  [GetHashKey("tug")] = "tug",
  [GetHashKey("avisa")] = "avisa",
  [GetHashKey("dinghy5")] = "dinghy5",
  [GetHashKey("kosatka")] = "kosatka",
  [GetHashKey("longfin")] = "longfin",
  [GetHashKey("patrolboat")] = "patrolboat",
  [GetHashKey("benson")] = "benson",
  [GetHashKey("biff")] = "biff",
  [GetHashKey("cerberus")] = "cerberus",
  [GetHashKey("cerberus2")] = "cerberus2",
  [GetHashKey("cerberus3")] = "cerberus3",
  [GetHashKey("hauler")] = "hauler",
  [GetHashKey("hauler2")] = "hauler2",
  [GetHashKey("mule")] = "mule",
  [GetHashKey("mule2")] = "mule2",
  [GetHashKey("mule3")] = "mule3",
  [GetHashKey("mule4")] = "mule4",
  [GetHashKey("packer")] = "packer",
  [GetHashKey("phantom")] = "phantom",
  [GetHashKey("phantom2")] = "phantom2",
  [GetHashKey("phantom3")] = "phantom3",
  [GetHashKey("pounder")] = "pounder",
  [GetHashKey("pounder2")] = "pounder2",
  [GetHashKey("stockade")] = "stockade",
  [GetHashKey("stockade3")] = "stockade3",
  [GetHashKey("terbyte")] = "terbyte",
  [GetHashKey("asbo")] = "asbo",
  [GetHashKey("blista")] = "blista",
  [GetHashKey("brioso")] = "brioso",
  [GetHashKey("club")] = "club",
  [GetHashKey("dilettante")] = "dilettante",
  [GetHashKey("dilettante2")] = "dilettante2",
  [GetHashKey("kanjo")] = "kanjo",
  [GetHashKey("issi2")] = "issi2",
  [GetHashKey("issi3")] = "issi3",
  [GetHashKey("issi4")] = "issi4",
  [GetHashKey("issi5")] = "issi5",
  [GetHashKey("issi6")] = "issi6",
  [GetHashKey("panto")] = "panto",
  [GetHashKey("prairie")] = "prairie",
  [GetHashKey("rhapsody")] = "rhapsody",
  [GetHashKey("brioso2")] = "brioso2",
  [GetHashKey("weevil")] = "weevil",
  [GetHashKey("cogcabrio")] = "cogcabrio",
  [GetHashKey("exemplar")] = "exemplar",
  [GetHashKey("f620")] = "f620",
  [GetHashKey("felon")] = "felon",
  [GetHashKey("felon2")] = "felon2",
  [GetHashKey("jackal")] = "jackal",
  [GetHashKey("oracle")] = "oracle",
  [GetHashKey("oracle2")] = "oracle2",
  [GetHashKey("sentinel")] = "sentinel",
  [GetHashKey("sentinel2")] = "sentinel2",
  [GetHashKey("windsor")] = "windsor",
  [GetHashKey("windsor2")] = "windsor2",
  [GetHashKey("zion")] = "zion",
  [GetHashKey("zion2")] = "zion2",
  [GetHashKey("bmx")] = "bmx",
  [GetHashKey("cruiser")] = "cruiser",
  [GetHashKey("fixter")] = "fixter",
  [GetHashKey("scorcher")] = "scorcher",
  [GetHashKey("tribike")] = "tribike",
  [GetHashKey("tribike2")] = "tribike2",
  [GetHashKey("tribike3")] = "tribike3",
  [GetHashKey("ambulance")] = "ambulance",
  [GetHashKey("fbi")] = "fbi",
  [GetHashKey("fbi2")] = "fbi2",
  [GetHashKey("firetruk")] = "firetruk",
  [GetHashKey("lguard")] = "lguard",
  [GetHashKey("pbus")] = "pbus",
  [GetHashKey("police")] = "police",
  [GetHashKey("police2")] = "police2",
  [GetHashKey("police3")] = "police3",
  [GetHashKey("police4")] = "police4",
  [GetHashKey("policeb")] = "policeb",
  [GetHashKey("polmav")] = "polmav",
  [GetHashKey("policeold1")] = "policeold1",
  [GetHashKey("policeold2")] = "policeold2",
  [GetHashKey("policet")] = "policet",
  [GetHashKey("pranger")] = "pranger",
  [GetHashKey("predator")] = "predator",
  [GetHashKey("riot")] = "riot",
  [GetHashKey("riot2")] = "riot2",
  [GetHashKey("sheriff")] = "sheriff",
  [GetHashKey("sheriff2")] = "sheriff2",
  [GetHashKey("akula")] = "akula",
  [GetHashKey("annihilator")] = "annihilator",
  [GetHashKey("buzzard")] = "buzzard",
  [GetHashKey("buzzard2")] = "buzzard2",
  [GetHashKey("cargobob")] = "cargobob",
  [GetHashKey("cargobob2")] = "cargobob2",
  [GetHashKey("cargobob3")] = "cargobob3",
  [GetHashKey("cargobob4")] = "cargobob4",
  [GetHashKey("frogger")] = "frogger",
  [GetHashKey("frogger2")] = "frogger2",
  [GetHashKey("havok")] = "havok",
  [GetHashKey("hunter")] = "hunter",
  [GetHashKey("maverick")] = "maverick",
  [GetHashKey("savage")] = "savage",
  [GetHashKey("seasparrow")] = "seasparrow",
  [GetHashKey("skylift")] = "skylift",
  [GetHashKey("supervolito")] = "supervolito",
  [GetHashKey("supervolito2")] = "supervolito2",
  [GetHashKey("swift")] = "swift",
  [GetHashKey("swift2")] = "swift2",
  [GetHashKey("valkyrie")] = "valkyrie",
  [GetHashKey("valkyrie2")] = "valkyrie2",
  [GetHashKey("volatus")] = "volatus",
  [GetHashKey("annihilator2")] = "annihilator2",
  [GetHashKey("seasparrow2")] = "seasparrow2",
  [GetHashKey("seasparrow3")] = "seasparrow3",
  [GetHashKey("bulldozer")] = "bulldozer",
  [GetHashKey("cutter")] = "cutter",
  [GetHashKey("dump")] = "dump",
  [GetHashKey("flatbed")] = "flatbed",
  [GetHashKey("guardian")] = "guardian",
  [GetHashKey("handler")] = "handler",
  [GetHashKey("mixer")] = "mixer",
  [GetHashKey("mixer2")] = "mixer2",
  [GetHashKey("rubble")] = "rubble",
  [GetHashKey("tiptruck")] = "tiptruck",
  [GetHashKey("tiptruck2")] = "tiptruck2",
  [GetHashKey("apc")] = "apc",
  [GetHashKey("barracks")] = "barracks",
  [GetHashKey("barracks2")] = "barracks2",
  [GetHashKey("barracks3")] = "barracks3",
  [GetHashKey("barrage")] = "barrage",
  [GetHashKey("chernobog")] = "chernobog",
  [GetHashKey("crusader")] = "crusader",
  [GetHashKey("halftrack")] = "halftrack",
  [GetHashKey("khanjali")] = "khanjali",
  [GetHashKey("minitank")] = "minitank",
  [GetHashKey("rhino")] = "rhino",
  [GetHashKey("scarab")] = "scarab",
  [GetHashKey("scarab2")] = "scarab2",
  [GetHashKey("scarab3")] = "scarab3",
  [GetHashKey("thruster")] = "thruster",
  [GetHashKey("trailersmall2")] = "trailersmall2",
  [GetHashKey("vetir")] = "vetir",
  [GetHashKey("akuma")] = "akuma",
  [GetHashKey("avarus")] = "avarus",
  [GetHashKey("bagger")] = "bagger",
  [GetHashKey("bati")] = "bati",
  [GetHashKey("bati2")] = "bati2",
  [GetHashKey("bf400")] = "bf400",
  [GetHashKey("carbonrs")] = "carbonrs",
  [GetHashKey("chimera")] = "chimera",
  [GetHashKey("cliffhanger")] = "cliffhanger",
  [GetHashKey("daemon")] = "daemon",
  [GetHashKey("daemon2")] = "daemon2",
  [GetHashKey("defiler")] = "defiler",
  [GetHashKey("deathbike")] = "deathbike",
  [GetHashKey("deathbike2")] = "deathbike2",
  [GetHashKey("deathbike3")] = "deathbike3",
  [GetHashKey("diablous")] = "diablous",
  [GetHashKey("diablous2")] = "diablous2",
  [GetHashKey("double")] = "double",
  [GetHashKey("enduro")] = "enduro",
  [GetHashKey("esskey")] = "esskey",
  [GetHashKey("faggio")] = "faggio",
  [GetHashKey("faggio2")] = "faggio2",
  [GetHashKey("faggio3")] = "faggio3",
  [GetHashKey("fcr")] = "fcr",
  [GetHashKey("fcr2")] = "fcr2",
  [GetHashKey("gargoyle")] = "gargoyle",
  [GetHashKey("hakuchou")] = "hakuchou",
  [GetHashKey("hakuchou2")] = "hakuchou2",
  [GetHashKey("hexer")] = "hexer",
  [GetHashKey("innovation")] = "innovation",
  [GetHashKey("lectro")] = "lectro",
  [GetHashKey("manchez")] = "manchez",
  [GetHashKey("nemesis")] = "nemesis",
  [GetHashKey("nightblade")] = "nightblade",
  [GetHashKey("oppressor")] = "oppressor",
  [GetHashKey("oppressor2")] = "oppressor2",
  [GetHashKey("pcj")] = "pcj",
  [GetHashKey("ratbike")] = "ratbike",
  [GetHashKey("ruffian")] = "ruffian",
  [GetHashKey("rrocket")] = "rrocket",
  [GetHashKey("sanchez")] = "sanchez",
  [GetHashKey("sanchez2")] = "sanchez2",
  [GetHashKey("sanctus")] = "sanctus",
  [GetHashKey("shotaro")] = "shotaro",
  [GetHashKey("sovereign")] = "sovereign",
  [GetHashKey("stryder")] = "stryder",
  [GetHashKey("thrust")] = "thrust",
  [GetHashKey("vader")] = "vader",
  [GetHashKey("vindicator")] = "vindicator",
  [GetHashKey("vortex")] = "vortex",
  [GetHashKey("wolfsbane")] = "wolfsbane",
  [GetHashKey("zombiea")] = "zombiea",
  [GetHashKey("zombieb")] = "zombieb",
  [GetHashKey("manchez2")] = "manchez2",
  [GetHashKey("blade")] = "blade",
  [GetHashKey("buccaneer")] = "buccaneer",
  [GetHashKey("buccaneer2")] = "buccaneer2",
  [GetHashKey("chino")] = "chino",
  [GetHashKey("chino2")] = "chino2",
  [GetHashKey("clique")] = "clique",
  [GetHashKey("coquette3")] = "coquette3",
  [GetHashKey("deviant")] = "deviant",
  [GetHashKey("dominator")] = "dominator",
  [GetHashKey("dominator2")] = "dominator2",
  [GetHashKey("dominator3")] = "dominator3",
  [GetHashKey("dominator4")] = "dominator4",
  [GetHashKey("dominator5")] = "dominator5",
  [GetHashKey("dominator6")] = "dominator6",
  [GetHashKey("dukes")] = "dukes",
  [GetHashKey("dukes2")] = "dukes2",
  [GetHashKey("dukes3")] = "dukes3",
  [GetHashKey("faction")] = "faction",
  [GetHashKey("faction2")] = "faction2",
  [GetHashKey("faction3")] = "faction3",
  [GetHashKey("ellie")] = "ellie",
  [GetHashKey("gauntlet")] = "gauntlet",
  [GetHashKey("gauntlet2")] = "gauntlet2",
  [GetHashKey("gauntlet3")] = "gauntlet3",
  [GetHashKey("gauntlet4")] = "gauntlet4",
  [GetHashKey("gauntlet5")] = "gauntlet5",
  [GetHashKey("hermes")] = "hermes",
  [GetHashKey("hotknife")] = "hotknife",
  [GetHashKey("hustler")] = "hustler",
  [GetHashKey("impaler")] = "impaler",
  [GetHashKey("impaler2")] = "impaler2",
  [GetHashKey("impaler3")] = "impaler3",
  [GetHashKey("impaler4")] = "impaler4",
  [GetHashKey("imperator")] = "imperator",
  [GetHashKey("imperator2")] = "imperator2",
  [GetHashKey("imperator3")] = "imperator3",
  [GetHashKey("lurcher")] = "lurcher",
  [GetHashKey("moonbeam")] = "moonbeam",
  [GetHashKey("moonbeam2")] = "moonbeam2",
  [GetHashKey("nightshade")] = "nightshade",
  [GetHashKey("peyote2")] = "peyote2",
  [GetHashKey("phoenix")] = "phoenix",
  [GetHashKey("picador")] = "picador",
  [GetHashKey("ratloader")] = "ratloader",
  [GetHashKey("ratloader2")] = "ratloader2",
  [GetHashKey("ruiner")] = "ruiner",
  [GetHashKey("ruiner2")] = "ruiner2",
  [GetHashKey("ruiner3")] = "ruiner3",
  [GetHashKey("sabregt")] = "sabregt",
  [GetHashKey("sabregt2")] = "sabregt2",
  [GetHashKey("slamvan")] = "slamvan",
  [GetHashKey("slamvan2")] = "slamvan2",
  [GetHashKey("slamvan3")] = "slamvan3",
  [GetHashKey("slamvan4")] = "slamvan4",
  [GetHashKey("slamvan5")] = "slamvan5",
  [GetHashKey("slamvan6")] = "slamvan6",
  [GetHashKey("stalion")] = "stalion",
  [GetHashKey("stalion2")] = "stalion2",
  [GetHashKey("tampa")] = "tampa",
  [GetHashKey("tampa3")] = "tampa3",
  [GetHashKey("tulip")] = "tulip",
  [GetHashKey("vamos")] = "vamos",
  [GetHashKey("vigero")] = "vigero",
  [GetHashKey("virgo")] = "virgo",
  [GetHashKey("virgo2")] = "virgo2",
  [GetHashKey("virgo3")] = "virgo3",
  [GetHashKey("voodoo")] = "voodoo",
  [GetHashKey("voodoo2")] = "voodoo2",
  [GetHashKey("yosemite")] = "yosemite",
  [GetHashKey("yosemite2")] = "yosemite2",
  [GetHashKey("yosemite3")] = "yosemite3",
  [GetHashKey("bfinjection")] = "bfinjection",
  [GetHashKey("bifta")] = "bifta",
  [GetHashKey("blazer")] = "blazer",
  [GetHashKey("blazer2")] = "blazer2",
  [GetHashKey("blazer3")] = "blazer3",
  [GetHashKey("blazer4")] = "blazer4",
  [GetHashKey("blazer5")] = "blazer5",
  [GetHashKey("bodhi2")] = "bodhi2",
  [GetHashKey("brawler")] = "brawler",
  [GetHashKey("bruiser")] = "bruiser",
  [GetHashKey("bruiser2")] = "bruiser2",
  [GetHashKey("bruiser3")] = "bruiser3",
  [GetHashKey("brutus")] = "brutus",
  [GetHashKey("brutus2")] = "brutus2",
  [GetHashKey("brutus3")] = "brutus3",
  [GetHashKey("caracara")] = "caracara",
  [GetHashKey("caracara2")] = "caracara2",
  [GetHashKey("dloader")] = "dloader",
  [GetHashKey("dubsta3")] = "dubsta3",
  [GetHashKey("dune")] = "dune",
  [GetHashKey("dune2")] = "dune2",
  [GetHashKey("dune3")] = "dune3",
  [GetHashKey("dune4")] = "dune4",
  [GetHashKey("dune5")] = "dune5",
  [GetHashKey("everon")] = "everon",
  [GetHashKey("freecrawler")] = "freecrawler",
  [GetHashKey("hellion")] = "hellion",
  [GetHashKey("insurgent")] = "insurgent",
  [GetHashKey("insurgent2")] = "insurgent2",
  [GetHashKey("insurgent3")] = "insurgent3",
  [GetHashKey("kalahari")] = "kalahari",
  [GetHashKey("kamacho")] = "kamacho",
  [GetHashKey("marshall")] = "marshall",
  [GetHashKey("mesa3")] = "mesa3",
  [GetHashKey("monster")] = "monster",
  [GetHashKey("monster3")] = "monster3",
  [GetHashKey("monster4")] = "monster4",
  [GetHashKey("monster5")] = "monster5",
  [GetHashKey("menacer")] = "menacer",
  [GetHashKey("outlaw")] = "outlaw",
  [GetHashKey("nightshark")] = "nightshark",
  [GetHashKey("rancherxl")] = "rancherxl",
  [GetHashKey("rancherxl2")] = "rancherxl2",
  [GetHashKey("rebel")] = "rebel",
  [GetHashKey("rebel2")] = "rebel2",
  [GetHashKey("rcbandito")] = "rcbandito",
  [GetHashKey("riata")] = "riata",
  [GetHashKey("sandking")] = "sandking",
  [GetHashKey("sandking2")] = "sandking2",
  [GetHashKey("technical")] = "technical",
  [GetHashKey("technical2")] = "technical2",
  [GetHashKey("technical3")] = "technical3",
  [GetHashKey("trophytruck")] = "trophytruck",
  [GetHashKey("trophytruck2")] = "trophytruck2",
  [GetHashKey("vagrant")] = "vagrant",
  [GetHashKey("zhaba")] = "zhaba",
  [GetHashKey("verus")] = "verus",
  [GetHashKey("winky")] = "winky",
  [GetHashKey("formula")] = "formula",
  [GetHashKey("formula2")] = "formula2",
  [GetHashKey("openwheel1")] = "openwheel1",
  [GetHashKey("openwheel2")] = "openwheel2",
  [GetHashKey("alphaz1")] = "alphaz1",
  [GetHashKey("avenger")] = "avenger",
  [GetHashKey("avenger2")] = "avenger2",
  [GetHashKey("besra")] = "besra",
  [GetHashKey("blimp")] = "blimp",
  [GetHashKey("blimp2")] = "blimp2",
  [GetHashKey("blimp3")] = "blimp3",
  [GetHashKey("bombushka")] = "bombushka",
  [GetHashKey("cargoplane")] = "cargoplane",
  [GetHashKey("cuban800")] = "cuban800",
  [GetHashKey("dodo")] = "dodo",
  [GetHashKey("duster")] = "duster",
  [GetHashKey("howard")] = "howard",
  [GetHashKey("hydra")] = "hydra",
  [GetHashKey("jet")] = "jet",
  [GetHashKey("lazer")] = "lazer",
  [GetHashKey("luxor")] = "luxor",
  [GetHashKey("luxor2")] = "luxor2",
  [GetHashKey("mammatus")] = "mammatus",
  [GetHashKey("microlight")] = "microlight",
  [GetHashKey("miljet")] = "miljet",
  [GetHashKey("mogul")] = "mogul",
  [GetHashKey("molotok")] = "molotok",
  [GetHashKey("nimbus")] = "nimbus",
  [GetHashKey("nokota")] = "nokota",
  [GetHashKey("pyro")] = "pyro",
  [GetHashKey("rogue")] = "rogue",
  [GetHashKey("seabreeze")] = "seabreeze",
  [GetHashKey("shamal")] = "shamal",
  [GetHashKey("starling")] = "starling",
  [GetHashKey("strikeforce")] = "strikeforce",
  [GetHashKey("stunt")] = "stunt",
  [GetHashKey("titan")] = "titan",
  [GetHashKey("tula")] = "tula",
  [GetHashKey("velum")] = "velum",
  [GetHashKey("velum2")] = "velum2",
  [GetHashKey("vestra")] = "vestra",
  [GetHashKey("volatol")] = "volatol",
  [GetHashKey("alkonost")] = "alkonost",
  [GetHashKey("baller")] = "baller",
  [GetHashKey("baller2")] = "baller2",
  [GetHashKey("baller3")] = "baller3",
  [GetHashKey("baller4")] = "baller4",
  [GetHashKey("baller5")] = "baller5",
  [GetHashKey("baller6")] = "baller6",
  [GetHashKey("bjxl")] = "bjxl",
  [GetHashKey("cavalcade")] = "cavalcade",
  [GetHashKey("cavalcade2")] = "cavalcade2",
  [GetHashKey("contender")] = "contender",
  [GetHashKey("dubsta")] = "dubsta",
  [GetHashKey("dubsta2")] = "dubsta2",
  [GetHashKey("fq2")] = "fq2",
  [GetHashKey("granger")] = "granger",
  [GetHashKey("gresley")] = "gresley",
  [GetHashKey("habanero")] = "habanero",
  [GetHashKey("huntley")] = "huntley",
  [GetHashKey("landstalker")] = "landstalker",
  [GetHashKey("landstalker2")] = "landstalker2",
  [GetHashKey("mesa")] = "mesa",
  [GetHashKey("mesa2")] = "mesa2",
  [GetHashKey("novak")] = "novak",
  [GetHashKey("patriot")] = "patriot",
  [GetHashKey("patriot2")] = "patriot2",
  [GetHashKey("radi")] = "radi",
  [GetHashKey("rebla")] = "rebla",
  [GetHashKey("rocoto")] = "rocoto",
  [GetHashKey("seminole")] = "seminole",
  [GetHashKey("seminole2")] = "seminole2",
  [GetHashKey("serrano")] = "serrano",
  [GetHashKey("toros")] = "toros",
  [GetHashKey("xls")] = "xls",
  [GetHashKey("xls2")] = "xls2",
  [GetHashKey("squaddie")] = "squaddie",
  [GetHashKey("asea")] = "asea",
  [GetHashKey("asea2")] = "asea2",
  [GetHashKey("asterope")] = "asterope",
  [GetHashKey("cog55")] = "cog55",
  [GetHashKey("cog552")] = "cog552",
  [GetHashKey("cognoscenti")] = "cognoscenti",
  [GetHashKey("cognoscenti2")] = "cognoscenti2",
  [GetHashKey("emperor")] = "emperor",
  [GetHashKey("emperor2")] = "emperor2",
  [GetHashKey("emperor3")] = "emperor3",
  [GetHashKey("fugitive")] = "fugitive",
  [GetHashKey("glendale")] = "glendale",
  [GetHashKey("glendale2")] = "glendale2",
  [GetHashKey("ingot")] = "ingot",
  [GetHashKey("intruder")] = "intruder",
  [GetHashKey("limo2")] = "limo2",
  [GetHashKey("premier")] = "premier",
  [GetHashKey("primo")] = "primo",
  [GetHashKey("primo2")] = "primo2",
  [GetHashKey("regina")] = "regina",
  [GetHashKey("romero")] = "romero",
  [GetHashKey("stafford")] = "stafford",
  [GetHashKey("stanier")] = "stanier",
  [GetHashKey("stratum")] = "stratum",
  [GetHashKey("stretch")] = "stretch",
  [GetHashKey("superd")] = "superd",
  [GetHashKey("surge")] = "surge",
  [GetHashKey("tailgater")] = "tailgater",
  [GetHashKey("warrener")] = "warrener",
  [GetHashKey("washington")] = "washington",
  [GetHashKey("airbus")] = "airbus",
  [GetHashKey("brickade")] = "brickade",
  [GetHashKey("bus")] = "bus",
  [GetHashKey("coach")] = "coach",
  [GetHashKey("pbus2")] = "pbus2",
  [GetHashKey("rallytruck")] = "rallytruck",
  [GetHashKey("rentalbus")] = "rentalbus",
  [GetHashKey("taxi")] = "taxi",
  [GetHashKey("tourbus")] = "tourbus",
  [GetHashKey("trash")] = "trash",
  [GetHashKey("trash2")] = "trash2",
  [GetHashKey("wastelander")] = "wastelander",
  [GetHashKey("alpha")] = "alpha",
  [GetHashKey("banshee")] = "banshee",
  [GetHashKey("bestiagts")] = "bestiagts",
  [GetHashKey("blista2")] = "blista2",
  [GetHashKey("blista3")] = "blista3",
  [GetHashKey("buffalo")] = "buffalo",
  [GetHashKey("buffalo2")] = "buffalo2",
  [GetHashKey("buffalo3")] = "buffalo3",
  [GetHashKey("carbonizzare")] = "carbonizzare",
  [GetHashKey("comet2")] = "comet2",
  [GetHashKey("comet3")] = "comet3",
  [GetHashKey("comet4")] = "comet4",
  [GetHashKey("comet5")] = "comet5",
  [GetHashKey("coquette")] = "coquette",
  [GetHashKey("coquette4")] = "coquette4",
  [GetHashKey("drafter")] = "drafter",
  [GetHashKey("deveste")] = "deveste",
  [GetHashKey("elegy")] = "elegy",
  [GetHashKey("elegy2")] = "elegy2",
  [GetHashKey("feltzer2")] = "feltzer2",
  [GetHashKey("flashgt")] = "flashgt",
  [GetHashKey("furoregt")] = "furoregt",
  [GetHashKey("fusilade")] = "fusilade",
  [GetHashKey("futo")] = "futo",
  [GetHashKey("gb200")] = "gb200",
  [GetHashKey("hotring")] = "hotring",
  [GetHashKey("komoda")] = "komoda",
  [GetHashKey("imorgon")] = "imorgon",
  [GetHashKey("issi7")] = "issi7",
  [GetHashKey("italigto")] = "italigto",
  [GetHashKey("jugular")] = "jugular",
  [GetHashKey("jester")] = "jester",
  [GetHashKey("jester2")] = "jester2",
  [GetHashKey("jester3")] = "jester3",
  [GetHashKey("khamelion")] = "khamelion",
  [GetHashKey("kuruma")] = "kuruma",
  [GetHashKey("kuruma2")] = "kuruma2",
  [GetHashKey("locust")] = "locust",
  [GetHashKey("lynx")] = "lynx",
  [GetHashKey("massacro")] = "massacro",
  [GetHashKey("massacro2")] = "massacro2",
  [GetHashKey("neo")] = "neo",
  [GetHashKey("neon")] = "neon",
  [GetHashKey("ninef")] = "ninef",
  [GetHashKey("ninef2")] = "ninef2",
  [GetHashKey("omnis")] = "omnis",
  [GetHashKey("paragon")] = "paragon",
  [GetHashKey("paragon2")] = "paragon2",
  [GetHashKey("pariah")] = "pariah",
  [GetHashKey("penumbra")] = "penumbra",
  [GetHashKey("penumbra2")] = "penumbra2",
  [GetHashKey("raiden")] = "raiden",
  [GetHashKey("rapidgt")] = "rapidgt",
  [GetHashKey("rapidgt2")] = "rapidgt2",
  [GetHashKey("raptor")] = "raptor",
  [GetHashKey("revolter")] = "revolter",
  [GetHashKey("ruston")] = "ruston",
  [GetHashKey("schafter2")] = "schafter2",
  [GetHashKey("schafter3")] = "schafter3",
  [GetHashKey("schafter4")] = "schafter4",
  [GetHashKey("schafter5")] = "schafter5",
  [GetHashKey("schafter6")] = "schafter6",
  [GetHashKey("schlagen")] = "schlagen",
  [GetHashKey("schwarzer")] = "schwarzer",
  [GetHashKey("sentinel3")] = "sentinel3",
  [GetHashKey("seven70")] = "seven70",
  [GetHashKey("specter")] = "specter",
  [GetHashKey("specter2")] = "specter2",
  [GetHashKey("streiter")] = "streiter",
  [GetHashKey("sugoi")] = "sugoi",
  [GetHashKey("sultan")] = "sultan",
  [GetHashKey("sultan2")] = "sultan2",
  [GetHashKey("surano")] = "surano",
  [GetHashKey("tampa2")] = "tampa2",
  [GetHashKey("tropos")] = "tropos",
  [GetHashKey("verlierer2")] = "verlierer2",
  [GetHashKey("vstr")] = "vstr",
  [GetHashKey("zr380")] = "zr380",
  [GetHashKey("zr3802")] = "zr3802",
  [GetHashKey("zr3803")] = "zr3803",
  [GetHashKey("italirsx")] = "italirsx",
  [GetHashKey("veto")] = "veto",
  [GetHashKey("veto2")] = "veto2",
  [GetHashKey("ardent")] = "ardent",
  [GetHashKey("btype")] = "btype",
  [GetHashKey("btype2")] = "btype2",
  [GetHashKey("btype3")] = "btype3",
  [GetHashKey("casco")] = "casco",
  [GetHashKey("cheetah2")] = "cheetah2",
  [GetHashKey("coquette2")] = "coquette2",
  [GetHashKey("deluxo")] = "deluxo",
  [GetHashKey("dynasty")] = "dynasty",
  [GetHashKey("fagaloa")] = "fagaloa",
  [GetHashKey("feltzer3")] = "feltzer3",
  [GetHashKey("gt500")] = "gt500",
  [GetHashKey("infernus2")] = "infernus2",
  [GetHashKey("jb700")] = "jb700",
  [GetHashKey("jb7002")] = "jb7002",
  [GetHashKey("mamba")] = "mamba",
  [GetHashKey("manana")] = "manana",
  [GetHashKey("manana2")] = "manana2",
  [GetHashKey("michelli")] = "michelli",
  [GetHashKey("monroe")] = "monroe",
  [GetHashKey("nebula")] = "nebula",
  [GetHashKey("peyote")] = "peyote",
  [GetHashKey("peyote3")] = "peyote3",
  [GetHashKey("pigalle")] = "pigalle",
  [GetHashKey("rapidgt3")] = "rapidgt3",
  [GetHashKey("retinue")] = "retinue",
  [GetHashKey("retinue2")] = "retinue2",
  [GetHashKey("savestra")] = "savestra",
  [GetHashKey("stinger")] = "stinger",
  [GetHashKey("stingergt")] = "stingergt",
  [GetHashKey("stromberg")] = "stromberg",
  [GetHashKey("swinger")] = "swinger",
  [GetHashKey("torero")] = "torero",
  [GetHashKey("tornado")] = "tornado",
  [GetHashKey("tornado2")] = "tornado2",
  [GetHashKey("tornado3")] = "tornado3",
  [GetHashKey("tornado4")] = "tornado4",
  [GetHashKey("tornado5")] = "tornado5",
  [GetHashKey("tornado6")] = "tornado6",
  [GetHashKey("turismo2")] = "turismo2",
  [GetHashKey("viseris")] = "viseris",
  [GetHashKey("z190")] = "z190",
  [GetHashKey("ztype")] = "ztype",
  [GetHashKey("zion3")] = "zion3",
  [GetHashKey("cheburek")] = "cheburek",
  [GetHashKey("toreador")] = "toreador",
  [GetHashKey("adder")] = "adder",
  [GetHashKey("autarch")] = "autarch",
  [GetHashKey("banshee2")] = "banshee2",
  [GetHashKey("bullet")] = "bullet",
  [GetHashKey("cheetah")] = "cheetah",
  [GetHashKey("cyclone")] = "cyclone",
  [GetHashKey("entity2")] = "entity2",
  [GetHashKey("entityxf")] = "entityxf",
  [GetHashKey("emerus")] = "emerus",
  [GetHashKey("fmj")] = "fmj",
  [GetHashKey("furia")] = "furia",
  [GetHashKey("gp1")] = "gp1",
  [GetHashKey("infernus")] = "infernus",
  [GetHashKey("italigtb")] = "italigtb",
  [GetHashKey("italigtb2")] = "italigtb2",
  [GetHashKey("krieger")] = "krieger",
  [GetHashKey("le7b")] = "le7b",
  [GetHashKey("nero")] = "nero",
  [GetHashKey("nero2")] = "nero2",
  [GetHashKey("osiris")] = "osiris",
  [GetHashKey("penetrator")] = "penetrator",
  [GetHashKey("pfister811")] = "pfister811",
  [GetHashKey("prototipo")] = "prototipo",
  [GetHashKey("reaper")] = "reaper",
  [GetHashKey("s80")] = "s80",
  [GetHashKey("sc1")] = "sc1",
  [GetHashKey("scramjet")] = "scramjet",
  [GetHashKey("sheava")] = "sheava",
  [GetHashKey("sultanrs")] = "sultanrs",
  [GetHashKey("t20")] = "t20",
  [GetHashKey("taipan")] = "taipan",
  [GetHashKey("tempesta")] = "tempesta",
  [GetHashKey("tezeract")] = "tezeract",
  [GetHashKey("thrax")] = "thrax",
  [GetHashKey("tigon")] = "tigon",
  [GetHashKey("turismor")] = "turismor",
  [GetHashKey("tyrant")] = "tyrant",
  [GetHashKey("tyrus")] = "tyrus",
  [GetHashKey("vacca")] = "vacca",
  [GetHashKey("vagner")] = "vagner",
  [GetHashKey("vigilante")] = "vigilante",
  [GetHashKey("visione")] = "visione",
  [GetHashKey("voltic")] = "voltic",
  [GetHashKey("voltic2")] = "voltic2",
  [GetHashKey("xa21")] = "xa21",
  [GetHashKey("zentorno")] = "zentorno",
  [GetHashKey("zorrusso")] = "zorrusso",
  [GetHashKey("armytanker")] = "armytanker",
  [GetHashKey("armytrailer")] = "armytrailer",
  [GetHashKey("armytrailer2")] = "armytrailer2",
  [GetHashKey("baletrailer")] = "baletrailer",
  [GetHashKey("boattrailer")] = "boattrailer",
  [GetHashKey("cablecar")] = "cablecar",
  [GetHashKey("docktrailer")] = "docktrailer",
  [GetHashKey("freighttrailer")] = "freighttrailer",
  [GetHashKey("graintrailer")] = "graintrailer",
  [GetHashKey("proptrailer")] = "proptrailer",
  [GetHashKey("raketrailer")] = "raketrailer",
  [GetHashKey("tr2")] = "tr2",
  [GetHashKey("tr3")] = "tr3",
  [GetHashKey("tr4")] = "tr4",
  [GetHashKey("trflat")] = "trflat",
  [GetHashKey("tvtrailer")] = "tvtrailer",
  [GetHashKey("tanker")] = "tanker",
  [GetHashKey("tanker2")] = "tanker2",
  [GetHashKey("trailerlarge")] = "trailerlarge",
  [GetHashKey("trailerlogs")] = "trailerlogs",
  [GetHashKey("trailersmall")] = "trailersmall",
  [GetHashKey("trailers")] = "trailers",
  [GetHashKey("trailers2")] = "trailers2",
  [GetHashKey("trailers3")] = "trailers3",
  [GetHashKey("trailers4")] = "trailers4",
  [GetHashKey("freight")] = "freight",
  [GetHashKey("freightcar")] = "freightcar",
  [GetHashKey("freightcont1")] = "freightcont1",
  [GetHashKey("freightcont2")] = "freightcont2",
  [GetHashKey("freightgrain")] = "freightgrain",
  [GetHashKey("metrotrain")] = "metrotrain",
  [GetHashKey("tankercar")] = "tankercar",
  [GetHashKey("airtug")] = "airtug",
  [GetHashKey("caddy")] = "caddy",
  [GetHashKey("caddy2")] = "caddy2",
  [GetHashKey("caddy3")] = "caddy3",
  [GetHashKey("docktug")] = "docktug",
  [GetHashKey("forklift")] = "forklift",
  [GetHashKey("mower")] = "mower",
  [GetHashKey("ripley")] = "ripley",
  [GetHashKey("sadler")] = "sadler",
  [GetHashKey("sadler2")] = "sadler2",
  [GetHashKey("scrap")] = "scrap",
  [GetHashKey("towtruck")] = "towtruck",
  [GetHashKey("towtruck2")] = "towtruck2",
  [GetHashKey("tractor")] = "tractor",
  [GetHashKey("tractor2")] = "tractor2",
  [GetHashKey("tractor3")] = "tractor3",
  [GetHashKey("utillitruck")] = "utillitruck",
  [GetHashKey("utillitruck2")] = "utillitruck2",
  [GetHashKey("utillitruck3")] = "utillitruck3",
  [GetHashKey("slamtruck")] = "slamtruck",
  [GetHashKey("bison")] = "bison",
  [GetHashKey("bison2")] = "bison2",
  [GetHashKey("bison3")] = "bison3",
  [GetHashKey("bobcatxl")] = "bobcatxl",
  [GetHashKey("boxville")] = "boxville",
  [GetHashKey("boxville2")] = "boxville2",
  [GetHashKey("boxville3")] = "boxville3",
  [GetHashKey("boxville4")] = "boxville4",
  [GetHashKey("boxville5")] = "boxville5",
  [GetHashKey("burrito")] = "burrito",
  [GetHashKey("burrito2")] = "burrito2",
  [GetHashKey("burrito3")] = "burrito3",
  [GetHashKey("burrito4")] = "burrito4",
  [GetHashKey("burrito5")] = "burrito5",
  [GetHashKey("camper")] = "camper",
  [GetHashKey("gburrito")] = "gburrito",
  [GetHashKey("gburrito2")] = "gburrito2",
  [GetHashKey("journey")] = "journey",
  [GetHashKey("minivan")] = "minivan",
  [GetHashKey("minivan2")] = "minivan2",
  [GetHashKey("paradise")] = "paradise",
  [GetHashKey("pony")] = "pony",
  [GetHashKey("pony2")] = "pony2",
  [GetHashKey("rumpo")] = "rumpo",
  [GetHashKey("rumpo2")] = "rumpo2",
  [GetHashKey("rumpo3")] = "rumpo3",
  [GetHashKey("speedo")] = "speedo",
  [GetHashKey("speedo2")] = "speedo2",
  [GetHashKey("speedo4")] = "speedo4",
  [GetHashKey("surfer")] = "surfer",
  [GetHashKey("surfer2")] = "surfer2",
  [GetHashKey("taco")] = "taco",
  [GetHashKey("youga")] = "youga",
  [GetHashKey("youga2")] = "youga2",
  [GetHashKey("youga3")] = "youga3",
}

Ora.Config:SetDataCollection(
    "Anticheat:ServerSideEvents",
    {
      "8321hiue89js",
      "adminmenu:allowall",
      "3dme:shareDisplay",
      "AdminMenu:giveBank",
      "AdminMenu:giveCash",
      "AdminMenu:giveDirtyMoney",
      "Tem2LPs5Para5dCyjuHm87y2catFkMpV",
      "dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
      "antilynx8:anticheat",
      "antilynxr4:detect",
      "antilynxr6:detection",
      "ynx8:anticheat",
      "antilynx8r4a:anticheat",
      "lynx8:anticheat",
      "AntiLynxR4:kick",
      "AntiLynxR4:log",
      "bank:deposit",
      "bank:withdraw",
      "Banca:deposit",
      "Banca:withdraw",
      "BsCuff:Cuff696999",
      "CheckHandcuff",
      "cuffServer",
      "cuffGranted",
      "DiscordBot:playerDied",
      "DFWM:adminmenuenable",
      "DFWM:askAwake",
      "DFWM:checkup",
      "DFWM:cleanareaentity",
      "DFWM:cleanareapeds",
      "DFWM:cleanareaveh",
      "DFWM:enable",
      "DFWM:invalid",
      "DFWM:log",
      "DFWM:openmenu",
      "DFWM:spectate",
      "DFWM:ViolationDetected",
      "dmv:success",
      "eden_garage:payhealth",
      "ems:revive",
      "esx_ambulancejob:revive",
      "esx_ambulancejob:setDeathStatus",
      "esx_billing:sendBill",
      "esx_banksecurity:pay",
      "esx_blanchisseur:startWhitening",
      "esx_carthief:alertcops",
      "esx_carthief:pay",
      "esx_dmvschool:addLicense",
      "esx_dmvschool:pay",
      "esx_drugs:startHarvestWeed",
      "esx_drugs:startTransformWeed",
      "esx_drugs:startSellWeed",
      "esx_drugs:startHarvestCoke",
      "esx_drugs:startTransformCoke",
      "esx_drugs:startSellCoke",
      "esx_drugs:startHarvestMeth",
      "esx_drugs:startTransformMeth",
      "esx_drugs:startSellMeth",
      "esx_drugs:startHarvestOpium",
      "esx_drugs:startTransformOpium",
      "esx_drugs:startSellOpium",
      "esx_drugs:stopHarvestCoke",
      "esx_drugs:stopTransformCoke",
      "esx_drugs:stopSellCoke",
      "esx_drugs:stopHarvestMeth",
      "esx_drugs:stopTransformMeth",
      "esx_drugs:stopSellMeth",
      "esx_drugs:stopHarvestWeed",
      "esx_drugs:stopTransformWeed",
      "esx_drugs:stopSellWeed",
      "esx_drugs:stopHarvestOpium",
      "esx_drugs:stopTransformOpium",
      "esx_drugs:stopSellOpium",
      "esx:enterpolicecar",
      "esx_fueldelivery:pay",
      "esx:giveInventoryItem",
      "esx_garbagejob:pay",
      "esx_godirtyjob:pay",
      "esx_gopostaljob:pay",
      "esx_handcuffs:cuffing",
      "esx_jail:sendToJail",
      "esx_jail:unjailQuest",
      "esx_jailer:sendToJail",
      "esx_jailer:unjailTime",
      "esx_jobs:caution",
      "esx_mecanojob:onNPCJobCompleted",
      "esx_mechanicjob:startHarvest",
      "esx_mechanicjob:startCraft",
      "esx_pizza:pay",
      "esx_policejob:handcuff",
      "esx_policejob:requestarrest",
      "esx-qalle-jail:jailPlayer",
      "esx-qalle-jail:jailPlayerNew",
      "esx-qalle-hunting:reward",
      "esx-qalle-hunting:sell",
      "esx_ranger:pay",
      "esx:removeInventoryItem",
      "esx_truckerjob:pay",
      "esx_skin:responseSaveSkin",
      "esx_slotmachine:sv:2",
      "esx_society:getOnlinePlayers",
      "esx_society:setJob",
      "esx_vehicleshop:setVehicleOwned",
      "hentailover:xdlol",
      "JailUpdate",
      "js:jailuser",
      "js:removejailtime",
      "LegacyFuel:PayFuel",
      "ljail:jailplayer",
      "lscustoms:payGarage",
      "mellotrainer:adminTempBan",
      "mellotrainer:adminKick",
      "mellotrainer:s_adminKill",
      "NB:destituerplayer",
      "NB:recruterplayer",
      "OG_cuffs:cuffCheckNearest",
      "paramedic:revive",
      "police:cuffGranted",
      "unCuffServer",
      "uncuffGranted",
      "vrp_slotmachine:server:2",
      "whoapd:revive",
      "gcPhone:_internalAddMessageDFWM",
      "gcPhone:tchat_channelDFWM",
      "esx_vehicleshop:setVehicleOwnedDFWM",
      "esx_mafiajob:confiscateDFWMPlayerItem",
      "_chat:messageEntDFWMered",
      "lscustoms:pDFWMayGarage",
      "vrp_slotmachDFWMine:server:2",
      "Banca:dDFWMeposit",
      "bank:depDFWMosit",
      "esx_jobs:caDFWMution",
      "give_back",
      "esx_fueldDFWMelivery:pay",
      "esx_carthDFWMief:pay",
      "esx_godiDFWMrtyjob:pay",
      "esx_pizza:pDFWMay",
      "esx_ranger:pDFWMay",
      "esx_garbageDFWMjob:pay",
      "esx_truckDFWMerjob:pay",
      "AdminMeDFWMnu:giveBank",
      "AdminMDFWMenu:giveCash",
      "esx_goDFWMpostaljob:pay",
      "esx_baDFWMnksecurity:pay",
      "esx_sloDFWMtmachine:sv:2",
      "esx:giDFWMveInventoryItem",
      "NB:recDFWMruterplayer",
      "esx_biDFWMlling:sendBill",
      "esx_jDFWMailer:sendToJail",
      "esx_jaDFWMil:sendToJail",
      "js:jaDFWMiluser",
      "esx-qalle-jail:jailPDFWMlayer",
      "esx_dmvschool:pDFWMay",
      "LegacyFuel:PayFuDFWMel",
      "OG_cuffs:cuffCheckNeDFWMarest",
      "CheckHandcDFWMuff",
      "cuffSeDFWMrver",
      "cuffGDFWMranted",
      "police:cuffGDFWMranted",
      "esx_handcuffs:cufDFWMfing",
      "esx_policejob:haDFWMndcuff",
      "bank:withdDFWMraw",
      "dmv:succeDFWMss",
      "esx_skin:responseSaDFWMveSkin",
      "esx_dmvschool:addLiceDFWMnse",
      "esx_mechanicjob:starDFWMtCraft",
      "esx_drugs:startHarvestWDFWMeed",
      "esx_drugs:startTransfoDFWMrmWeed",
      "esx_drugs:startSellWeDFWMed",
      "esx_drugs:startHarvestDFWMCoke",
      "esx_drugs:startTransDFWMformCoke",
      "esx_drugs:startSellCDFWMoke",
      "esx_drugs:startHarDFWMvestMeth",
      "esx_drugs:startTDFWMransformMeth",
      "esx_drugs:startSellMDFWMeth",
      "esx_drugs:startHDFWMarvestOpium",
      "esx_drugs:startSellDFWMOpium",
      "esx_drugs:starDFWMtTransformOpium",
      "esx_blanchisDFWMseur:startWhitening",
      "esx_drugs:stopHarvDFWMestCoke",
      "esx_drugs:stopTranDFWMsformCoke",
      "esx_drugs:stopSellDFWMCoke",
      "esx_drugs:stopHarvesDFWMtMeth",
      "esx_drugs:stopTranDFWMsformMeth",
      "esx_drugs:stopSellMDFWMeth",
      "esx_drugs:stopHarDFWMvestWeed",
      "esx_drugs:stopTDFWMransformWeed",
      "esx_drugs:stopSellWDFWMeed",
      "esx_drugs:stopHarvestDFWMOpium",
      "esx_drugs:stopTransDFWMformOpium",
      "esx_drugs:stopSellOpiuDFWMm",
      "esx_society:openBosDFWMsMenu",
      "esx_jobs:caDFWMution",
      "esx_tankerjob:DFWMpay",
      "esx_vehicletrunk:givDFWMeDirty",
      "gambling:speDFWMnd",
      "AdminMenu:giveDirtyMDFWMoney",
      "esx_moneywash:depoDFWMsit",
      "esx_moneywash:witDFWMhdraw",
      "mission:completDFWMed",
      "truckerJob:succeDFWMss",
      "99kr-burglary:addMDFWMoney",
      "esx_jailer:unjailTiDFWMme",
      "esx_ambulancejob:reDFWMvive",
      "DiscordBot:plaDFWMyerDied",
      "esx:getShDFWMaredObjDFWMect",
      "esx_society:getOnlDFWMinePlayers",
      "js:jaDFWMiluser",
      "h:xd",
      "adminmenu:setsalary",
      "adminmenu:cashoutall",
      "bank:tranDFWMsfer",
      "paycheck:bonDFWMus",
      "paycheck:salDFWMary",
      "HCheat:TempDisableDetDFWMection",
      "esx_drugs:pickedUpCDFWMannabis",
      "esx_drugs:processCDFWMannabis",
      "esx-qalle-hunting:DFWMreward",
      "esx-qalle-hunting:seDFWMll",
      "esx_mecanojob:onNPCJobCDFWMompleted",
      "BsCuff:Cuff696DFWM999",
      "veh_SR:CheckMonDFWMeyForVeh",
      "esx_carthief:alertcoDFWMps",
      "mellotrainer:adminTeDFWMmpBan",
      "mellotrainer:adminKickDFWM",
      "esx_society:putVehicleDFWMInGarage",
      'bank:transfer',
      'UnJP',
      'esx-qalle-jail:openJailMenu',
      'ambulancier:selfRespawn',
      'esx_inventoryhud:openPlayerInventory',
      'esx:getSharedObject',
      'esx:serverCallback',
      'esx:showNotification',
      'esx:showAdvancedNotification',
      'esx:showHelpNotification',
      'esx:playerLoaded',
      'esx:onPlayerDeath',
      'skinchanger:loadDefaultModel',
      'skinchanger:modelLoaded',
      'esx:restoreLoadout',
      'esx:setAccountMoney',
      'esx:addInventoryItem',
      'esx:removeInventoryItem',
      'esx:setJob',
      'esx:setJob2',
      'esx:addWeapon',
      'esx:addWeaponComponent',
      'esx:removeWeapon',
      'esx:removeWeaponComponent',
      'esx:teleport',
      'esx:spawnVehicle',
      'esx:spawnObject',
      'esx:pickup',
      'esx:removePickup',
      'esx:pickupWeapon',
      'esx:spawnPed',
      'esx:deleteVehicle',
      'es:addedMoney',
      'es:removedMoney',
      'es:addedBank',
      'es:removedBank',
      'es:setPlayerDecorator',
      'skinchanger:getSkin',
      'skinchanger:loadClothes',
      'esx_skin:openRestrictedMenu',
      'esx_skin:getLastSkin',
      'esx_skin:setLastSkin',
      'esx_skin:openSaveableMenu',
      'skinchanger:loadSkin',
      'esx_billing:newBill',
      'esx_status:loaded',
      'esx_optionalneeds:onDrink',
      'esx_status:registerStatus',
      'esx_status:getStatus',
      'esx_property:getProperties',
      'esx_property:getProperty',
      'esx_property:getGateway',
      'esx_property:setPropertyOwned',
      'sendProximityMessage',
      'sendProximityMessageMe',
      'sendProximityMessageDo',
      'esx_skin:openMenu',
      'esx_skin:openSaveableRestrictedMenu',
      'skinchanger:change',
      'esx_status:load',
      'esx_status:set',
      'esx_status:add',
      'esx_status:remove',
      'esx_status:setDisplay',
      'esx_status:onTick',
      'tattoo:buySuccess',
      'esx_weashop:loadLicenses',
      'jsfour-idcard:open',
      'esx_basicneeds:resetStatus',
      'esx_basicneeds:healPlayer',
      'esx_basicneeds:onEat',
      'esx_basicneeds:onDrink',
      'esx_service:notifyAllInService',
      'esx_society:openBossMenu',
      'esx_society:openBossMenu2',
      'esx_society:toggleSocietyHud',
      'esx_society:toggleSociety2Hud',
      'esx_society:setSocietyMoney',
      'esx_society:setSociety2Money',
      'esx_holdupbank:currentlyrobbing',
      'esx_holdupbank:killblip',
      'esx_holdupbank:setblip',
      'esx_holdupbank:toofarlocal',
      'esx_holdupbank:robberycomplete',
      'esx_holdup:currentlyrobbing',
      'esx_holdup:killblip',
      'esx_holdup:setblip',
      'esx_holdup:toofarlocal',
      'esx_holdup:robberycomplete',
      'esx_holdup:starttimer',
      'esx_ambulancejob:heal',
      'esx_ambulancejob:revive',
      'esx_ambulancejob:requestDeath',
      'esx_phone:addSpecialContact',
      'esx_lscustom:installMod',
      'esx_lscustom:cancelInstallMod',
      'esx_basicneeds:isEating',
      'esx:setjob2',
      'esx_jobs:publicTeleports',
      'esx_jobs:action',
      'esx_jobs:spawnJobVehicle',
      'esx_vehiclelock:updatePlayerCars',
      'esx_mecanojob:onHijack',
      'esx_mecanojob:onCarokit',
      'esx_mecanojob:onFixkit',
      'esx_phone:cancelMessage',
      'esx_policejob:handcuff',
      'esx_policejob:unrestrain',
      'esx_policejob:drag',
      'esx_policejob:putInVehicle',
      'esx_policejob:OutVehicle',
      'esx_policejob:updateBlip',
      'esx_phone:removeSpecialContact',
      'esx_vigneronjob:annonce',
      'esx_vigneronjob:annoncestop',
      'esx_truck_inventory:setOwnedVehicule',
      'esx_truck_inventory:getInventoryLoaded',
      'InteractSound_CL:PlayOnOne',
      'InteractSound_CL:PlayOnAll',
      'InteractSound_CL:PlayWithinDistance',
      '::{korioz#0110}::esx:getSharedObject',
    } 
  )