---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/08/2019 00:08
---

RMenu.Add(
    "personnal",
    "animations",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "main"), "Animations", "Animations disponibles")
)

RegisterCommand(
    "playanim",
    function(source, args)
        --print(json.encode(args))
        anim = {args[1], args[2]}
        doAnim(anim, nil, 1)
    end
)

Citizen.CreateThread(
    function()
        local DemarcheInd = 1
        local HumeurInd = 1
        local Demarche = {}
        for i = 1, #demarcheAnim, 1 do
            Demarche[i] = demarcheAnim[i].name
        end
        local Humor = {}
        for i = 1, #emoteList, 1 do
            Humor[i] = emoteList[i].name
        end

        -- Add event handler for the ora event when player is loaded to load the humor and clipset
        AddEventHandler("Ora::CE::Character:Loaded", function()
            DemarcheInd = GetResourceKvpInt("Ora::CE::Demarche", 1)

            -- To actualize de value of LocalPlayer().Ped to make sure we do have to right ped
            LocalPlayer().Ped = PlayerPedId()
            local ped = LocalPlayer().Ped
            ResetPedMovementClipset(ped, 0)
            if DemarcheInd >= 1 then
                local clipset = demarcheAnim[DemarcheInd].dict
                RequestAnimSet(clipset)
                while not HasAnimSetLoaded(clipset) do
                    Citizen.Wait(100)
                end
                SetPedMovementClipset(ped, clipset, 0)
            end
            
            HumeurInd = GetResourceKvpInt("Ora::CE::Humeur", 1)

            ClearFacialIdleAnimOverride(ped)
            if HumeurInd >= 1 then
                local anim = emoteList[HumeurInd].dict
                SetFacialIdleAnimOverride(ped, anim, 0)
            end
        end)

        while true do
            Wait(1)
            if RageUI.Visible(RMenu:Get("personnal", "animations")) then
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        RageUI.Button(
                            "Dormir/se réveiller",
                            nil,
                            {},
                            true,
                            function(Hovered, Active, Selected)
                                if Selected then
                                    LocalPlayer().Ragdoll = not LocalPlayer().Ragdoll
                                end
                            end
                        )
                        RageUI.List(
                            "Démarche",
                            Demarche,
                            DemarcheInd,
                            nil,
                            {},
                            true,
                            function(Hovered, Active, Selected, Index)
                                DemarcheInd = Index
                                if Selected then
                                    Citizen.CreateThread(
                                        function()
                                            ped = PlayerPedId()
                                            ResetPedMovementClipset(ped, 0)
                                            if Index ~= 1 then
                                                anim = demarcheAnim[Index].dict
                                                RequestAnimSet(anim)
                                                while not HasAnimSetLoaded(anim) do
                                                    Citizen.Wait(100)
                                                end
                                                SetPedMovementClipset(ped, anim, 0)
                                            end
                                            SetResourceKvpInt("Ora::CE::Demarche", Index)
                                        end
                                    )
                                end
                            end
                        )

                        RageUI.List(
                            "Humeur",
                            Humor,
                            HumeurInd,
                            nil,
                            {},
                            true,
                            function(Hovered, Active, Selected, Index)
                                HumeurInd = Index
                                if Selected then
                                    Citizen.CreateThread(
                                        function()
                                            ped = PlayerPedId()
                                            anim = emoteList[Index].dict
                                            ClearFacialIdleAnimOverride(ped)
                                            if Index ~= 1 then
                                                SetFacialIdleAnimOverride(ped, anim, 0)
                                            end
                                            SetResourceKvpInt("Ora::CE::Humeur", Index)
                                        end
                                    )
                                end
                            end
                        )
                    end,
                    function()
                    end
                ) 
            end
        end
    end
)

RegisterCommand(
    "CancelAnim",
    function()
        TriggerEvent("Ora:Client:CancelBinSearch")
        ClearPedTasks(PlayerPedId())
    end,
    false
)

RegisterCommand(
    "ragdoll",
    function()
        if not IsPedInAnyVehicle(LocalPlayer().Ped) then
            LocalPlayer().Ragdoll = not LocalPlayer().Ragdoll
        end
    end,
    false
)

RegisterKeyMapping("ragdoll", "Dormir/Se réveiller", "keyboard", "=")
RegisterKeyMapping("CancelAnim", "Annuler l'animation", "keyboard", "X")
