---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/08/2019 00:08
---
Settings = setmetatable({}, Settings)
Settings.Color = {R = 255, G = 255, B = 255}

function Settings:Load()
    TriggerServerCallback(
        "getSettings",
        function(Data)
            if Data ~= nil then
                if Data.bind ~= nil then
                    self.Bind = json.decode(Data.bind)
                end

                if Data.colors ~= nil then
                    self.Color = json.decode(Data.colors)
                end

                if Data.hud ~= nil then
                    TriggerEvent("DisplayThisHUD", Data.hud)
                end

                if Data.food ~= nil and Data.thirst ~= nil then
                    exports['Ora_utils']:InitHungerThirst(Data.food, Data.thirst)
                end
                --self.FarmLimit = Data[1].farm_limit
                self:Format()
            end
        end
    )
end

function Settings:Format()
    local loopCount = 0
    if (self.Bind == nil) then
        while (loopCount < 50) do
            Wait(50)
            if (self.Bind ~= nil) then
                break
            end
            loopCount = loopCount + 1
        end
    end

    if (self.Bind == nil) then
        self.Bind = {}
    end

    for k, v in pairs(self.Bind) do
        KeySettings:Clear("keyboard", k, "bind")
        KeySettings:Add(
            "keyboard",
            k,
            function()
                doAnim(v.anim, nil, v.func)
            end,
            "bind"
        )
    end
    RMenu:ChangeAllColor(self.Color)
    TriggerServerEvent("saveMyColor", self.Color)
    TriggerServerEvent("saveMyBind", self.Bind)
end

function Settings:CanOpenRadioMenu()
    if (Ora.Player.Speaker.IsOnShoulder) then
        return true
    end

    if (#(Ora.Player.Speaker.Pos - GetEntityCoords(PlayerPedId())) > 5.0) then
        return true
    else
        return false
    end
end

RegisterCommand(
    "loadsettings",
    function()
        Settings:Load()
    end
)

RegisterNetEvent("vehicle:AddTempClé")
AddEventHandler(
    "vehicle:AddTempClé",
    function(plate, label)
        veh = GetMyVehicles()

        table.insert(veh.preter, {plate = plate, label = label})
        RageUI.Popup({message = "Vous avez reçu de nouvelle clé"})
        SaveMyVehicles(veh)
    end
)

RMenu.Add(
    "personnal",
    "actions",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "main"), "Actions", "Actions disponibles")
)

RMenu.Add(
    "personnal",
    "infos",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "main"), "Informations", "Informations disponibles")
)

RMenu.Add(
    "personnal",
    "actions_mykey",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "actions"), "Mes clés", "Clés possédées")
)

-- Settings
RMenu.Add(
    "personnal",
    "settings",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "main"), "Paramètres", "Paramètres disponibles")
)

RMenu.Add(
    "personnal",
    "settings_bindAnim",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings"), "Paramètres", "Assigner une animation")
)

RMenu.Add(
    "personnal",
    "settings_organisation",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings"), "Paramètres", "Mon organisation")
)

RMenu.Add(
    "personnal",
    "dealer_mode",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings"), "Paramètres", "Mode dealer")
)

RMenu.Add(
    "personnal",
    "settings_organisation_members",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings_organisation"), "Paramètres", "Faction > Membres")
)

RMenu.Add(
    "personnal",
    "settings_organisation_roles",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings_organisation"), "Paramètres", "Faction > Roles")
)

RMenu.Add(
    "personnal",
    "settings_organisation_informations",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings_organisation"), "Paramètres", "Faction > Informations")
)

RMenu.Add(
    "personnal",
    "settings_organisation_member_edit",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings_organisation"), "Paramètres", "Faction > Editer un membre")
)

RMenu.Add(
    "personnal",
    "settings_organisation_rank_edit",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings_organisation"), "Paramètres", "Faction > Editer un grade")
)

RMenu.Add(
    "personnal",
    "settings_organisation_rank_add",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings_organisation"), "Paramètres", "Faction > Créer un grade")
)

RMenu.Add(
    "personnal",
    "settings_gestionAnim",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings_bindAnim"), "Paramètres", "Supprimer ses animations")
)

RMenu.Add("personnal", "illegal", RageUI.CreateSubMenu(RMenu:Get("personnal", "actions"), "Informations", "Ma mission"))

RMenu.Add(
    "personnal",
    "settings_map",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings"), "Paramètres", "Personnaliser la carte")
)

RMenu.Add(
    "personnal",
    "settings_customColor",
    RageUI.CreateSubMenu(RMenu:Get("personnal", "settings"), "Paramètres", "Personnaliser le menu")
)
local listMoney = 1
local moneyLabel = {"Propre", "~r~Sale"}
local casqueList = {
    [19] = 68,
    [51] = 69,
    [52] = 54,
    [63] = 73,
    [74] = 75,
    [79] = 80,
    [81] = 82,
    [92] = 93
}
local vesteList = {
    [11] = 5,
    [33] = 32,
    [61] = 60,
    [76] = 75,
    [88] = 89,
    [101] = 100
}
local function Visor()
    local animstring = "anim@mp_helmets@on_foot"
    local a = nil
    if IsPedInAnyVehicle(LocalPlayer().Ped) then
        animstring = "anim@mp_helmets@on_bike@quad"
    end
    if not HasAnimDictLoaded(animstring) then
        RequestAnimDict(animstring)
        while (not HasAnimDictLoaded(animstring)) do
            Wait(0)
        end
    end
    local propsIndex = GetPedPropIndex(PlayerPedId(), 0) + 1
    if casqueList[propsIndex] ~= nil then
        if not visor then
            a = "visor_up"
        else
            a = "visor_down"
        end
        ClearPedTasks(LocalPlayer().Ped)
        TaskPlayAnim(LocalPlayer().Ped, animstring, a, 8.0, 1.0, -1, 48, 0.0, false, false, false)
        Wait(490)
        if not visor then
            SetPedPropIndex(
                LocalPlayer().Ped,
                0,
                casqueList[propsIndex] - 1,
                GetPedPropTextureIndex(LocalPlayer().Ped, 0),
                true
            )
        else
            SetPedPropIndex(
                LocalPlayer().Ped,
                0,
                casqueList[propsIndex] - 1,
                GetPedPropTextureIndex(LocalPlayer().Ped, 0),
                true
            )
        end
    elseif visor then
        for k, v in pairs(casqueList) do
            if v == propsIndex then
                if not visor then
                    a = "visor_up"
                else
                    a = "visor_down"
                end
                ClearPedTasks(LocalPlayer().Ped)
                TaskPlayAnim(LocalPlayer().Ped, animstring, a, 8.0, 1.0, -1, 48, 0.0, false, false, false)
                Wait(490)
                if not visor then
                    SetPedPropIndex(LocalPlayer().Ped, 0, k - 1, GetPedPropTextureIndex(LocalPlayer().Ped, 0), true)
                else
                    SetPedPropIndex(LocalPlayer().Ped, 0, k - 1, GetPedPropTextureIndex(LocalPlayer().Ped, 0), true)
                end
            end
        end
    end
    visor = not visor
end
local veste = false
local function Veste()
    local ped = PlayerPedId()
    local vesteIndex = GetPedDrawableVariation(ped, 11) + 1
    local animstring = "clothingtie"
    local a = "try_tie_neutral_b"
    if not HasAnimDictLoaded(animstring) then
        RequestAnimDict(animstring)
        while (not HasAnimDictLoaded(animstring)) do
            Wait(0)
        end
    end
    ClearPedTasks(LocalPlayer().Ped)
    TaskPlayAnim(LocalPlayer().Ped, animstring, a, 8.0, 1.0, -1, 48, 0.0, false, false, false)
    Wait(490)
    if vesteList[vesteIndex] ~= nil then
        SetPedComponentVariation(ped, 11, vesteList[vesteIndex] - 1, GetPedTextureVariation(ped, 11))
    elseif veste then
        for k, v in pairs(vesteList) do
            if v == vesteIndex then
                SetPedComponentVariation(ped, 11, k - 1, GetPedTextureVariation(ped, 11))
            end
        end
    end
    veste = not veste
end
RegisterCommand(
    "-visor",
    function()
        -- Visor()
    end,
    false
)
RegisterCommand(
    "+visor",
    function()
        -- Visor()
    end,
    false
)
RegisterCommand(
    "visor",
    function()
        -- Visor()
    end,
    false
)

RegisterCommand(
    "veste",
    function()
        --   Veste()
    end,
    false
)

RegisterCommand(
    "-veste",
    function()
        --   Veste()
    end,
    false
)
RegisterCommand(
    "+veste",
    function()
        --   Veste()
    end,
    false
)
local srcc = nil
local oldSave = 0
Citizen.CreateThread(
    function()
        AddTextEntry("PM_PANE_CFX", "Ora")
        while true do
            Wait(1)
            --    print(GetGameTimer())
            if RageUI.Visible(RMenu:Get("personnal", "infos")) then
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        if srcc == nil then
                            srcc = GetPlayerServerId(PlayerId())
                        end
                        RageUI.Button(
                            "Limite de métier",
                            nil,
                            {RightLabel = LocalPlayer().FarmLimit .. "/600"},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                end
                            end
                        )
                        if Ora.Identity.Job:Get().label ~= "👤 Citoyen" then
                            RageUI.Button(
                                "Métier",
                                nil,
                                {
                                    RightLabel = Ora.Identity.Job:Get().label ..
                                        " | " .. Jobs[Ora.Identity.Job:GetName()].grade[Ora.Identity.Job:Get().gradenum].label
                                },
                                true,
                                function(_, _, Selected)
                                    if Selected then
                                    end
                                end
                            )
                        end

                        if Ora.Identity.Orga:Get().label ~= "👤 Citoyen" then
                            RageUI.Button(
                                "Métier 2",
                                nil,
                                {
                                    RightLabel = Ora.Identity.Orga:Get().label ..
                                        " | " .. Jobs[Ora.Identity.Orga:GetName()].grade[Ora.Identity.Orga:Get().gradenum].label
                                },
                                true,
                                function(_, _, Selected)
                                    if Selected then
                                    end
                                end
                            )
                        end

                        RageUI.Button(
                            "Mon ID",
                            nil,
                            {RightLabel = srcc},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                end
                            end
                        )

                        RageUI.Button(
                            "Mon UUID",
                            nil,
                            {RightLabel = PlyUUID},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                end
                            end
                        )
                    end
                )
            end
            if RageUI.Visible(RMenu:Get("personnal", "actions")) then
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        RageUI.Checkbox(
                            "Visière",
                            "Permet d'activer/désactiver la visière de votre casque si il le permet",
                            visor,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                if Selected then
                                    Visor()
                                end
                            end
                        )

                        RageUI.Checkbox(
                            "Veste",
                            "Permet d'ouvrir/fermer votre veste si elle le permet",
                            veste,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                if Selected then
                                    Veste()
                                end
                            end
                        )

                        if currentMission.label ~= nil then
                            RageUI.Button(
                                "Ma mission illégale",
                                nil,
                                {},
                                true,
                                function(_, _, Selected)
                                end,
                                RMenu:Get("personnal", "illegal")
                            )
                        end

                        if (Ora.Player.Speaker.IsUsing == true) then
                            RageUI.Button(
                                "Gérer mon enceinte",
                                nil,
                                {},
                                true,
                                function(_, _, Selected)
                                    if (Selected) then
                                        if (not Settings:CanOpenRadioMenu()) then
                                            return RageUI.Popup({message = "~r~Vous êtes trop loin de votre enceinte"})
                                        end

                                        TriggerEvent("xradio:openRadio")
                                        Citizen.CreateThread(function()
                                            local timeout = 0

                                            while true do
                                                Wait(2000)
                                                if (timeout == 5 or not Ora.Player.Speaker.IsUsing or Ora.Player.Speaker.IsOnShoulder) then break end

                                                if (not Ora.Player.Speaker.IsOnShoulder or #(Ora.Player.Speaker.Pos - GetEntityCoords(PlayerPedId())) > 5.0) then
                                                    RageUI.GoBack()
                                                    break
                                                end

                                                timeout = timeout + 1
                                            end
                                        end)
                                    end
                                end,
                                Settings:CanOpenRadioMenu() and RMenu:Get("xRadio", "main") or function() end
                            )
                        end

                        RageUI.Button(
                            "Synchroniser mon personnage",
                            nil,
                            {RightLabel = oldSave ~= 0 and returnTime(oldSave - GetGameTimer(), true) or ""},
                            true,
                            function(_, _, Selected)
                                if oldSave == 0 then
                                    oldSave = 0
                                end
                                if (Selected and oldSave - GetGameTimer() <= 0) then
                                    Ora.Inventory:Save(true)
                                    Ora.Player:SavePosition()
                                    if (GetEntityHealth(LocalPlayer().Ped) ~= Ora.Health:GetCurrentRegisteredHealth()) then
                                        Ora.Health:SetMyHealth(GetEntityHealth(LocalPlayer().Ped))
                                    end
                                    RageUI.Popup(
                                        {
                                            message = "✅ Personnage synchronisé",
                                            colors = 20
                                        }
                                    )
                                    oldSave = GetGameTimer() + 600000 -- 50000
                                elseif (Selected) then
                                    ShowNotification("~r~Vous avez déjà sauvegardé votre personnage il y a peu")
                                end
                            end
                        )

                        RageUI.Separator("Rockstar Editor")

                        RageUI.Button("Record ","Permet de lancer le record d'un clip.",{},true,
                            function(_, _, Selected)
                                if Selected then
                                    StartRecording(1)
                                    ShowNotification("~r~Vous avez déjà sauvegardé votre personnage il y a peu")
                                end    
                            end
                        )

                        RageUI.Button("Sauvegarder et arrêter","Permet d'enregister et d'arrêter le clip.",{},true,
                            function(_, _, Selected)
                                if Selected then
                                    StopRecordingAndSaveClip(1)
                                    ShowNotification("Sauvegarde et arrêt du record")
                                end
                            end
                        )

                        RageUI.Button("Ouvrir Rockstar Editor","Permet de quitter le serveur et d'ouvrir Rockstar Editor.",{},true,
                            function(_, _, Selected)
                                if Selected then
                                    NetworkSessionLeaveSinglePlayer()
            		                ActivateRockstarEditor()
                                    ShowNotification("Ouverture de Rockstar Editor.")
                                end    
                            end
                        )
                    end,
                    function()
                    end
                )
            end
            if RageUI.Visible(RMenu:Get("personnal", "actions_mykey")) then
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        local vehicles = GetMyVehicles()
                        for i = 1, #vehicles.data, 1 do
                            if vehicles.data[i].settings ~= nil then
                                vehicles.data[i].plate = json.decode(vehicles.data[i].settings).plate
                            end
                            RageUI.Button(
                                vehicles.data[i].label ..
                                    " ~g~[~HUD_COLOUR_NET_PLAYER19~" .. vehicles.data[i].plate .. "~g~] ",
                                nil,
                                {},
                                true,
                                function(_, _, Selected)
                                    if Selected then
                                        if vehicles.data[i].settings ~= nil then
                                            local m = true
                                            RageUI.Popup(
                                                {
                                                    message = "Voulez vous prêter vos ~b~clés?~s~\n~g~E ~s~pour accepter\n~r~L~s~ pour refuser"
                                                }
                                            )
                                            Citizen.CreateThread(
                                                function()
                                                    Wait(5000)
                                                    if m then
                                                        m = false
                                                        RageUI.Popup({message = "~r~Annulé"})
                                                    end
                                                end
                                            )
                                            Citizen.CreateThread(
                                                function()
                                                    while m do
                                                        Wait(1)
                                                        HoverPlayer()
                                                        if IsControlJustPressed(0, Keys["E"]) then
                                                            player = GetPlayerServerIdInDirection(8.0)
                                                            if (player ~= false) then
                                                                RageUI.Popup({message = "~g~Vous avez prêter vos clés"})
                                                                TriggerServerEvent(
                                                                    "vehicle:PreterCle",
                                                                    player,
                                                                    vehicles.data[i].plate,
                                                                    vehicles.data[i].label
                                                                )
                                                            else
                                                                RageUI.Popup({message = "~r~Aucun joueurs proche"})
                                                            end
                                                            m = false
                                                        end
                                                        if IsControlJustPressed(0, Keys["L"]) then
                                                            m = false
                                                            RageUI.Popup({message = "~r~Annulé"})
                                                        end
                                                    end
                                                end
                                            )
                                        end
                                    end
                                end
                            )
                        end
                        if #vehicles.preter > 0 then
                            RageUI.CenterButton(
                                "~b~↓↓↓ ~s~Autres véhicules ~b~↓↓↓",
                                nil,
                                {},
                                true,
                                function(_, _, Selected)
                                end
                            )
                            for i = 1, #vehicles.preter, 1 do
                                RageUI.Button(
                                    vehicles.preter[i].label ..
                                        " ~g~[~HUD_COLOUR_NET_PLAYER19~" .. vehicles.preter[i].plate .. "~g~] ",
                                    nil,
                                    {},
                                    true,
                                    function(_, _, Selected)
                                        if Selected then
                                        end
                                    end
                                )
                            end
                        end
                    end,
                    function()
                    end
                )
            end
        end
    end
)
function dump(o)
    if type(o) == "table" then
        local s = "{ "
        for k, v in pairs(o) do
            if type(k) ~= "number" then
                k = '"' .. k .. '"'
            end
            s = s .. "[" .. k .. "] = " .. dump(v) .. ","
        end
        return s .. "} "
    else
        return tostring(o)
    end
end
local HUD = true
local DEALING = false
Citizen.CreateThread(
    function()

        local HUDs = {"Défaut", "Défaut violet", "Défaut vert", "Défaut rouge", "Sous la map", "Base rouge", "Base"}
        local HUDsIdx = 1

        Settings:Load()
        --RMenu:Get("personnal", "settings").CinemaMode = false
        RMenu:Get("personnal", "settings").Hud = true

        RMenu:Get("personnal", "settings_bindAnim").ArrayTouches = {
            "Pav 4.",
            "Pav 5.",
            "Pav 6.",
            "Pav 7.",
            "Pav 8.",
            "Pav 9.",
            "ALT"
        }

        RMenu:Get("personnal", "settings_bindAnim").TouchesIndex = {"N4", "N5", "N6", "N7", "N8", "N9", "LEFTALT"}

        RMenu:Get("personnal", "settings_bindAnim").IndexTouches = 1

        RMenu:Get("personnal", "settings_bindAnim").ArrayCategorie = {}

        RMenu:Get("personnal", "settings_bindAnim").IndexCategorie = 1

        RMenu:Get("personnal", "settings_bindAnim").IndexAnimations = 1

        RMenu:Get("personnal", "settings_map").ListIndex = 1
        for k, v in pairs(Animations) do
            table.insert(RMenu:Get("personnal", "settings_bindAnim").ArrayCategorie, k)
        end
        RMenu:Get("personnal", "settings_bindAnim").ArrayAnim = {}

        -- for i = 1 , #RMenu:Get('personnal', 'settings_bindAnim').ArrayCategorie,1 do
        --     for p = 1 ,#Animations[RMenu:Get('personnal', 'settings_bindAnim').ArrayCategorie[i]], 1 do
        --         table.insert( RMenu:Get('personnal', 'settings_bindAnim').ArrayAnim, Animations[RMenu:Get('personnal', 'settings_bindAnim').ArrayCategorie[i]][p].name)
        --     end
        -- end

        for i = 1, #Animations[RMenu:Get("personnal", "settings_bindAnim").ArrayCategorie[1]], 1 do
            table.insert(
                RMenu:Get("personnal", "settings_bindAnim").ArrayAnim,
                Animations[RMenu:Get("personnal", "settings_bindAnim").ArrayCategorie[1]][i].name
            )
        end

        while true do
            Wait(1)
            if RageUI.Visible(RMenu:Get("personnal", "settings")) then
                local self = RMenu:Get("personnal", "settings")
                local Player = LocalPlayer()
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()


                        RageUI.CenterButton(
                            "~h~~b~--- Paramètres RP ---~h~~s~",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        RageUI.Checkbox(
                            "Service " .. Ora.Identity.Job:Get().label,
                            "Permet d'activer/désactiver ~o~votre service",
                            Ora.Identity.Job.isOnDuty,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                Ora.Identity.Job.isOnDuty = Checked
                                if Selected then
                                    Ora.Service:UpdateService('job')
                                    RageUI.Popup(
                                        {
                                            message = Checked and "Vous avez ~g~activé~s~ votre service" or
                                                "Vous avez ~r~désactivé~s~ votre service",
                                            colors = 20
                                        }
                                    )
                                    --[[ if Job:Get().radios ~= nil then
                                        if not Checked then
                                            for i = 1, #Job:Get().radios, 1 do
                                                exports["rp-radio"]:GivePlayerAccessToFrequency(Job:Get().radios[i])
                                            end
                                        else
                                            for i = 1, #Job:Get().radios, 1 do
                                                exports["rp-radio"]:RemovePlayerAccessToFrequency(Job:Get().radios[i])
                                            end
                                        end
                                    end ]]
                                end
                            end
                        )

                        RageUI.Checkbox(
                            "Service " .. Ora.Identity.Orga:Get().label,
                            "Permet d'activer/désactiver ~o~votre service",
                            Ora.Identity.Orga.isOnDuty,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                Ora.Identity.Orga.isOnDuty = Checked
                                if Selected then
                                    Ora.Service:UpdateService('orga')
                                    RageUI.Popup(
                                        {
                                            message = Checked and "Vous avez ~g~activé~s~ votre service" or
                                                "Vous avez ~r~désactivé~s~ votre service",
                                            colors = 20
                                        }
                                    )
                                end
                            end
                        )

                        RageUI.Button(
                            "Annuler votre appel en cours",
                            nil,
                            {},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    ShowNotification("~r~Vous avez annulé l'appel")
                                    TriggerEvent("call:cancelCall")
                                end
                            end
                        )

                        RageUI.Button(
                            "Gérer vos armes",
                            nil,
                            {},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    ExecuteCommand("xkz")
                                end
                            end
                        )

                        RageUI.Button(
                            "Arrêter le cambriolage",
                            nil,
                            {},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    ShowNotification("~r~Vous avez arrêter le cambriolage")
                                    forceEndRoberry()
                                end
                            end
                        )

                        if (Ora.DrugDealing:ImDealing()) then
                            RageUI.Button(
                                "Arreter de dealer",
                                "Arret du mode ~o~dealer~s~",
                                {},
                                true,
                                function(_, _, Selected)
                                    if (Selected) then
                                        Ora.DrugDealing:StopDealing()
                                        Wait(10)
                                        RageUI.GoBack()
                                    end
                                end
                            )
                                 
                        else
                            RageUI.Button(
                                "Commencer a dealer",
                                "Démarrer le mode ~o~dealer~s~",
                                {},
                                true,
                                function(_, _, Selected)
                                end,
                                RMenu:Get("personnal", "dealer_mode")
                            )  
                        end

                        RageUI.Button(
                            "Créer/Gérer votre faction",
                            "Permet de gérer votre ~o~Faction~s~",
                            {},
                            true,
                            function(_, _, Selected)
                            end,
                            RMenu:Get("personnal", "settings_organisation")
                        )
                                        
                        RageUI.CenterButton(
                            "~h~~b~--- Paramètres visuels ---~h~~s~",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        RageUI.Checkbox(
                            "Mode cinéma",
                            "Permet d'activer/désactiver le mode ~o~cinéma",
                            self.CinemaMode,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                self.CinemaMode = Checked
                                if Selected then
                                    Player.Hud = false
                                    if not Checked then
                                        Player.Hud = true
                                    end
                                    DisplayRadar(not Checked)
                                    Player.UpdateHud()
                                    TriggerEvent("displayNourriture", not Checked)
                                    TriggerEvent("speedo:display", not Checked)
                                end
                            end
                        )
                        RageUI.Checkbox(
                            "Minimap",
                            "Permet d'activer/désactiver la ~o~minimap",
                            Minimap,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                if Selected then
                                    Minimap = Checked
                                    if Minimap == true then
                                        DisplayRadar(false)
                                    else
                                        DisplayRadar(true)
                                    end
                                end
                            end
                        )
                        RageUI.Checkbox(
                            "HUD",
                            "Permet d'activer/désactiver ~o~l'HUD",
                            HUD,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                if Selected then
                                    HUD = Checked
                                    Player.Hud = Checked
                                    TriggerEvent("displayNourriture", Checked)
                                end
                            end
                        )
                        
                        RageUI.Button(
                            "Personnaliser le menu",
                            "Permet de personnaliser les ~o~couleur ~s~du menu",
                            {},
                            true,
                            function(_, _, Selected)
                            end,
                            RMenu:Get("personnal", "settings_customColor")
                        )
                        RageUI.List(
                            "Choisir son HUD",
                            HUDs,
                            HUDsIdx,
                            nil,
                            {},
                            true,
                            function(_, Active, Selected, Index)
                                if Index ~= HUDsIdx then
                                    HUDsIdx = Index
                                end
                                if Active then
                                    TriggerEvent("DisplayThisHUD", Index)
                                end
                            end
                        )
                        RageUI.Button(
                            "Sauvegarder l'HUD",
                            nil,
                            {},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    TriggerServerEvent("SetPlyHUD", HUDsIdx)
                                end
                            end
                        )

                        -- RageUI.Button("Personnaliser la carte","Permet de modifier la ~o~carte ~s~à son gout",{},true,function(_,_,Selected)

                        -- end,RMenu:Get('personnal', 'settings_map'))
                    end,
                    function()
                    end
                )
            end
            if RageUI.Visible(RMenu:Get("personnal", "settings_map")) then
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        local self = RMenu:Get("personnal", "settings_map")
                        local blipsLabel = {}
                        for k, v in pairs(Blips.Data) do
                            table.insert(blipsLabel, k)
                        end
                        --   --(json.encode(blipsLabel))
                        RageUI.List(
                            "Blips",
                            blipsLabel,
                            self.ListIndex,
                            nil,
                            {},
                            true,
                            function(_, Active, Selected, Index)
                                self.ListIndex = Index
                            end
                        )
                        RageUI.Checkbox(
                            "Afficher",
                            "Permet d'activer/désactiver l'affichage du ~o~marqueur~s~ sur la carte",
                            Blips.Data[blipsLabel[self.ListIndex]][1].isShow,
                            {},
                            function(_, _, Selected, Checked)
                                Blips.Data[blipsLabel[self.ListIndex]][1].isShow = Checked
                                -- TODO
                            end
                        )
                        local c = Blips.Data[blipsLabel[self.ListIndex]]
                    end,
                    function()
                    end
                )
            end

            if RageUI.Visible(RMenu:Get("personnal", "dealer_mode")) then
                RageUI.DrawContent({header = true, glare = true},
                    function()
                        Ora.DrugDealing:AllowRefreshOfZones(true)
                        local zones = Ora.DrugDealing:GetZones()
                        for key, value in ipairs(zones) do
                            local boostedMessage = ""
                            if (value.isBoosted == true) then
                                Ora.DrugDealing:SetBoostedZoneId(key)
                                boostedMessage = " ~h~~g~Boost (+5$)~h~~s~"
                            end
                            if (value.isFull == true) then
                                RageUI.Button(
                                    "Dealer à " .. value.name .. boostedMessage .. " ~r~(Trop de dealers)~s~",
                                    "Impossible de dealer à " .. value.name .. " il y a déjà trop de dealers sur place" .. boostedMessage,
                                    {},
                                    false,
                                    function(_, _, Selected)
                                        if (Selected) then
                                            ShowNotification("~r~Il y a dejà trop de dealers la bas~s~")
                                        end
                                    end
                                )
                            elseif (value.hasEnoughCops == false) then
                                RageUI.Button(
                                    "Dealer à " .. value.name .. boostedMessage .. " ~r~(Pas de clients)~s~",
                                    "Impossible de dealer à " .. value.name .. " il n'y a pas de clients" .. boostedMessage,
                                    {},
                                    false,
                                    function(_, _, Selected)
                                        if (Selected) then
                                            ShowNotification("~r~Il n'y a pas de clients la bas~s~")
                                        end
                                    end
                                )
                            else
                                RageUI.Button(
                                    "~g~Dealer à " .. value.name .. "~s~" .. boostedMessage,
                                    "Dealer à " .. value.name .. boostedMessage,
                                    {},
                                    false,
                                    function(_, _, Selected)
                                        if (Selected) then
                                            if not Ora.DrugDealing:ImDealing() then
                                                ShowNotification("Vérification que vous pouvez dealer. Patientez")
                                                Wait(math.random(100, 900))
                                                Ora.DrugDealing:CanStartDealingAt(key)
                                                Wait(10)
                                                RageUI.GoBack()
                                            else
                                                RageUI.GoBack()
                                            end
                                        end
                                    end
                                )
                            end
                        end
                    end
                )
            else
                Ora.DrugDealing:AllowRefreshOfZones(false)
            end

            if RageUI.Visible(RMenu:Get("personnal", "settings_customColor")) then
                local self = RMenu:Get("personnal", "settings_customColor")
                self.EnableMouse = true
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        RageUI.Progress(
                            "Couleur 1 (R)",
                            Settings.Color.R,
                            255,
                            nil,
                            true,
                            true,
                            function(_, _, Selected, Color)
                                if Selected then
                                    count = KeyboardInput("~b~Entrez une couleur", nil, 3)
                                    count = tonumber(count)
                                    if count ~= nil and count <= 255 then
                                        Color = count
                                    end
                                end
                                Settings.Color.R = Color
                            end
                        )
                        RageUI.Progress(
                            "Couleur 2 (G)",
                            Settings.Color.G,
                            255,
                            nil,
                            true,
                            true,
                            function(_, _, Selected, Color)
                                if Selected then
                                    count = KeyboardInput("~b~Entrez une couleur", nil, 3)
                                    count = tonumber(count)
                                    if count ~= nil and count <= 255 then
                                        Color = count
                                    end
                                end
                                Settings.Color.G = Color
                            end
                        )
                        RageUI.Progress(
                            "Couleur 3 (B) ",
                            Settings.Color.B,
                            255,
                            nil,
                            true,
                            true,
                            function(_, _, Selected, Color)
                                if Selected then
                                    count = KeyboardInput("~b~Entrez une couleur", nil, 3)
                                    count = tonumber(count)
                                    if count ~= nil and count <= 255 then
                                        Color = count
                                    end
                                end
                                Settings.Color.B = Color
                            end
                        )

                        RageUI.Button(
                            "Valider",
                            "",
                            {
                                Color = {
                                    BackgroundColor = {0, 150, 0, 25}
                                }
                            },
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    RMenu:ChangeAllColor(Settings.Color)
                                    TriggerServerEvent("saveMyColor", Settings.Color)
                                end
                            end
                        )
                        RMenu:Get("personnal", "settings_customColor"):EditSpriteColor(Settings.Color)
                    end,
                    function()
                    end
                )
            end
            if RageUI.Visible(RMenu:Get("personnal", "settings_gestionAnim")) then
                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        if Settings.Bind == nil or tableCount(Settings.Bind) == 0 then
                            RageUI.Button(
                                "Vide",
                                nil,
                                {},
                                true,
                                function(_, _, Selected)
                                end
                            )
                        else
                            for k, v in pairs(Settings.Bind) do
                                RageUI.Button(
                                    "~b~[" .. k .. "]~s~ " .. v.name,
                                    nil,
                                    {},
                                    true,
                                    function(_, _, Selected)
                                        if Selected then
                                            Settings.Bind[k] = nil
                                            TriggerServerEvent("saveMyBind", Settings.Bind)
                                        end
                                    end
                                )
                            end
                        end
                    end
                )
            end

            if RageUI.Visible(RMenu:Get("personnal", "settings_organisation_informations")) then
                RageUI.DrawContent({header = true, glare = true},
                    function()
                        RageUI.CenterButton(
                            "~b~↓↓↓ ~s~"..  IllegalOrga.CURRENT_ORGA.NAME .." (".. IllegalOrga.CURRENT_ORGA.LABEL ..") ~b~↓↓↓",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )
                        RageUI.CenterButton(
                            "~h~~b~-------- MEMBRES (".. #IllegalOrga.CURRENT_ORGA.MEMBERS ..") --------~h~~s~",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        for index, value in pairs(IllegalOrga.CURRENT_ORGA.MEMBERS) do
                            RageUI.Button(
                                value.fullname .. " (" .. value.rank_name .. ")",
                                "",
                                {},
                                true,
                                function(_, _, Selected)
                                end
                            ) 
                        end

                        RageUI.CenterButton(
                            "~h~~b~-------- GRADES (".. #IllegalOrga.CURRENT_ORGA.RANKS ..") --------~h~~s~",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        for index, value in pairs(IllegalOrga.CURRENT_ORGA.RANKS) do
                            RageUI.Button(
                                value.name,
                                "",
                                {},
                                true,
                                function(_, _, Selected)
                                end
                            ) 
                        end
                    end
                )
            end

            if RageUI.Visible(RMenu:Get("personnal", "settings_organisation_members")) then

                if (IllegalOrga.MENU.INDEX_ORGA_RANKS ~= nil) then
                    IllegalOrga.MENU.INDEX_ORGA_RANKS = nil
                end

                RageUI.DrawContent({header = true, glare = true},
                    function()
                        RageUI.CenterButton(
                            "~b~↓↓↓ ~s~"..  IllegalOrga.CURRENT_ORGA.NAME .." (".. IllegalOrga.CURRENT_ORGA.LABEL ..") ~b~↓↓↓",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )
                        RageUI.CenterButton(
                            "~h~~b~-------- MEMBRES (".. #IllegalOrga.CURRENT_ORGA.MEMBERS ..") --------~h~~s~",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        for index, value in pairs(IllegalOrga.CURRENT_ORGA.MEMBERS) do
                            RageUI.Button(
                                value.fullname .. " (" .. value.rank_name .. ")",
                                "Modifier le membre " .. value.fullname,
                                {
                                    RightLabel = "Editer →"
                                },
                                true,
                                function(_, _, Selected)
                                    if (Selected) then
                                        IllegalOrga.MENU.CURRENT_PLAYER = value
                                    end
                                end,
                                RMenu:Get("personnal", "settings_organisation_member_edit")
                            ) 
                        end
                    end
                )
            end

            if RageUI.Visible(RMenu:Get("personnal", "settings_organisation_member_edit")) then

                if (IllegalOrga.MENU.CURRENT_PLAYER.NEW_VALUES == nil) then
                    IllegalOrga.MENU.CURRENT_PLAYER.NEW_VALUES = {}
                end

                RageUI.DrawContent({header = true, glare = true},
                    function()
                        RageUI.CenterButton(
                            "~b~↓↓↓ ~s~"..  IllegalOrga.MENU.CURRENT_PLAYER.fullname .." ~b~↓↓↓",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        if IllegalOrga.MENU.INDEX_ORGA_RANKS == nil then
                            IllegalOrga.MENU.INDEX_ORGA_RANKS = 1
                        end

                        RageUI.List(
                            "Grade (Actuel : " .. IllegalOrga.MENU.CURRENT_PLAYER.rank_name .. ")",
                            IllegalOrga.GetOrgaRanksAsList(),
                            IllegalOrga.MENU.INDEX_ORGA_RANKS,
                            nil,
                            {},
                            true,
                            function(_, Hover, Selected, Index)
                                if (Hover) then
                                    IllegalOrga.MENU.INDEX_ORGA_RANKS = Index
                                    IllegalOrga.MENU.CURRENT_PLAYER.NEW_VALUES.rank_id = IllegalOrga.GetRankIdByName(IllegalOrga.GetOrgaRanksAsList()[Index])
                                end
                            end
                        )

                        RageUI.CenterButton(
                            "~h~~g~Sauvegarder les modifications~h~",
                            nil,
                            {},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    RageUI.GoBack()
                                    Wait(10)
                                    TriggerServerEvent("Ora::Illegal:updateOrgPlayer", IllegalOrga.CURRENT_ORGA.ID ,IllegalOrga.MENU.CURRENT_PLAYER)
                                    IllegalOrga.MENU.CURRENT_PLAYER = {}
                                end
                            end
                        ) 

                        RageUI.CenterButton(
                            "~h~~b~----------------~h~~s~",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        RageUI.CenterButton(
                            "~h~~r~Exclure de la faction~h~",
                            nil,
                            {},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    RageUI.GoBack()
                                    Wait(10)
                                    TriggerServerEvent("Ora::Illegal:deleteOrgPlayer", IllegalOrga.CURRENT_ORGA , IllegalOrga.MENU.CURRENT_PLAYER)
                                end
                            end
                        ) 
                    end
                )
            end

            if RageUI.Visible(RMenu:Get("personnal", "settings_organisation_roles")) then
                RageUI.DrawContent({header = true, glare = true},
                    function()
                        RageUI.CenterButton(
                            "~b~↓↓↓ ~s~"..  IllegalOrga.CURRENT_ORGA.NAME .." (".. IllegalOrga.CURRENT_ORGA.LABEL ..") ~b~↓↓↓",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )
                        RageUI.CenterButton(
                            "~h~~b~-------- GRADES (".. #IllegalOrga.CURRENT_ORGA.RANKS ..") --------~h~~s~",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        for index, value in pairs(IllegalOrga.CURRENT_ORGA.RANKS) do
                            RageUI.Button(
                                value.name,
                                "Modifier le grade " .. value.name,
                                {
                                    RightLabel = "Editer →"
                                },
                                true,
                                function(_, _, Selected)
                                    if (Selected) then
                                        IllegalOrga.MENU.CURRENT_RANK = value
                                    end
                                end,
                                RMenu:Get("personnal", "settings_organisation_rank_edit")
                            ) 
                        end

                        RageUI.CenterButton(
                            "~h~~g~+ Ajouter un grade~h~",
                            nil,
                            {},
                            true,
                            function(_, _, Selected)
                                if (Selected) then
                                    IllegalOrga.MENU.CURRENT_RANK = {}
                                    IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES = {}
                                end
                            end,
                            RMenu:Get("personnal", "settings_organisation_rank_add")
                        ) 
                    end
                )
            end

            
            if RageUI.Visible(RMenu:Get("personnal", "settings_organisation_rank_add")) then
                RageUI.DrawContent({header = true, glare = true}, function()
                    if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif == nil) then
                        IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif = 0 
                    end

                    local labelInputName = "Nom du grade :"
                    if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.name ~= nil) then
                        labelInputName = labelInputName .. " " .. IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.name
                    end

                    RageUI.Button(
                        labelInputName,
                        "Définir le nom du nouveau grade",
                        {},
                        true,
                        function(_, _, Selected)
                            if Selected then
                                name = KeyboardInput("~b~Nom du grade", nil, 255)
                                if name ~= nil then
                                    IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.name = name
                                end
                            end
                        end
                    )

                    RageUI.CenterButton(
                        "~r~↓↓↓ ~r~ Permission de faction ~r~↓↓↓",
                        nil,
                        {},
                        true,
                        function(_, _, _)
                        end
                    )

                    if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif == nil) then
                        IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif = 0 
                    end

                    RageUI.Checkbox(
                        "Peut recevoir les notifications ? ",
                        "Peut recevoir les notifications d'attaques de labo et de livraison d'armes & drogues",
                        (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif == true) and true or false,
                        {},
                        function(Hovered, Ative, Selected, Checked)
                            if Selected then
                                IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif = Checked
                            end
                        end
                    )

                    if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_see_lab == nil) then
                        IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_see_lab = 0
                    end

                    RageUI.Checkbox(
                        "Peut voir les labos & dépots ?",
                        "Voir les labos & dépots d'armes sur la map",
                        (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_see_lab == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_see_lab == true) and true or false,
                        {},
                        function(Hovered, Ative, Selected, Checked)
                            if Selected then
                                IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_see_lab = Checked
                            end
                        end
                    )

                    if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_enter_lab == nil) then
                        IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_enter_lab = 0
                    end

                    RageUI.Checkbox(
                        "Peut entrer dans les labos & dépots ?",
                        "Peut entrer dans les labos & dépots d'armes",
                        (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_enter_lab == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_enter_lab == true) and true or false,
                        {},
                        function(Hovered, Ative, Selected, Checked)
                            if Selected then
                                IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_enter_lab = Checked
                            end
                        end
                    )

                    RageUI.CenterButton(
                        "~r~↓↓↓ ~r~ Permission de gestion ~r~↓↓↓",
                        nil,
                        {},
                        true,
                        function(_, _, _)
                        end
                    )

                    if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_add_members == nil) then
                        IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_add_members = 0 
                    end

                    RageUI.Checkbox(
                        "Peut Recruter ?",
                        "Peut recruter des nouveaux membres",
                        (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_add_members == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_add_members == true) and true or false,
                        {},
                        function(Hovered, Ative, Selected, Checked)
                            if Selected then
                                IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_add_members = Checked
                            end
                        end
                    )

                    if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_remove_members == nil) then
                        IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_remove_members = 0 
                    end

                    RageUI.Checkbox(
                        "Peut Exclure ?",
                        "Peut exclure des membres",
                        (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_remove_members == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_remove_members == true) and true or false,
                        {},
                        function(Hovered, Ative, Selected, Checked)
                            if Selected then
                                IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_remove_members = Checked
                            end
                        end
                    )

                    if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_rank == nil) then
                        IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_rank = 0 
                    end

                    RageUI.Checkbox(
                        "Peut Gérer les grades ?",
                        "Permet de gérer les grades",
                        (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_rank == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_rank == true) and true or false,
                        {},
                        function(Hovered, Ative, Selected, Checked)
                            if Selected then
                                IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_rank = Checked
                            end
                        end
                    )

                    if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_member == nil) then
                        IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_member = 0 
                    end

                    RageUI.Checkbox(
                        "Peut Gérer les membres ?",
                        "Permet de gérer les membres de la faction",
                        (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_member == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_member == true) and true or false,
                        {},
                        function(Hovered, Ative, Selected, Checked)
                            if Selected then
                                IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_member = Checked
                            end
                        end
                    )
                    
                    if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_delete_orga == nil) then
                        IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_delete_orga = 0 
                    end

                    RageUI.CenterButton(
                        "~h~~b~----------------~h~~s~",
                        nil,
                        {},
                        true,
                        function(_, _, _)
                        end
                    )

                    RageUI.CenterButton(
                        "~h~~g~Sauvegarder les modifications~h~",
                        nil,
                        {},
                        true,
                        function(_, _, Selected)
                            if Selected then
                                RageUI.GoBack()
                                Wait(10)
                                TriggerServerEvent("Ora::Illegal:createOrgRank", IllegalOrga.CURRENT_ORGA.ID ,IllegalOrga.MENU.CURRENT_RANK)
                            end
                        end
                    ) 

                    RageUI.CenterButton(
                        "~h~~b~----------------~h~~s~",
                        nil,
                        {},
                        true,
                        function(_, _, _)
                        end
                    )
                end)

            end

            if RageUI.Visible(RMenu:Get("personnal", "settings_organisation_rank_edit")) then

                if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES == nil) then
                    IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES = {}
                end

                RageUI.DrawContent({header = true, glare = true},
                    function()
                        RageUI.CenterButton(
                            "~b~↓↓↓ ~s~"..  IllegalOrga.MENU.CURRENT_RANK.name .." ~b~↓↓↓",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        RageUI.CenterButton(
                            "~r~↓↓↓ ~r~ Permission de faction ~r~↓↓↓",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif == nil) then
                            IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif = IllegalOrga.MENU.CURRENT_RANK.can_receive_notif 
                        end

                        local currentValue = IllegalOrga.MENU.CURRENT_RANK.can_receive_notif == 1 and "Oui" or "Non"
                        RageUI.Checkbox(
                            "Peut recevoir les notifications ? (Actuel : " .. currentValue .. ")",
                            "Peut recevoir les notifications d'attaques de labo et de livraison d'armes & drogues",
                            (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif == true) and true or false,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                if Selected then
                                    IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_receive_notif = Checked
                                end
                            end
                        )

                        if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_see_lab == nil) then
                            IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_see_lab = IllegalOrga.MENU.CURRENT_RANK.can_see_lab 
                        end

                        local currentValue = IllegalOrga.MENU.CURRENT_RANK.can_see_lab == 1 and "Oui" or "Non"

                        RageUI.Checkbox(
                            "Peut voir les labos & dépots ? (Actuel : " .. currentValue .. ")",
                            "Voir les labos & dépots d'armes sur la map",
                            (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_see_lab == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_see_lab == true) and true or false,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                if Selected then
                                    IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_see_lab = Checked
                                end
                            end
                        )

                        if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_enter_lab == nil) then
                            IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_enter_lab = IllegalOrga.MENU.CURRENT_RANK.can_enter_lab 
                        end

                        local currentValue = IllegalOrga.MENU.CURRENT_RANK.can_enter_lab == 1 and "Oui" or "Non"
                        RageUI.Checkbox(
                            "Peut entrer dans les labos & dépots ? (Actuel : " .. currentValue .. ")",
                            "Peut entrer dans les labos & dépots d'armes",
                            (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_enter_lab == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_enter_lab == true) and true or false,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                if Selected then
                                    IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_enter_lab = Checked
                                end
                            end
                        )

                        RageUI.CenterButton(
                            "~r~↓↓↓ ~r~ Permission de gestion ~r~↓↓↓",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_add_members == nil) then
                            IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_add_members = IllegalOrga.MENU.CURRENT_RANK.can_add_members 
                        end

                        local currentValue = IllegalOrga.MENU.CURRENT_RANK.can_add_members == 1 and "Oui" or "Non"

                        RageUI.Checkbox(
                            "Peut Recruter ? (Actuel : " .. currentValue .. ")",
                            "Peut recruter des nouveaux membres",
                            (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_add_members == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_add_members == true) and true or false,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                if Selected then
                                    IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_add_members = Checked
                                end
                            end
                        )

                        if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_remove_members == nil) then
                            IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_remove_members = IllegalOrga.MENU.CURRENT_RANK.can_remove_members 
                        end

                        local currentValue = IllegalOrga.MENU.CURRENT_RANK.can_remove_members == 1 and "Oui" or "Non"
                        RageUI.Checkbox(
                            "Peut Exclure ? (Actuel : " .. currentValue .. ")",
                            "Peut exclure des membres",
                            (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_remove_members == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_remove_members == true) and true or false,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                if Selected then
                                    IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_remove_members = Checked
                                end
                            end
                        )

                        if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_rank == nil) then
                            IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_rank = IllegalOrga.MENU.CURRENT_RANK.can_manage_rank 
                        end

                        local currentValue = IllegalOrga.MENU.CURRENT_RANK.can_manage_rank == 1 and "Oui" or "Non"
                        RageUI.Checkbox(
                            "Peut Gérer les grades ? (Actuel : " .. currentValue .. ")",
                            "Permet de gérer les grades",
                            (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_rank == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_rank == true) and true or false,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                if Selected then
                                    IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_rank = Checked
                                end
                            end
                        )

                        if (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_member == nil) then
                            IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_member = IllegalOrga.MENU.CURRENT_RANK.can_manage_member 
                        end

                        local currentValue = IllegalOrga.MENU.CURRENT_RANK.can_manage_member == 1 and "Oui" or "Non"
                        RageUI.Checkbox(
                            "Peut Gérer les membres ? (Actuel : " .. currentValue .. ")",
                            "Permet de gérer les membres de la faction",
                            (IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_member == 1 or IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_member == true) and true or false,
                            {},
                            function(Hovered, Ative, Selected, Checked)
                                if Selected then
                                    IllegalOrga.MENU.CURRENT_RANK.NEW_VALUES.can_manage_member = Checked
                                end
                            end
                        )
                        
                        RageUI.CenterButton(
                            "~h~~b~----------------~h~~s~",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        RageUI.CenterButton(
                            "~h~~g~Sauvegarder les modifications~h~",
                            nil,
                            {},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    RageUI.GoBack()
                                    Wait(10)
                                    ShowNotification("~g~Edition du grade ~h~".. IllegalOrga.MENU.CURRENT_RANK.name .."~h~ réalisée")
                                    TriggerServerEvent("Ora::Illegal:updateOrgRank", IllegalOrga.CURRENT_ORGA.ID ,IllegalOrga.MENU.CURRENT_RANK)
                                end
                            end
                        ) 

                        RageUI.CenterButton(
                            "~h~~b~----------------~h~~s~",
                            nil,
                            {},
                            true,
                            function(_, _, _)
                            end
                        )

                        RageUI.CenterButton(
                            "~h~~r~Supprimer ce grade~h~",
                            nil,
                            {},
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    RageUI.GoBack()
                                    Wait(10)
                                    TriggerServerEvent("Ora::Illegal:deleteOrgRank", IllegalOrga.CURRENT_ORGA.ID ,IllegalOrga.MENU.CURRENT_RANK)
                                end
                            end
                        ) 
                    end
                )
            end

            if RageUI.Visible(RMenu:Get("personnal", "settings_organisation")) then
                RageUI.DrawContent({header = true, glare = true},
                    function()
                        if (type(IllegalOrga) == "table") then
                            if (IllegalOrga.CURRENT_ORGA == nil) then
                                IllegalOrga.CURRENT_ORGA = IllegalOrga.GetEmptyOrga()
                            end
                            
                            local inputName = "Nom :"
                            if (IllegalOrga.CURRENT_ORGA.NAME ~= nil) then
                                inputName = inputName .. " " .. IllegalOrga.CURRENT_ORGA.NAME
                            end

                            local labelInputName = "Sigle :"
                            if (IllegalOrga.CURRENT_ORGA.LABEL ~= nil) then
                                labelInputName = labelInputName .. " " .. IllegalOrga.CURRENT_ORGA.LABEL
                            end

                            if (IllegalOrga.GetId() ~= nil) then
                                RageUI.CenterButton(
                                    "~b~↓↓↓ ~s~"..  IllegalOrga.CURRENT_ORGA.NAME .." (".. IllegalOrga.CURRENT_ORGA.LABEL ..") ~b~↓↓↓",
                                    nil,
                                    {},
                                    true,
                                    function(_, _, _)
                                    end
                                )

                                if IllegalOrga.GetMyRank().can_add_members == 1 then
                                    if IllegalOrga.MENU.INDEX_ORGA_RANKS == nil then
                                        IllegalOrga.MENU.INDEX_ORGA_RANKS = 1
                                    end

                                    RageUI.List(
                                        "~b~Recruter en tant que :",
                                        IllegalOrga.GetOrgaRanksAsList(),
                                        IllegalOrga.MENU.INDEX_ORGA_RANKS,
                                        nil,
                                        {},
                                        true,
                                        function(_, Hover, Selected, Index)
                                            IllegalOrga.MENU.INDEX_ORGA_RANKS = Index
                                            if (Hover == true) then
                                                HoverPlayer()
                                            end

                                            if (Selected == true) then
                                                local playerId = GetPlayerServerIdInDirection(8.0)
                                                
                                                if (playerId ~= false) then
                                                    TriggerServerEvent("Ora::Illegal:addPlayerToOrg", IllegalOrga.CURRENT_ORGA, playerId, IllegalOrga.GetRankIdByName(IllegalOrga.GetOrgaRanksAsList()[IllegalOrga.MENU.INDEX_ORGA_RANKS]))
                                                    RageUI.GoBack()
                                                else
                                                    ShowNotification("~r~Personne n'est a proximité~s~")
                                                end
                                            end
                                        end
                                    )
                                end

                                if IllegalOrga.GetMyRank().can_remove_members == 1 then
                                    RageUI.Button(
                                        "~r~Exclure",
                                        "Exclure la personne devant vous dans votre faction",
                                        {},
                                        true,
                                        function(_, Hover, Selected)
                                            if (Hover == true) then
                                                HoverPlayer()
                                            end

                                            if (Selected == true) then
                                                local playerId = GetPlayerServerIdInDirection(8.0)

                                                if (playerId ~= false) then
                                                    TriggerServerEvent("Ora::Illegal:deletePlayerFromOrgByPlayerServerId", IllegalOrga.CURRENT_ORGA, playerId)
                                                    RageUI.GoBack()
                                                else
                                                    ShowNotification("~r~Personne n'est a proximité~s~")
                                                end
                                            end
                                        end
                                    )
                                end

                                RageUI.CenterButton(
                                    "---------------------",
                                    "",
                                    {},
                                    true,
                                    function(_, _, Selected)
                                    end
                                )

                                RageUI.Button(
                                        "~b~Informations sur le groupe",
                                        "Affiche les informations du groupe",
                                        {
                                            RightLabel = "→"
                                        },
                                        true,
                                        function(_, _, Selected)
                                            -- Hover
                                        end,
                                        RMenu:Get("personnal", "settings_organisation_informations")
                                    )

                                if IllegalOrga.GetMyRank().can_manage_member == 1 then
                                    RageUI.Button(
                                        "Gérer les membres",
                                        "Gérer les membres de votre organisation",
                                        {
                                            RightLabel = "→"
                                        },
                                        true,
                                        function(_, _, Selected)
                                        end,
                                        RMenu:Get("personnal", "settings_organisation_members")
                                    )
                                end

                                if IllegalOrga.GetMyRank().can_manage_rank == 1 then
                                    RageUI.Button(
                                        "Gérer les grades",
                                        "Gérer les grades de votre organisation",
                                        {
                                            RightLabel = "→"
                                        },
                                        true,
                                        function(_, _, Selected)
                                        end,
                                        RMenu:Get("personnal", "settings_organisation_roles")
                                    )
                                end

                                RageUI.Button(
                                    "~r~Quitter l'organisation~s~",
                                    "Partir de L'organisation",
                                    {},
                                    true,
                                    function(_, _, Selected)
                                        if Selected then
                                            RageUI.GoBack()
                                            Wait(10)
                                            TriggerServerEvent("Ora::Illegal:leaveOrg", IllegalOrga.CURRENT_ORGA)
                                        end
                                    end
                                )

                                if IllegalOrga.GetMyRank().can_delete_orga == 1 then
                                    RageUI.CenterButton(
                                        "---------------------",
                                        "",
                                        {},
                                        true,
                                        function(_, _, Selected)
                                        end
                                    )
                                    RageUI.CenterButton(
                                        "~h~~r~↓↓↓ Supprimer l'organisation ↓↓↓~h~~s~",
                                        "Supprimer L'organisation",
                                        {},
                                        true,
                                        function(_, _, Selected)
                                            if Selected then
                                                RageUI.GoBack()
                                                Wait(10)
                                                TriggerServerEvent("Ora::Illegal:deleteOrg", IllegalOrga.CURRENT_ORGA)
                                            end
                                        end
                                    )
                                end
                            else
                                RageUI.Button(
                                    inputName,
                                    "Nom de votre faction",
                                    {},
                                    true,
                                    function(_, _, Selected)
                                        if Selected then
                                            name = KeyboardInput("~b~Nom de votre faction", nil, 255)
                                            if name ~= nil then
                                                IllegalOrga.CURRENT_ORGA.NAME = name
                                            end
                                        end
                                    end
                                )

                                RageUI.Button(
                                    labelInputName,
                                    "Sigle (4 Caractères max)",
                                    {},
                                    true,
                                    function(_, _, Selected)
                                        if Selected then
                                            name = KeyboardInput("~b~Sigle de votre faction (4 Caracteres max)", nil, 4)
                                            if name ~= nil then
                                                IllegalOrga.CURRENT_ORGA.LABEL = name
                                            end
                                        end
                                    end
                                )


                                RageUI.Button(
                                    "~g~Enregistrer l'organisation~s~",
                                    "Enregistrer ton orga",
                                    {},
                                    true,
                                    function(_, _, Selected)
                                        if Selected then
                                            local canSave = true
                                            if (IllegalOrga.CURRENT_ORGA.NAME == "") then
                                                canSave = false
                                                ShowNotification("~r~Veuillez saisir un nom de faction")
                                            end

                                            if (IllegalOrga.CURRENT_ORGA.LABEL == "") then
                                                canSave = false
                                                ShowNotification("~r~Veuillez saisir un label de faction")
                                            end

                                            if (canSave == true) then
                                                RageUI.GoBack()
                                                Wait(10)
                                                TriggerServerEvent("Ora::Illegal:createOrg", IllegalOrga.CURRENT_ORGA)
                                            end
                                        end
                                    end
                                )

                            end
                        end
                    end
                )
            end

            if RageUI.Visible(RMenu:Get("personnal", "settings_bindAnim")) then
                local self = RMenu:Get("personnal", "settings_bindAnim")

                RageUI.DrawContent(
                    {header = true, glare = true},
                    function()
                        RageUI.Button(
                            "Supprimer ses animations",
                            nil,
                            {},
                            true,
                            function(_, _, Selected)
                            end,
                            RMenu:Get("personnal", "settings_gestionAnim")
                        )

                        RageUI.List(
                            "Touche",
                            self.ArrayTouches,
                            self.IndexTouches,
                            nil,
                            {},
                            true,
                            function(_, _, Selected, Index)
                                self.IndexTouches = Index
                            end
                        )

                        RageUI.List(
                            "Catégorie",
                            self.ArrayCategorie,
                            self.IndexCategorie,
                            nil,
                            {},
                            true,
                            function(_, _, Selected, Index)
                                if Index ~= self.IndexCategorie then
                                    self.IndexCategorie = Index

                                    self.ArrayAnim = {}

                                    for i = 1, #Animations[self.ArrayCategorie[Index]], 1 do
                                        table.insert(self.ArrayAnim, Animations[self.ArrayCategorie[Index]][i].name)
                                    end

                                    self.IndexAnimations = 1
                                end
                            end
                        )

                        RageUI.List(
                            "Animations",
                            self.ArrayAnim,
                            self.IndexAnimations,
                            nil,
                            {},
                            true,
                            function(_, _, Selected, Index)
                                self.IndexAnimations = Index
                                if Selected then
                                    local v = Animations[self.ArrayCategorie[self.IndexCategorie]][self.IndexAnimations]
                                    doAnim(v.anim, nil, v.func)
                                end
                            end
                        )

                        RageUI.Button(
                            "Valider",
                            "Permet d'assigner l'animations sélectionné à la touche sélectionné",
                            {
                                Color = {
                                    BackgroundColor = {0, 150, 0, 25}
                                }
                            },
                            true,
                            function(_, _, Selected)
                                if Selected then
                                    local found = false
                                    if Settings.Bind == nil then
                                        Settings.Bind = {}
                                    end
                                    Settings.Bind[self.TouchesIndex[self.IndexTouches]] =
                                        Animations[self.ArrayCategorie[self.IndexCategorie]][self.IndexAnimations]
                                    Settings:Format()
                                end
                            end
                        )
                    end,
                    function()
                    end
                )
            end
        end
    end
)

DisableHud = function(bool)
    if bool == nil then
        return Player.HUDStats
    else
        if bool then
            TriggerEvent("es:setMoneyDisplay", 1.0)
        else
            TriggerEvent("es:setMoneyDisplay", 0.0)
        end
    end
end
