
var emoteFavoriteList = [];
var tabOpen = "expressions";

var preferences = {};

$(function(){
	window.onload = (e) => {
		window.addEventListener('message', (event) => {
			var item = event.data;
			if (item !== undefined && item.type === "ui") {
				if (item.display === true) {
                    $("#box").show();
				} else{
                    $("#box").hide();
                }
			}
            if (item !== undefined && item.type === "receiveFavorite") {
                emoteFavoriteList = JSON.parse(item.data);
                $('#favorite').empty();
                for(let favoriteEmote of emoteFavoriteList) {
                    let emoteTemplate = `<div class="content-item" data-name="` + favoriteEmote.emote + `"><div class="content-item-favorite-button favorite-active"><i class="fa-solid fa-star"></i></div>  <div class="content-item-name"> <span>` + favoriteEmote.emote.charAt(0).toUpperCase() + favoriteEmote.emote.slice(1) + `</span></div></div>`;
                    $('#favorite').append(emoteTemplate);
                }
                createEmoteList();
                updateFavoriteStatus();
            }
            if (item !== undefined && item.type === "receivePreferences") {
                preferences = JSON.parse(item.data);
                createEmoteList();

            }
		});
        $('#expressions').show();
        $('#expressions').addClass("active");
        for(let elt of document.getElementsByClassName('navbar-item')) {
            if(elt.dataset.name === "expressions") {
                elt.classList.add("active");
            }
            elt.addEventListener('click', (e) => {
                let type = elt.dataset.name;
                let id = "#" + type;
                tabOpen = type;
                document.getElementById("search-input").value = "";
                $(id).show();
                $(id).addClass("active");
                //Show wich tab is open
                elt.classList.add("active");
                for(let eltm of document.getElementsByClassName('navbar-item')) {
                    if(eltm.dataset.name !== type) {
                        let id = "#" + eltm.dataset.name;
                        $(id).hide();
                        $(id).removeClass("active");
                        eltm.classList.remove("active");
                    }
                }
                for(let eltm of document.getElementsByClassName('content')) {
                    for(let emote of eltm.children) {
                        emote.style.display = "flex";
                    }
                }
                searchEmote();
            });
        }
        document.onkeyup = function (data) {
            if (data.which == 27) {
                $.post('https://OraEmoteMenu/exit', JSON.stringify({}));
                return;
            }
        }
        $("#close-box").click(() => {
            $.post('https://OraEmoteMenu/exit', JSON.stringify({}));
        });
        $("#stop-walk-expression-button").click(() => {
            $.post('https://OraEmoteMenu/DisableWalkExpression', JSON.stringify({}));
        });
        // On input focus
        $(':input').on('focus', function() {
            $.post('https://OraEmoteMenu/DisableInput', JSON.stringify({}));
        });
        
        // When focus is lost
        $(':input').on('blur', function() {
            $.post('https://OraEmoteMenu/EnableInput', JSON.stringify({}));
        });
	};
});


function updateFavoriteStatus() {
    for(let emoteFavorite of document.getElementsByClassName('favorite-inactive')) {
        emoteFavorite.addEventListener('click', (e) => {
            let emote = emoteFavorite.parentElement.dataset.name;
            $.post('https://OraEmoteMenu/addFavoriteEmote', JSON.stringify({emote: emote}));
        })
    }
    for(let emoteFavorite of document.getElementsByClassName('favorite-active')) {
        emoteFavorite.addEventListener('click', (e) => {
            let emote = emoteFavorite.parentElement.dataset.name;
            $.post('https://OraEmoteMenu/removeFavoriteEmote', JSON.stringify({emote: emote}));
        })
    }
}

function searchEmote() {
    let searchInput = document.getElementById("search-input");
    searchInput.addEventListener('input', (e) => {
        let search = searchInput.value;
        for(let elt of document.getElementById(tabOpen).children) {
            if(elt.dataset.name.toLowerCase().includes(search.toLowerCase())) {
                elt.style.display = "flex";
            } else {
                elt.style.display = "none";
            }
        }
    });
}

function createEmoteList() {
    let stopButton = '<div class="content-item" data-name="stop-current"><div class="content-item-name reset-button"> <span>Réinitialiser</span></div></div>';

    for(let elt of animationType) {
        let id = "#" + elt.toLowerCase();
        $(id).empty();
        animThatHaveOptionButtons[elt] && $(id).append(stopButton)
        for(let emote of emotes[elt]) {
            let favorite = false;
            for(let emoteFavorite of emoteFavoriteList) {
                if(emote === emoteFavorite.emote) {
                    favorite = true;
                }
            }
            let emoteTemplate = `<div class="content-item" data-name="` + emote + `">` + (favorite ? `<div class="content-item-favorite-button favorite-active">` : `<div class="content-item-favorite-button favorite-inactive">`)+ (favorite ? `<i class="fa-solid fa-star"></i>` : `<i class="fa-regular fa-star"></i>`) + `</div><div class="content-item-name"> <span>` + emote.charAt(0).toUpperCase() + emote.slice(1) + `</span></div>` + (animThatHaveOptionButtons[elt] ? '<div class="content-item-save ' + (preferences[elt.toLowerCase()] == emote ? 'checked"> <i class="fa-solid fa-check' : '"> <i class="fa-solid fa-check') + '"></i></div>' : "") + `</div>`;
            $(id).append(emoteTemplate);
        }
    }
    for (let elt of document.getElementsByClassName("content-item-name")) {
        elt.addEventListener("click", (e) => {
            if ("stop-current" == elt.parentNode.dataset.name) {
                if ("expressions" === tabOpen && "" === preferences[tabOpen]) {
                    $.post("https://OraEmoteMenu/playEmote", JSON.stringify({ name: "Défaut" }));
                    return;
                }
                if ("walks" === tabOpen && "" !== preferences[tabOpen]) $.post("https://OraEmoteMenu/playEmote", JSON.stringify({ name: "Défaut" })), 
                
                $.post("https://OraEmoteMenu/playEmote", JSON.stringify({ name: preferences[tabOpen] }));
            } else {
                $.post("https://OraEmoteMenu/playEmote", JSON.stringify({ name: elt.parentNode.dataset.name }));
            }
        });
    }
    for (let saveBtn of document.getElementsByClassName("content-item-save")) {
        saveBtn.addEventListener("click", (e) => {
            let a = saveBtn.parentNode.dataset.name,
                t = tabOpen;
            void 0 === preferences[t] && (preferences[t] = ""), (preferences[t] = preferences[t] === a ? "" : a), $.post("https://OraEmoteMenu/savePreferences", JSON.stringify({ data: preferences }));
        });
    }
}

const animThatHaveOptionButtons = {
    "Expressions": true,
    "Walks": true,
}

const animationType = [
    "Expressions",
    "Walks",
    "Shared",
    "Dances",
    "Emotes",
    "PropEmotes",
]

const emotes = {
    "Expressions": [
        "Angry",
        "Drunk",
        "Dumb",
        "Electrocuted",
        "Grumpy",
        "Grumpy2",
        "Grumpy3",
        "Happy",
        "Injured",
        "Joyful",
        "Mouthbreather",
        "Never Blink",
        "One Eye",
        "Shocked",
        "Shocked2",
        "Sleeping",
        "Sleeping2",
        "Sleeping3",
        "Smug",
        "Speculative",
        "Stressed",
        "Sulking",
        "Weird",
        "Weird2"
    ],
    "Walks": [
        "Alien",
        "Armored",
        "Arrogant",
        "Brave",
        "Casual",
        "Casual2",
        "Casual3",
        "Casual4",
        "Casual5",
        "Casual6",
        "Chichi",
        "Confident",
        "Cop",
        "Cop2",
        "Cop3",
        "Default Female",
        "Default Male",
        "Drunk",
        "Drunk2",
        "Drunk3",
        "Femme",
        "Fire",
        "Fire2",
        "Fire3",
        "Flee",
        "Franklin",
        "Gangster",
        "Gangster2",
        "Gangster3",
        "Gangster4",
        "Gangster5",
        "Grooving",
        "Grooving2",
        "Guard",
        "Handcuffs",
        "Heels",
        "Heels2",
        "Hiking",
        "Hipster",
        "Hobo",
        "Hurry",
        "Janitor",
        "Janitor2",
        "Jog",
        "Lemar",
        "Lester",
        "Lester2",
        "Maneater",
        "Michael",
        "Money",
        "Muscle",
        "Posh",
        "Posh2",
        "Quick",
        "Runner",
        "Sad",
        "Sassy",
        "Sassy2",
        "Scared",
        "Sexy",
        "Shady",
        "Slow",
        "Swagger",
        "Tough",
        "Tough2",
        "Trash",
        "Trash2",
        "Trevor",
        "Wide",
        "Musclé",
        "Stylé",
        "Déterminer",
        "Sombre",
        "Jogging2",
        "Gros"
    ],
    "Shared": [
        "handshake",
        "handshake2",
        "hug",
        "hug2",
        "bro",
        "bro2",
        "give",
        "give2",
        "baseball",
        "baseballthrow",
        "stickup",
        "stickupscared",
        "punch",
        "punched",
        "headbutt",
        "headbutted",
        "slap2",
        "slap",
        "slapped",
        "slapped2"
    ],
    "Dances": [
        "uncle",
        "respect",
        "drill",
        "drill2",
        "drill3",
        "drill4",
        "drill5",
        "Drill6",
        "drill7",
        "drill8",
        "drill9",
        "drill10",
        "Drill11",
        "dancef",
        "dancef2",
        "dancef3",
        "dancef4",
        "dancef5",
        "dancef6",
        "danceslow2",
        "danceslow3",
        "danceslow4",
        "dance",
        "dance2",
        "dance3",
        "dance4",
        "danceupper",
        "danceupper2",
        "danceshy",
        "danceshy2",
        "danceslow",
        "dancesilly9",
        "dance6",
        "dance7",
        "dance8",
        "dancesilly",
        "dancesilly2",
        "dancesilly3",
        "dancesilly4",
        "dancesilly5",
        "dancesilly6",
        "dance9",
        "dancesilly8",
        "dancesilly7",
        "dance5",
        "woowalkinx",
        "bloodwalk",
        "cripwalk3",
        "shootit",
        "millyrocks",
        "shmoney",
        "dougie",
        "haiphuthon",
        "curvette",
        "tokyochall",
        "thotiana",
        "moodswings",
        "whatyouknowboutlove",
        "danceglowstick",
        "danceglowstick2",
        "danceglowstick3",
        "dancehorse",
        "dancehorse2",
        "dancehorse3",
        "zoumbacafew",
        "pistoletdroite",
        "slowcalme",
        "Egyptiennemeuf",
        "zoukmeuf",
        "ambiancemeuf",
        "dehanchemeufhautdroite",
        "dehanchemeufbasgauche",
        "dehanchemeufbasdroite",
        "dehanchemeufhautgauche",
        "hole",
        "robotarticule",
        "festival1",
        "danceapplaudit",
        "simplemeuf"
    ],
    "Emotes": [
        "pbox",
        "ch",
        "gangsign5",
        "checkwatch",
        "picking",
        "gangaim",
        "showboobs",
        "cleanleg",
        "showboobs2",
        "lockcar",
        "selfie5",
        "selfiewc",
        "selfie3",
        "selfie4",
        "Selfie1",
        "Selfie2",
        "khaby",
        "depressed",
        "carsign",
        "carsign2",
        "carlowrider",
        "carlowrider2",
        "drink",
        "beast",
        "chill",
        "cloudgaze",
        "cloudgaze2",
        "prone",
        "pullover",
        "idle",
        "idle8",
        "idle9",
        "idle10",
        "idle11",
        "idle2",
        "idle3",
        "idle4",
        "idle5",
        "idle6",
        "idle7",
        "wait3",
        "idledrunk",
        "idledrunk2",
        "idledrunk3",
        "airguitar",
        "airsynth",
        "argue",
        "argue2",
        "bartender",
        "blowkiss",
        "blowkiss2",
        "curtsy",
        "bringiton",
        "comeatmebro",
        "cop2",
        "cop3",
        "crossarms",
        "strangulate",
        "pls",
        "families",
        "vagos",
        "ballas",
        "mara",
        "celeste",
        "celeste2",
        "morgue",
        "crossarms2",
        "crossarms3",
        "crossarms4",
        "crossarms5",
        "foldarms2",
        "crossarms6",
        "foldarms",
        "crossarmsside",
        "damn",
        "damn2",
        "pointdown",
        "surrender",
        "facepalm2",
        "facepalm",
        "facepalm3",
        "facepalm4",
        "fallover",
        "fallover2",
        "fallover3",
        "fallover4",
        "fallover5",
        "fallasleep",
        "fightme",
        "fightme2",
        "finger",
        "finger2",
        "handshake",
        "handshake2",
        "wait4",
        "wait5",
        "wait6",
        "wait7",
        "wait8",
        "wait9",
        "wait10",
        "wait11",
        "hiking",
        "hug",
        "hug2",
        "hug3",
        "inspect",
        "jazzhands",
        "jog2",
        "jog3",
        "jog4",
        "jog5",
        "jumpingjacks",
        "kneel2",
        "kneel3",
        "knock",
        "knock2",
        "knucklecrunch",
        "lapdance",
        "lean2",
        "lean3",
        "lean4",
        "lean5",
        "leanflirt",
        "leanbar2",
        "leanbar3",
        "leanbar4",
        "leanhigh",
        "leanhigh2",
        "leanside",
        "leanside2",
        "leanside3",
        "leanside4",
        "leanside5",
        "me",
        "mechanic",
        "mechanic2",
        "mechanic3",
        "mechanic4",
        "medic2",
        "meditate",
        "meditate2",
        "meditate3",
        "metal",
        "no",
        "no2",
        "nosepick",
        "noway",
        "ok",
        "outofbreath",
        "pickup",
        "push",
        "push2",
        "point",
        "pushup",
        "countdown",
        "pointright",
        "salute",
        "salute2",
        "salute3",
        "scared",
        "scared2",
        "screwyou",
        "shakeoff",
        "shot",
        "sleep",
        "shrug",
        "shrug2",
        "sit",
        "sit2",
        "sit3",
        "sit4",
        "sit5",
        "sit6",
        "sit7",
        "sit8",
        "sit9",
        "sitlean",
        "sitsad",
        "sitscared",
        "sitscared2",
        "sitscared3",
        "sitdrunk",
        "sitchair2",
        "sitchair3",
        "sitchair4",
        "sitchair5",
        "sitchair6",
        "sitchairside",
        "situp",
        "clapangry",
        "slowclap3",
        "clap",
        "slowclap",
        "slowclap2",
        "smell",
        "stickup",
        "stumble",
        "stunned",
        "sunbathe",
        "sunbathe2",
        "t",
        "t2",
        "think5",
        "think",
        "think3",
        "think2",
        "thumbsup3",
        "thumbsup2",
        "thumbsup",
        "type",
        "type2",
        "type3",
        "type4",
        "warmth",
        "wave4",
        "wave2",
        "wave3",
        "wave",
        "wave5",
        "wave6",
        "wave7",
        "wave8",
        "wave9",
        "whistle",
        "whistle2",
        "yeah",
        "lift",
        "lol",
        "lol2",
        "statue2",
        "statue3",
        "gangsign",
        "gangsign2",
        "passout",
        "passout2",
        "passout3",
        "passout4",
        "passout5",
        "petting",
        "crawl",
        "flip2",
        "flip",
        "slide",
        "slide2",
        "slide3",
        "slugger",
        "flipoff",
        "flipoff2",
        "bow",
        "bow2",
        "keyfob",
        "golfswing",
        "eat",
        "reaching",
        "wait",
        "wait2",
        "wait12",
        "wait13",
        "lapdance2",
        "lapdance3",
        "lapdance3",
        "twerk",
        "slap",
        "headbutt",
        "fishdance",
        "peace",
        "peace2",
        "cpr",
        "cpr2",
        "ledge",
        "airplane",
        "peek",
        "cough",
        "stretch",
        "stretch2",
        "stretch3",
        "stretch4",
        "celebrate",
        "punching",
        "doglay",
        "dogsit",
        "superhero",
        "superhero2",
        "mindcontrol",
        "mindcontrol2",
        "clown",
        "clown2",
        "clown3",
        "clown4",
        "clown5",
        "tryclothes",
        "tryclothes2",
        "tryclothes3",
        "nervous2",
        "nervous",
        "nervous3",
        "uncuff",
        "namaste",
        "dj",
        "threaten",
        "radio",
        "pull",
        "bird",
        "chicken",
        "bark",
        "rabbit",
        "spiderman",
        "boi",
        "adjust",
        "handsup",
        "pee",
        "atm",
        "bbq",
        "bumbin",
        "bumsleep",
        "cheer",
        "chinup",
        "clipboard2",
        "cop",
        "copbeacon",
        "filmshocking",
        "flex",
        "guard",
        "hammer",
        "hangout",
        "impatient",
        "janitor",
        "jog",
        "kneel",
        "leafblower",
        "lean",
        "leanbar",
        "lookout",
        "maid",
        "medic",
        "musician",
        "notepad2",
        "parkingmeter",
        "party",
        "texting",
        "prosthigh",
        "prostlow",
        "puddle",
        "record",
        "sitchair",
        "smoke",
        "smokeweed",
        "statue",
        "sunbathe3",
        "sunbatheback",
        "weld",
        "windowshop",
        "yoga",
        "ceinturons",
        "brasdansledos",
        "brasdevant",
        "karate",
        "karate2",
        "cutthroat",
        "cutthroat2",
        "mindblown",
        "mindblown2",
        "boxing",
        "boxing2",
        "stink",
        "bike1",
        "bike2",
        "bike3",
        "bike4",
        "think4",
        "adjusttie",
        "reactiona",
        "reactanger",
        "reactwhy",
        "reactscrew",
        "reactshock",
        "reactgoodc",
        "trynewc",
        "trynewc2",
        "reacteasy",
        "reactıwill",
        "reactnoway",
        "reactbye",
        "reacthello",
        "lookatplayer",
        "reactgreat",
        "fakepunch",
        "reactdamn",
        "imtellingyou",
        "reactno",
        "dontkillme",
        "bangbang",
        "tryshirtn",
        "tryshirtp",
        "tryshoes",
        "tryshoes2",
        "overhere",
        "washingface",
        "lastday",
        "tryg",
        "pickup",
        "stretchl",
        "hos",
        "hos2",
        "guardaim",
        "gready",
        "lao",
        "toilet",
        "toilet2",
        "covermale2",
        "valet",
        "valet2",
        "sunbathem",
        "sunbathem2",
        "leancar",
        "checkout",
        "checkout2",
        "checkout",
        "readmessages",
        "readmessages2",
        "listenmusic",
        "jogger",
        "jogger2",
        "wtf",
        "ucdt",
        "warmup",
        "warmup2",
        "warmup3",
        "warmup4",
        "hmassage",
        "passout",
        "ddealer",
        "swatch",
        "checkw",
        "waitt",
        "noway",
        "tsomething",
        "lfh",
        "mstretch",
        "dj",
        "dj2",
        "dj3",
        "dj4",
        "lmic",
        "gotc",
        "vsad",
        "dgrave",
        "bow3",
        "weeding",
        "lookplan",
        "gangdrink",
        "gangdrink",
        "mleaning",
        "thanks",
        "textingmale",
        "ffb",
        "sitchair7",
        "sitchair8",
        "sitchair9",
        "sitchair10",
        "standingt",
        "standingfit",
        "standingm",
        "standingf"
    ],
    "PropEmotes": [
        "notepad",
        "box",
        "rose",
        "smoke2",
        "smoke3",
        "smoke4",
        "bong",
        "suitcase",
        "suitcase2",
        "mugshot",
        "coffee",
        "whiskey",
        "beer",
        "cup",
        "donut",
        "burger",
        "sandwich",
        "soda",
        "egobar",
        "wine",
        "flute",
        "champagne",
        "cigar",
        "cigar2",
        "guitar",
        "guitar2",
        "guitarelectric",
        "guitarelectric2",
        "book",
        "bouquet",
        "teddy",
        "backpack",
        "clipboard",
        "map",
        "beg",
        "makeitrain",
        "camera",
        "champagnespray",
        "joint",
        "cig",
        "brief3",
        "tablet",
        "tablet2",
        "phonecall",
        "phone",
        "clean",
        "clean2",
        "clean3",
        "dgrave1"
    ]
}