---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 01/09/2019 19:38
---

---func_1673
---@param camera number
---@param arg1 number
---@param arg2 number
---@param arg3 number
---@param arg4 number
---@return void
local function func_1673(camera, arg1, arg2, arg3, arg4)
    Citizen.InvokeNative(0xF55E4046F6F831DC, camera, arg1)
    Citizen.InvokeNative(0xE111A7C0D200CBC5, camera, arg2)
    SetCamDofFnumberOfLens(camera, arg3)
    SetCamDofMaxNearInFocusDistanceBlendLevel(camera, arg4)
end

---CamCreatorInit
---@return table
function CamCreatorInit()
    local _Cam = {
        f_466 = CreateCam("DEFAULT_SCRIPTED_CAMERA", false),
        f_465 = CreateCam("DEFAULT_SCRIPTED_CAMERA", false)
    }
    _Cam.f_466 = CreateCam("DEFAULT_SCRIPTED_CAMERA", false)
    _Cam.f_465 = CreateCam("DEFAULT_SCRIPTED_CAMERA", false)
    return _Cam
end

---Stage_01
---@param uParam0 table
---@return void
function Stage_01(uParam0)
    SetCamCoord(uParam0.f_466, 402.7553, -1000.622, -98.48412)
    SetCamRot(uParam0.f_466, -6.716503, 0, -0.276376, 2)
    SetCamFov(uParam0.f_466, 36.95373)
    func_1673(uParam0.f_466, 3, 1, 1.2, 1)
    SetCamActive(uParam0.f_466, true)
    StopCamShaking(uParam0.f_466, 1)
end

---Stage_01_A
---@param uParam0 table
---@return void
function Stage_01_A(uParam0)
    SetCamCoord(uParam0.f_465, 402.7391, -1003.981, -98.43439)
    SetCamRot(uParam0.f_465, -3.589798, 0, -0.276381, 2)
    SetCamFov(uParam0.f_465, 36.95373)
    func_1673(uParam0.f_465, 7, 1, 1, 1)
    SetCamActive(uParam0.f_465, true)
    StopCamShaking(uParam0.f_465, 1)
    SetCamActiveWithInterp(uParam0.f_466, uParam0.f_465, 6000, 1, 1)
end

--- Zoom out
---func_1678
---@param uParam0 table
---@return void
function func_1678(uParam0)
    PlaySoundFrontend(-1, "Zoom_Out", "MUGSHOT_CHARACTER_CREATION_SOUNDS", 0, 0, 1)

    local vVar0 = GetGameplayCamCoords()
    local vVar1 = GetCamRot(uParam0.f_465, 2)
    local fVar2 = Citizen.InvokeNative(0x80ec114669daeff4)

    SetCamCoord(uParam0.f_465, vVar0)
    SetCamRot(uParam0.f_465, vVar1, 2)
    SetCamFov(uParam0.f_465, fVar2)
    func_1673(uParam0.f_465, 3.8, 1, 1.2, 1)
    SetCamActive(uParam0.f_465, true)

    StopCamShaking(uParam0.f_465, 1)
    SetCamCoord(uParam0.f_466, 402.7553, -1000.622, -98.48412)
    SetCamRot(uParam0.f_466, -6.716503, 0, -0.276376, 2)
    SetCamFov(uParam0.f_466, 36.95373)
    StopCamShaking(uParam0.f_466, 1)
    func_1673(uParam0.f_466, 3, 1, 1.2, 1)
    SetCamActiveWithInterp(uParam0.f_466, uParam0.f_465, 300, 1, 1)
end

---func_1675
---@param uParam0 table
---@param iParam1 number
---@param Freemode table
function func_1675(uParam0, iParam1, Stats)
    local vVar0 = GetGameplayCamCoords()
    local vVar1 = GetCamRot(uParam0.f_465, 2)
    local fVar2 = Citizen.InvokeNative(0x80ec114669daeff4)
    SetCamCoord(uParam0.f_465, vVar0)
    SetCamRot(uParam0.f_465, vVar1, 2)
    SetCamFov(uParam0.f_465, fVar2)
    func_1673(uParam0.f_465, 3.0, 1.0, 1.2, 1.0)
    SetCamActive(uParam0.f_465, true)
    StopCamShaking(uParam0.f_465, 1)
    if (iParam1 == 1) then
        --- Custom
        if not (Stats) then
            SetCamCoord(uParam0.f_466, 402.7553, -1000.55, -98.48412)
            SetCamRot(uParam0.f_466, 2.254577, 0, 0.893029, 2)
            SetCamFov(uParam0.f_466, 9.999582)
            func_1673(uParam0.f_466, 3.8, 1.0, 1.2, 1.0)
        else
            SetCamCoord(uParam0.f_466, 402.7553, -1000.622, -98.48412)
            SetCamRot(uParam0.f_466, 1.260873, 0, 0.834392, 2)
            SetCamFov(uParam0.f_466, 10.01836)
            func_1673(uParam0.f_466, 3.8, 1.0, 1.2, 1.0)
        end
    else
        --- Take picture and exit
        if not (Stats) then
            SetCamCoord(uParam0.f_466, 402.6852, -1000.129, -98.46554)
            SetCamRot(uParam0.f_466, 2.366912, 0, -2.14811, 2)
            SetCamFov(uParam0.f_466, 9.958394)
            func_1673(uParam0.f_466, 4.0, 1.0, 1.2, 1.0)
        else
            SetCamCoord(uParam0.f_466, 402.6852, -1000.129, -98.46554)
            SetCamRot(uParam0.f_466, 0.861356, 0, -2.348183, 2)
            SetCamFov(uParam0.f_466, 10.00255)
            func_1673(uParam0.f_466, 4.0, 1.0, 1.2, 1.0)
        end
    end
    StopCamShaking(uParam0.f_466, 1)
    SetCamActiveWithInterp(uParam0.f_466, uParam0.f_465, 300, 1, 1)
end

---CreatorZoomIn
---@param _Cam table
---@return void
function CreatorZoomIn(_Cam)
    PlaySoundFrontend(-1, "Zoom_In", "MUGSHOT_CHARACTER_CREATION_SOUNDS", 0, 0, 1)
    if (GetEntityModel(PlayerPedId()) == GetHashKey("mp_m_freemode_01")) then
        func_1675(_Cam, 1, 1)
    else
        func_1675(_Cam, 1, 0)
    end
    RenderScriptCams(true, false, 3000, 1, 0, 0)
end

---CreatorZoomOut
---@param _Cam table
---@return void
function CreatorZoomOut(_Cam)
    PlaySoundFrontend(-1, "Zoom_Out", "MUGSHOT_CHARACTER_CREATION_SOUNDS", 0, 0, 1)
    func_1678(_Cam)
    RenderScriptCams(true, false, 3000, 1, 0, 0)
end

---CreatorTakePictureIn
---@param _Cam table
---@return void
function CreatorTakePictureIn(_Cam)
    PlaySoundFrontend(-1, "Zoom_In", "MUGSHOT_CHARACTER_CREATION_SOUNDS", 0, 0, 1)
    if (GetEntityModel(PlayerPedId()) == GetHashKey("mp_m_freemode_01")) then
        func_1675(_Cam, 2, 1)
    else
        func_1675(_Cam, 2, 0)
    end
    RenderScriptCams(false, false, 3000, 1, 0, 0)

    SetFocusEntity(PlayerPedId())
end
