name: deploy
on:
  push:
    tags:
      dev-*
      prod-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Deploy to develop
        id: deployRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://212.227.190.245/deploy.php'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
          data: "tag=${{ env.RELEASE_VERSION }}"
      - name: Show logs
        run: echo ${{ steps.deployRequest.outputs.response }}
